<a href="https://colab.research.google.com/github/hidaaprilia/web-mapping-system/blob/main/01_Evaluasi_SUSENAS03_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **01 DATA PREPARATION**

In [ ]:
%pip install openpyxl
%pip install xlrd
%pip install pyxlsb
%pip install dbfread
%pip install simpledbf

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pyxlsb in /usr/local/lib/python3.12/dist-packages (1.0.10)
Requirement already satisfied: dbfread in /usr/local/lib/python3.12/dist-packages (2.0.7)
Requirement already satisfied: simpledbf in /usr/local/lib/python3.12/dist-packages (0.2.6)

In [ ]:
import pandas as pd  # Pandas for data manipulation and analysis
import numpy as np  # NumPy for numeric computation
from google.colab import drive
from dbfread import DBF
import pandas as pd

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 01 Persiapan Data KOR

In [ ]:
file_path = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/1_1. Data KOR ART.xls'
file_path2 ='/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/1_2. Data KOR ART.xls'
file_path3 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/1_3. Data KOR ART.xls'
file_path4 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/2_1. Data KOR RT.xls'
file_path5 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/2_2. Data KOR RT.xls'
file_path6 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/2_3. Data KOR RT.xls'
file_path7 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/2_4. Data KOR RT.xls'

In [ ]:
#KOR 1_1. DATA KOR ART
table = DBF(file_path)
df = pd.DataFrame(iter(table))

#KOR 1_2. DATA KOR ART
table2 = DBF(file_path2)
df2 = pd.DataFrame(iter(table2))

#KOR 1_3. DATA KOR ART
table3 = DBF(file_path3)
df3 = pd.DataFrame(iter(table3))

#KOR 2_1. DATA KOR RT
table4 = DBF(file_path4)
df4 = pd.DataFrame(iter(table4))

#KOR 2_2. DATA KOR RT
table5 = DBF(file_path5)
df5 = pd.DataFrame(iter(table5))

#KOR 2_3. DATA KOR RT
table6 = DBF(file_path6)
df6 = pd.DataFrame(iter(table6))

#KOR 2_4. DATA KOR RT
table7 = DBF(file_path7)
df7 = pd.DataFrame(iter(table7))

In [ ]:
#Making an ID Column untuk KOR 1_1. DATA KOR ART
df["NKS_STR"] = df["NKS"].astype(str)
df["NURT_STR"] = df["NURT"].astype(str)
df["R401_STR"] = df["R401"].astype(str)
df["ID_ruta"] =  df["NKS_STR"] + df["NURT_STR"]
df["ID_art"] =  df["ID_ruta"] + df["R401_STR"]

#Making an ID Column untuk KOR 1_2. DATA KOR ART
df2["NKS_STR"] = df2["NKS"].astype(str)
df2["NURT_STR"] = df2["NURT"].astype(str)
df2["R401_STR"] = df2["R401"].astype(str)
df2["ID_ruta"] =  df2["NKS_STR"] + df2["NURT_STR"]
df2["ID_art"] =  df2["ID_ruta"] + df2["R401_STR"]

#Making an ID Column untuk KOR 1_3. DATA KOR ART
df3["NKS_STR"] = df3["NKS"].astype(str)
df3["NURT_STR"] = df3["NURT"].astype(str)
df3["R401_STR"] = df3["R401"].astype(str)
df3["ID_ruta"] =  df3["NKS_STR"] + df3["NURT_STR"]
df3["ID_art"] =  df3["ID_ruta"] + df3["R401_STR"]

#Making an ID Column untuk KOR 2_1. DATA KOR RT
df4["NKS_STR"] = df4["NKS"].astype(str)
df4["NURT_STR"] = df4["NURT"].astype(str)
df4["ID_ruta"] =  df4["NKS_STR"] + df4["NURT_STR"]

#Making an ID Column untuk KOR 2_2. DATA KOR RT
df5["NKS_STR"] = df5["NKS"].astype(str)
df5["NURT_STR"] = df5["NURT"].astype(str)
df5["ID_ruta"] =  df5["NKS_STR"] + df5["NURT_STR"]

#Making an ID Column untuk KOR 2_3. DATA KOR RT
#df6["NKS_STR"] = df6["NKS"].astype(str)
#df6["NURT_STR"] = df6["NURT"].astype(str)
#df6["ID_ruta"] =  df6["NKS_STR"] + df6["NURT_STR"]

#Making an ID Column untuk KOR 2_4. DATA KOR RT
#df7["NKS_STR"] = df7["NKS"].astype(str)
#df7["NURT_STR"] = df7["NURT"].astype(str)
#df7["ID_ruta"] =  df7["NKS_STR"] + df7["NURT_STR"]

In [ ]:
#Merging DF KOR_ART
df2_subset = df2.iloc[:, 40:181]
df3_subset = df3.iloc[:, 36:47]
df_kor_art=pd.concat([df, df2_subset,df3_subset], axis=1)
df_kor_art.head()

,ROWNUMBER,PROP,NAMAPROPIN,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,...,NAMA_PPK,URUT_INFO_,R1401A,R1401B,R1402A,R1402B,R1403,R1404A,R1404B,R1404C
0,1,15,JAMBI,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,19,PEMATANG PAUH,2,...,DIKI FERNANDO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,15,JAMBI,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,19,PEMATANG PAUH,2,...,DHARA ALINDHY. RY,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,15,JAMBI,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,38,GEMURUH,2,...,JAMALUDIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,15,JAMBI,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,39,PEMATANG TEMBESU,2,...,A. RAFIK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,15,JAMBI,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,39,PEMATANG TEMBESU,2,...,EFRINA WATI,2.0,1.0,19.0,1.0,19.0,2.0,NaN,NaN,NaN

In [ ]:
#Merging DF KOR_RT
df5_subset = df5.iloc[:, 25:147]
df_kor_rt=pd.concat([df4, df5_subset], axis=1)
df_kor_rt.head()
df_kor_rt.to_excel("df_kor_rt.xlsx", index=False)   # requires openpyxl or xlsxwriter installed

In [ ]:
#Merging DF KOR_ART dan DF Kor_Ruta - 1
df_kor_rt_columns_list=df_kor_rt.columns.tolist()
print(df_kor_rt_columns_list)

['ROWNUMBER', 'PROP', 'NAMAPROPIN', 'KAB', 'NAMAKABUPA', 'KEC', 'NAMAKECAMA', 'DESA', 'NAMADESA', 'KLASIFIKAS', 'NKS', 'SLS', 'NURT', 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT', 'ALAMAT', 'NUC1', 'R110', 'CATATAN', 'R111', 'R101A', 'R101B', 'R101C', 'R112L_K', 'R112L_D', 'R112L_M', 'R112L_S', 'R112B_K', 'R112B_D', 'R112B_M', 'R112B_S', 'NAMAPENCAC', 'R201K3_1', 'R201K3_2', 'R201K4_1', 'R201K4_2', 'TTDPENCACA', 'NAMAPENGAW', 'R202K3_1', 'R202K3_2', 'R202K4_1', 'R202K4_2', 'TTDPENGAWA', 'R203', 'R301', 'R302', 'R303', 'R304', 'R305', 'W_MULAIJ', 'W_MULAIM', 'NUINFO_FIE', 'R1501', 'R1502', 'R1503', 'R1504', 'R1505', 'R1506', 'R1507', 'R1508', 'NUINFORT2', 'R1601', 'R1602', 'R1602LAIN', 'R1603', 'R1604', 'R1605', 'R1606', 'R1607', 'R1608', 'R1609A', 'R1609B', 'R1609C', 'R1609D', 'R1609E', 'R1610A', 'R1610B', 'R1610C', 'R1611A', 'R1611B', 'R1612', 'R1613A', 'R1613B', 'R1613C', 'R1613D', 'R1613E', 'R1614A', 'R1614B', 'R1615A', 'R1615B', 'R1615C', 'R1616A', 'R1616B1', 'R1616B2', 'R1616B3', 'R1617', 'R1618', 'R1619A', 'R1619B', 'R1619C', 'R1620A', 'R1620B', 'R1620C', 'R1620D', 'R1621A', 'R1621B', 'R1621C', 'R1621D', 'R1621E', 'R1621F', 'R1621G', 'R1622', 'R1701A', 'R1701B', 'R1701C', 'R1701D', 'R1701E', 'R1701F', 'R1701G', 'R1701H', 'R1701I', 'R1701J', 'R1701K', 'R1702A', 'R1702B', 'R1801A', 'R1801B', 'R1801C', 'R1801D', 'R1801E', 'R1801F', 'R1801G', 'R1801H', 'R1801I', 'R1801J', 'R1801K', 'R1801L', 'R1801M', 'R1801N', 'R1802_A', 'R1802_B', 'R1802_C', 'R1802_D', 'R1901A', 'R1901B', 'R1901C', 'STATUSDOK', 'ISTRANSFER', 'JUMLAHENTR', 'OPERATORDO', 'LAMAENTRI', 'NKS_STR', 'NURT_STR', 'ID_ruta', 'R2001A1', 'R2001A2', 'R2001A3', 'R2001B1', 'R2001B2', 'R2001B3', 'R2001C1', 'R2001C2', 'R2001C3', 'R2001D1', 'R2001D2', 'R2001D3', 'R2001E1', 'R2001E2', 'R2001E3', 'R2001F1', 'R2001F2', 'R2001F3', 'R2002', 'R2003A', 'R2003B', 'R2003C_A', 'R2003C_B', 'R2003C_C', 'R2003C_D', 'R2003C_E', 'R2003C_F', 'R2003C_G', 'R2003C_LAI', 'R2004', 'R2005', 'R2006A2', 'R2006BI2', 'R2006B2', 'R2006C2', 'R2006D2', 'R2006E2_A', 'R2006E2_B', 'R2006E2_C', 'R2006E2_D', 'R2006E2_E', 'R2006E2_F', 'R2006E2_G', 'R2006E2_LA', 'R2006A3', 'R2006BI3', 'R2006B3', 'R2006C3', 'R2006D3', 'R2006E3_A', 'R2006E3_B', 'R2006E3_C', 'R2006E3_D', 'R2006E3_E', 'R2006E3_F', 'R2006E3_G', 'R2006E3_LA', 'R2006A4', 'R2006BI4', 'R2006B4', 'R2006C4', 'R2006D4', 'R2006E4_A', 'R2006E4_B', 'R2006E4_C', 'R2006E4_D', 'R2006E4_E', 'R2006E4_F', 'R2006E4_G', 'R2006E4_LA', 'R2006A5', 'R2006B5', 'R2006BI5', 'R2006C5', 'R2006D5', 'R2006E5_A', 'R2006E5_B', 'R2006E5_C', 'R2006E5_D', 'R2006E5_E', 'R2006E5_F', 'R2006E5_G', 'R2006E5_LA', 'R2007A', 'R2007B', 'R2008A', 'R2008B', 'R2008C', 'R2008D', 'R2009A', 'R2009B1', 'R2009B2', 'R2009B3', 'R2009B4', 'R2009B5', 'R2010A', 'R2010A1', 'R2010A2', 'R2010A3', 'R2010A4', 'R2010A5', 'R2010B', 'R2010B1', 'MTGL1', 'MBLN1', 'MMULAI1J', 'MMULAI1M', 'MSELESAI1J', 'MSELESAI1M', 'MTGL2', 'MBLN2', 'MMULAI2J', 'MMULAI2M', 'MSELESAI2J', 'MSELESAI2M', 'MJAMSELESE', 'MMENITSELE', 'STATUSDOK', 'ISTRANSFER', 'JUMLAHENTR', 'OPERATORDO', 'LAMAENTRI']

In [ ]:
#Merging DF KOR_ART dan DF Kor_Ruta - 2

cols_to_drop=['ROWNUMBER', 'PROP', 'NAMAPROPIN', 'KAB', 'NAMAKABUPA', 'KEC', 'NAMAKECAMA',
              'DESA', 'NAMADESA', 'KLASIFIKAS', 'NKS', 'SLS', 'NURT', 'SEMESTER',
              'NAMAKRTDSR', 'NAMAKRT', 'ALAMAT', 'NUC1', 'R110', 'CATATAN', 'R111', 'R101A',
              'R101B', 'R101C', 'R112L_K', 'R112L_D', 'R112L_M', 'R112L_S', 'R112B_K', 'R112B_D',
              'R112B_M', 'R112B_S', 'NAMAPENCAC', 'R201K3_1', 'R201K3_2', 'R201K4_1', 'R201K4_2', 'TTDPENCACA',
              'NAMAPENGAW', 'R202K3_1', 'R202K3_2', 'R202K4_1', 'R202K4_2', 'TTDPENGAWA', 'R203', 'R301', 'R302',
              'R303', 'R304', 'R305', 'W_MULAIJ', 'W_MULAIM', 'NUINFO_FIE',
              'ISTRANSFER','JUMLAHENTR','LAMAENTRI','OPERATORDO','STATUSDOK','NKS_STR', 'NURT_STR']
df_kor_rt_unique=df_kor_rt.drop(cols_to_drop, axis=1)


df_kor = pd.merge(df_kor_art, df_kor_rt_unique, on="ID_ruta", how="left")
df_kor.to_excel("df_kor.xlsx", index=False)

## 02 Persiapan Data KP

In [ ]:
file_pathKP = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/3. Data KP Komoditi Makanan RT.xls'
file_pathKP2 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/4. Data KP Komoditi Makanan ART.xls'
file_pathKP3 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/5. Data KP Komoditi Non Makanan.xls'
file_pathKP4 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/6. Data KP Rekap B43 ART.xls'
file_pathKP5 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/7. Data KP ART B5A.xls'
file_pathKP6 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/8. Data KP ART B5B.xls'
file_pathKP7 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/9. Data KP Rekap B43 RT.xls'
file_pathKP8 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/10. Data KP Rekap B5A-B5E RT.xls'
file_pathKP9 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/11. Data KP Rekap B5F-B5G RT .xls'
file_pathKP10 = '/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/00 Hasil Export Data/12. Data KP Rekap B6-B7 RT.xls'

In [ ]:
#KP_3. Data KP Komoditi Makanan RT
table_kp1 = DBF(file_pathKP)
df_kp1 = pd.DataFrame(iter(table_kp1))

#KP_4. Data KP Komoditi Makanan ART
table_kp2 = DBF(file_pathKP2)
df_kp2 = pd.DataFrame(iter(table_kp2))

#KP_5. Data KP Komoditi Non Makanan
table_kp3 = DBF(file_pathKP3)
df_kp3 = pd.DataFrame(iter(table_kp3))

#KP_6. Data KP Rekap B43 ART
table_kp4 = DBF(file_pathKP4)
df_kp4 = pd.DataFrame(iter(table_kp4))

#KP_7. Data KP ART B5A
table_kp5 = DBF(file_pathKP5)
df_kp5 = pd.DataFrame(iter(table_kp5))

#KP_8. Data KP ART B5B
table_kp6 = DBF(file_pathKP6)
df_kp6 = pd.DataFrame(iter(table_kp6))

#KP_9. Data KP Rekap B43 RT
table_kp9 = DBF(file_pathKP7)
df_kp9 = pd.DataFrame(iter(table_kp9))

#KP_10. Data KP Rekap B5A-B5E RT
table_kp10 = DBF(file_pathKP8)
df_kp10 = pd.DataFrame(iter(table_kp10))

#KP_11. Data KP Rekap B5F-B5G RT
table_kp11 = DBF(file_pathKP9)
df_kp11 = pd.DataFrame(iter(table_kp11))

#KP_12. Data KP Rekap B6-B7 RT
table_kp12 = DBF(file_pathKP10)
df_kp12 = pd.DataFrame(iter(table_kp12))

In [ ]:
#Making an ID Column untuk KP 3. Data KP Komoditi Makanan RT
df_kp1["NKS_STR"] = df_kp1["NKS"].astype(str)
df_kp1["NURT_STR"] = df_kp1["NURT"].astype(str)
df_kp1["ID_ruta"] =  df_kp1["NKS_STR"] + df_kp1["NURT_STR"]

#Making an ID Column untuk KP 4. Data KP Komoditi Makanan ART
df_kp2["NKS_STR"] = df_kp2["NKS"].astype(str)
df_kp2["NURT_STR"] = df_kp2["NURT"].astype(str)
df_kp2["ID_ruta"] =  df_kp2["NKS_STR"] + df_kp2["NURT_STR"]

#Making an ID Column untuk #KP_5. Data KP Komoditi Non Makanan
df_kp3["NKS_STR"] = df_kp3["NKS"].astype(str)
df_kp3["NURT_STR"] = df_kp3["NURT"].astype(str)
df_kp3["ID_ruta"] = df_kp3["NKS_STR"] + df_kp3["NURT_STR"]

#Making an ID Column untuk #KP_6. Data KP Rekap B43 ART
df_kp4["R401_STR"] = df_kp4["R401"].astype(str)
df_kp4["NKS_STR"] = df_kp4["NKS"].astype(str)
df_kp4["NURT_STR"] = df_kp4["NURT"].astype(str)
df_kp4["ID_ruta"] = df_kp4["NKS_STR"] + df_kp4["NURT_STR"]
df_kp4["ID_art"] =  df_kp4["ID_ruta"] + df_kp4["R401_STR"]

#Making an ID Column untuk #KP_7. Data KP ART B5A
df_kp5["R401_STR"] = df_kp5["R401"].astype(str)
df_kp5["NKS_STR"] = df_kp5["NKS"].astype(str)
df_kp5["NURT_STR"] = df_kp5["NURT"].astype(str)
df_kp5["ID_ruta"] = df_kp5["NKS_STR"] + df_kp5["NURT_STR"]
df_kp5["ID_art"] =  df_kp5["ID_ruta"] + df_kp5["R401_STR"]

#Making an ID Column untuk #KP_8. Data KP ART B5B
df_kp6["R401_STR"] = df_kp6["R401"].astype(str)
df_kp6["NKS_STR"] = df_kp6["NKS"].astype(str)
df_kp6["NURT_STR"] = df_kp6["NURT"].astype(str)
df_kp6["ID_ruta"] = df_kp6["NKS_STR"] + df_kp6["NURT_STR"]
df_kp6["ID_art"] =  df_kp6["ID_ruta"] + df_kp6["R401_STR"]

#Making an ID Column untuk #KP_10. Data KP Rekap B5A-B5E RT
df_kp9["NKS_STR"] = df_kp9["NKS"].astype(str)
df_kp9["NURT_STR"] = df_kp9["NURT"].astype(str)
df_kp9["ID_ruta"] = df_kp9["NKS_STR"] + df_kp9["NURT_STR"]

#Making an ID Column untuk #KP_10. Data KP Rekap B5A-B5E RT
df_kp10["NKS_STR"] = df_kp10["NKS"].astype(str)
df_kp10["NURT_STR"] = df_kp10["NURT"].astype(str)
df_kp10["ID_ruta"] = df_kp10["NKS_STR"] + df_kp10["NURT_STR"]

#Making an ID Column untuk #KP_11. Data KP Rekap B5F-B5G RT
df_kp11["NKS_STR"] = df_kp11["NKS"].astype(str)
df_kp11["NURT_STR"] = df_kp11["NURT"].astype(str)
df_kp11["ID_ruta"] = df_kp11["NKS_STR"] + df_kp11["NURT_STR"]

#Making an ID Column untuk #KP_12. Data KP Rekap B6-B7 RT
df_kp12["NKS_STR"] = df_kp12["NKS"].astype(str)
df_kp12["NURT_STR"] = df_kp12["NURT"].astype(str)
df_kp12["ID_ruta"] = df_kp12["NKS_STR"] + df_kp12["NURT_STR"]

In [ ]:
#Making a dummy table to store all the name of the food commodities
dummy = pd.read_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/02 Dummy Table_KP Makanan.xlsx', engine="openpyxl", dtype={
    "NKS": str,       # force ID_ruta as string
    "NURT": str     # force NOURUTART as integer
})
dummy["ID_ruta"]=dummy["NKS"]+dummy["NURT"]
komo = pd.DataFrame({"NOMOURUTKOMO": range(1, 226)})
dummy_table = dummy.merge(komo, how="cross")
dummy_table["NOMOURUTKOMO"] = dummy_table["NOMOURUTKOMO"].astype(str)
dummy_table["ID_komo"]=dummy_table["ID_ruta"]+dummy_table["NOMOURUTKOMO"]


#Making a dummy table to store all the name of non-food commodities
dummy2 = pd.read_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/03 Dummy Table_KP NonMakanan.xlsx', engine="openpyxl", dtype={
    "NKS": str,       # force ID_ruta as string
    "NURT": str     # force NOURUTART as integer
})
dummy2["ID_ruta"]=dummy2["NKS"]+dummy2["NURT"]
komo2 = pd.DataFrame({"NOMOURUTKOMO": range(226, 348)})
dummy_table2 = dummy2.merge(komo2, how="cross")
dummy_table2["NOMOURUTKOMO"] = dummy_table2["NOMOURUTKOMO"].astype(str)
dummy_table2["ID_komo"]=dummy_table2["ID_ruta"]+dummy_table2["NOMOURUTKOMO"]

dummy_table.head()

     NKS NURT ID_ruta NOMOURUTKOMO  ID_komo
0  00040    1  000401            1  0004011
1  00040    1  000401            2  0004012
2  00040    1  000401            3  0004013
3  00040    1  000401            4  0004014
4  00040    1  000401            5  0004015

In [ ]:
kp1=df_kp1[["NKS_STR","NURT_STR","ID_ruta","NOURUTKOMO","KOLOM5","KOLOM6"]].copy()
kp1["NOURUTKOMO"] = kp1["NOURUTKOMO"].astype(str)
kp1["ID_komo"]=kp1["ID_ruta"]+kp1["NOURUTKOMO"]
kp1.head()

  NKS_STR NURT_STR ID_ruta NOURUTKOMO  KOLOM5   KOLOM6   ID_komo
0   00040        1  000401          1     NaN  40000.0   0004011
1   00040        1  000401          2    2.50  40000.0   0004012
2   00040        1  000401         16     NaN  53000.0  00040116
3   00040        1  000401         29    1.00  43000.0  00040129
4   00040        1  000401         56    1.55  10000.0  00040156

In [ ]:
kp1=df_kp1[["NKS_STR","NURT_STR","ID_ruta","NOURUTKOMO","KOLOM5","KOLOM6"]].copy()
kp1["NOURUTKOMO"] = kp1["NOURUTKOMO"].astype(str)
kp1["ID_komo"]=kp1["ID_ruta"]+kp1["NOURUTKOMO"]
kp1= kp1.drop(columns=["NKS_STR","NURT_STR","ID_ruta","NOURUTKOMO"])

kp1_full=pd.merge(dummy_table, kp1, on="ID_komo", how="left")
kp1_full["NOMOURUTKOMO"] = kp1_full["NOMOURUTKOMO"].astype(int)
kp1_full["NURT"] = kp1_full["NURT"].astype(int)
kp1_full.sort_values(by=["NURT","ID_ruta", "NOMOURUTKOMO"], ascending=[True, False, False])

kp1_full

          NKS  NURT  ID_ruta  NOMOURUTKOMO     ID_komo  KOLOM5   KOLOM6
0       00040     1   000401             1     0004011     NaN  40000.0
1       00040     1   000401             2     0004012     2.5  40000.0
2       00040     1   000401             3     0004013     NaN      NaN
3       00040     1   000401             4     0004014     NaN      NaN
4       00040     1   000401             5     0004015     NaN      NaN
...       ...   ...      ...           ...         ...     ...      ...
148495  50217    10  5021710           221  5021710221     NaN      NaN
148496  50217    10  5021710           222  5021710222     NaN      NaN
148497  50217    10  5021710           223  5021710223     NaN      NaN
148498  50217    10  5021710           224  5021710224     NaN      NaN
148499  50217    10  5021710           225  5021710225     NaN      NaN

[148500 rows x 7 columns]

In [ ]:
#Merging Dummy Table with df_kp1
kp1=df_kp1[["NKS_STR","NURT_STR","ID_ruta","NOURUTKOMO","KOLOM5","KOLOM6"]].copy()
kp1["NOURUTKOMO"] = kp1["NOURUTKOMO"].astype(str)
kp1["ID_komo"]=kp1["ID_ruta"]+kp1["NOURUTKOMO"]
kp1= kp1.drop(columns=["NKS_STR","NURT_STR","ID_ruta","NOURUTKOMO"])

kp1_full=pd.merge(dummy_table, kp1, on="ID_komo", how="left")
kp1_full["NOMOURUTKOMO"] = kp1_full["NOMOURUTKOMO"].astype(int)
kp1_full["NURT"] = kp1_full["NURT"].astype(int)
kp1_full.sort_values(by=["NURT","ID_ruta", "NOMOURUTKOMO"], ascending=[True, False, False])

#Merging Dummy Table with df_kp2
kp2=df_kp2[["NKS_STR","NURT_STR","ID_ruta","NOURUTKOMO","KOLOM5","KOLOM6"]].copy()
kp2["NOURUTKOMO"] = kp2["NOURUTKOMO"].astype(str)
kp2["ID_komo"]=kp2["ID_ruta"]+kp2["NOURUTKOMO"]
kp2= kp2.drop(columns=["NKS_STR","NURT_STR","ID_ruta","NOURUTKOMO"])
kp2_full=pd.merge(dummy_table, kp2, on="ID_komo", how="left")
kp2_full["NOMOURUTKOMO"] = kp2_full["NOMOURUTKOMO"].astype(int)
kp2_full["NURT"] = kp2_full["NURT"].astype(int)
kp2_full.sort_values(by=["NURT","ID_ruta", "NOMOURUTKOMO"], ascending=[True, False, False])


#Merging Dummy Table with df_kp3
kp3=df_kp3[["NKS_STR","NURT_STR","ID_ruta","NOURUTKOMO","KOLOM4A","KOLOM5","KOLOM6","KOLOM7"]].copy()
kp3["NOURUTKOMO"] = kp3["NOURUTKOMO"].astype(str)
kp3["ID_komo"]=kp3["ID_ruta"]+kp3["NOURUTKOMO"]
kp3= kp3.drop(columns=["NKS_STR","NURT_STR","ID_ruta","NOURUTKOMO"])
kp3_full=pd.merge(dummy_table2, kp3, on="ID_komo", how="left")
kp3_full["NOMOURUTKOMO"] = kp3_full["NOMOURUTKOMO"].astype(int)
kp3_full["NURT"] = kp3_full["NURT"].astype(int)
kp3_full.sort_values(by=["NURT","ID_ruta", "NOMOURUTKOMO"], ascending=[True, False, False])

,NKS,NURT,ID_ruta,NOMOURUTKOMO,ID_komo,KOLOM4A,KOLOM5,KOLOM6,KOLOM7
29401,993,1,9931,347,9931347,NaN,NaN,NaN,NaN
29400,993,1,9931,346,9931346,NaN,NaN,NaN,NaN
29399,993,1,9931,345,9931345,NaN,NaN,NaN,NaN
29398,993,1,9931,344,9931344,NaN,NaN,NaN,NaN
29397,993,1,9931,343,9931343,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1102,00040,10,0004010,230,0004010230,NaN,NaN,NaN,NaN
1101,00040,10,0004010,229,0004010229,NaN,NaN,NaN,NaN
1100,00040,10,0004010,228,0004010228,NaN,NaN,NaN,NaN
1099,00040,10,0004010,227,0004010227,NaN,NaN,NaN,NaN
1098,00040,10,0004010,226,0004010226,NaN,NaN,NaN,NaN

In [ ]:
kp1_pivot= pd.pivot_table(kp1_full,
                          index="ID_ruta",
                          columns="NOMOURUTKOMO",
                          values="KOLOM6",
                          aggfunc="sum",
                          fill_value=0).reset_index()
kp2_pivot= pd.pivot_table(kp2_full,
                          index="ID_ruta",
                          columns="NOMOURUTKOMO",
                          values="KOLOM6",
                          aggfunc="sum",
                          fill_value=0).reset_index()


kp3_pivot= pd.pivot_table(kp3_full,
                          index="ID_ruta",
                          columns="NOMOURUTKOMO",
                          values="KOLOM5",
                          aggfunc="sum",
                          fill_value=0).reset_index()

kp3_pivot_2= pd.pivot_table(kp3_full,
                          index="ID_ruta",
                          columns="NOMOURUTKOMO",
                          values="KOLOM6",
                          aggfunc="sum",
                          fill_value=0).reset_index()


cols_to_keep=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_ruta']
df_AMKP=df_kor_rt[cols_to_keep]

kp2_pivot.head()

NOMOURUTKOMO,ID_ruta,1,2,3,4,5,6,7,8,9,...,216,217,218,219,220,221,222,223,224,225
0,000401,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,15000.0,10000.0,0.0,126000.0,126000.0,0.0,0.0,0.0,0.0
1,0004010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,000402,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,000403,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,000404,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df_AMKP

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta
0,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,19,PEMATANG PAUH,2,00040,000400,1,1,DIKI FERNANDO,DIKI FERNANDO,000401
1,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,38,GEMURUH,2,00102,000700,4,1,JAMALUDIN,JAMALUDIN,001024
2,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,39,PEMATANG TEMBESU,2,00110,000400,1,1,A. RAFIK,A. RAFIK,001101
3,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50019,001900,5,1,NURASIAH,NURASIAH,500195
4,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50033,003300,3,1,SLAMET SUPRIANTO,SLAMET SUPRIANTO,500333
5,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50039,003901,1,1,EFRAN ZAMZAMI,EFRAN ZAMZAMI,500391
6,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710
7,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721
8,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722
9,7,TANJUNG JABUNG BARAT,20,PENGABUAN,18,PASAR SENIN,2,00993,000500,2,1,ARIF HARIYANTO,ARIF HARIYANTO,009932
10,7,TANJUNG JABUNG BARAT,21,SENYERANG,5,SENYERANG,2,01075,001100,4,1,MARMI,MARMI,010754
11,7,TANJUNG JABUNG BARAT,21,SENYERANG,5,SENYERANG,2,01075,001100,9,1,BAMBANG BASUKI RAHMAT,BAMBANG BASUKI RAHMAT,010759
12,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50048,000700,1,1,PARIADI,PARIADI,500481
13,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50054,001300,5,1,RASIDI,RASIDI,500545
14,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081
15,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082
16,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,3,1,ABDULLAH,ABDULLAH,501083
17,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,4,1,M. ANUARI,M. ANUARI,501084
18,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,5,1,JUMRI,JUMRI,501085
19,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,6,1,ABD. RAHMAN,ABD. RAHMAN,501086
20,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,7,1,SYAMSUDDIN,SYAMSUDDIN,501087
21,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,8,1,DARUSMAN,DARUSMAN,501088
22,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,9,1,SELAMAT HARITONANG,SELAMAT HARITONANG,501089
23,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,10,1,EKO NOVRIANSYAH PUTRA,EKO NOVRIANSYAH PUTRA,5010810
24,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50114,000801,5,1,RESTUONO,RESTUONO,501145
25,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,11,TUNGKAL I,2,01175,000900,2,1,JUMRI SARMAN,JUMRI SARMAN,011752
26,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,15,SUNGAI NIBUNG,1,50137,000100,2,1,M. SARNUBI,M. SARNUBI,501372
27,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,16,SRIWIJAYA,1,50163,001300,6,1,SYAPARDUDIN,SYAPARDUDIN,501636
28,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,16,SRIWIJAYA,1,50163,001300,9,1,MISRAN,MISRAN,501639
29,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50206,000702,8,1,MULYADI,MULYADI,502068
30,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50213,001301,2,1,RUSLI,RUSLI,502132
31,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50213,001301,8,1,DONI ADNAN,,502138
32,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,3,PEMBENGIS,2,01232,000100,1,1,ARNAIN,ARNAIN,012321
33,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,9,MEKAR TANJUNG,2,01297,000400,1,1,BEJO WIYONO,BEJO WIYONO,012971
34,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,9,MEKAR TANJUNG,2,01297,000400,5,1,BADRAN,BADRAN,012975
35,7,TANJUNG JABUNG BARAT,40,BETARA,16,SUNGAI TERAP,2,01512,001000,5,1,USNAINI,USNAINI,015125
36,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,3,BETARA KIRI,2,01551,000100,2,1,RIDWAN,RIDWAN,015512
37,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,3,BETARA KIRI,2,01551,000100,3,1,MUHAMMAD ALWI,MUHAMMAD ALWI,015513
38,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,3,BETARA KIRI,2,01551,000100,4,1,ASIAH,ASIAH,015514
39,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,7,TANJUNG PASIR,2,01601,001300,1,1,MASTANIAH,MASTANIAH,016011

### 02.1 Persiapan Dataset K dan KP

In [ ]:
#Dataset Anomali M dan KP 01
AMKP_01_1 = df_kor.groupby("ID_ruta").agg(
    M403_8=("R403", lambda x: (x==8).sum())
).reset_index()
AMKP_01 = pd.merge(
    AMKP_01_1,
    kp3_pivot[["ID_ruta", 304]],
    on="ID_ruta",
    how="left")
AMKP_01 = AMKP_01.rename(columns={304: "Gaji Pembantu (R304)"})
df_AMKP_01=pd.merge(df_AMKP,AMKP_01,on="ID_ruta",how="left")
df_AMKP_01

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,M403_8,Gaji Pembantu (R304)
0,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,19,PEMATANG PAUH,2,00040,000400,1,1,DIKI FERNANDO,DIKI FERNANDO,000401,0,0.0
1,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,38,GEMURUH,2,00102,000700,4,1,JAMALUDIN,JAMALUDIN,001024,0,0.0
2,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,39,PEMATANG TEMBESU,2,00110,000400,1,1,A. RAFIK,A. RAFIK,001101,0,0.0
3,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50019,001900,5,1,NURASIAH,NURASIAH,500195,0,0.0
4,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50033,003300,3,1,SLAMET SUPRIANTO,SLAMET SUPRIANTO,500333,0,0.0
5,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50039,003901,1,1,EFRAN ZAMZAMI,EFRAN ZAMZAMI,500391,0,0.0
6,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN
7,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,NaN
8,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,0,NaN
9,7,TANJUNG JABUNG BARAT,20,PENGABUAN,18,PASAR SENIN,2,00993,000500,2,1,ARIF HARIYANTO,ARIF HARIYANTO,009932,0,NaN
10,7,TANJUNG JABUNG BARAT,21,SENYERANG,5,SENYERANG,2,01075,001100,4,1,MARMI,MARMI,010754,0,NaN
11,7,TANJUNG JABUNG BARAT,21,SENYERANG,5,SENYERANG,2,01075,001100,9,1,BAMBANG BASUKI RAHMAT,BAMBANG BASUKI RAHMAT,010759,0,NaN
12,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50048,000700,1,1,PARIADI,PARIADI,500481,0,0.0
13,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50054,001300,5,1,RASIDI,RASIDI,500545,0,0.0
14,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,0,0.0
15,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0.0
16,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,3,1,ABDULLAH,ABDULLAH,501083,0,0.0
17,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,4,1,M. ANUARI,M. ANUARI,501084,0,0.0
18,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,5,1,JUMRI,JUMRI,501085,0,0.0
19,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,6,1,ABD. RAHMAN,ABD. RAHMAN,501086,0,0.0
20,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,7,1,SYAMSUDDIN,SYAMSUDDIN,501087,0,0.0
21,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,8,1,DARUSMAN,DARUSMAN,501088,0,0.0
22,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,9,1,SELAMAT HARITONANG,SELAMAT HARITONANG,501089,0,0.0
23,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,10,1,EKO NOVRIANSYAH PUTRA,EKO NOVRIANSYAH PUTRA,5010810,0,0.0
24,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50114,000801,5,1,RESTUONO,RESTUONO,501145,0,0.0
25,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,11,TUNGKAL I,2,01175,000900,2,1,JUMRI SARMAN,JUMRI SARMAN,011752,0,NaN
26,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,15,SUNGAI NIBUNG,1,50137,000100,2,1,M. SARNUBI,M. SARNUBI,501372,0,0.0
27,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,16,SRIWIJAYA,1,50163,001300,6,1,SYAPARDUDIN,SYAPARDUDIN,501636,0,0.0
28,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,16,SRIWIJAYA,1,50163,001300,9,1,MISRAN,MISRAN,501639,0,0.0
29,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50206,000702,8,1,MULYADI,MULYADI,502068,0,0.0
30,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50213,001301,2,1,RUSLI,RUSLI,502132,0,0.0
31,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50213,001301,8,1,DONI ADNAN,,502138,0,0.0
32,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,3,PEMBENGIS,2,01232,000100,1,1,ARNAIN,ARNAIN,012321,0,NaN
33,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,9,MEKAR TANJUNG,2,01297,000400,1,1,BEJO WIYONO,BEJO WIYONO,012971,0,NaN
34,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,9,MEKAR TANJUNG,2,01297,000400,5,1,BADRAN,BADRAN,012975,0,NaN
35,7,TANJUNG JABUNG BARAT,40,BETARA,16,SUNGAI TERAP,2,01512,001000,5,1,USNAINI,USNAINI,015125,0,NaN
36,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,3,BETARA KIRI,2,01551,000100,2,1,RIDWAN,RIDWAN,015512,0,NaN
37,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,3,BETARA KIRI,2,01551,000100,3,1,MUHAMMAD ALWI,MUHAMMAD ALWI,015513,0,NaN
38,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,3,BETARA KIRI,2,01551,000100,4,1,ASIAH,ASIAH,015514,0,NaN
39,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,7,TANJUNG PASIR,2,01601,001300,1,1,MASTANIAH,MASTANIAH,016011,0,NaN

In [ ]:
#Dataset Anomali M dan KP 02.1
AMKP_02_1_1 = df_kor.groupby("ID_ruta").agg(
    R407_1=("R407", lambda x: (x<1).sum())
).reset_index()
AMKP_02_1 = pd.merge(
    AMKP_02_1_1,
    kp3_pivot_2[["ID_ruta", 287, 288]],
    on="ID_ruta",
    how="left")
AMKP_02_1 = AMKP_02_1.rename(columns={287: "Periksa Kehamilan (R287)",288: "Imunisasi (R288)"})
df_AMKP_02_1=pd.merge(df_AMKP,AMKP_02_1,on="ID_ruta",how="left")
df_AMKP_02_1.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,R407_1,Periksa Kehamilan (R287),Imunisasi (R288)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,NaN,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,0,NaN,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,0,0.0,0.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0.0,0.0

In [ ]:
#Dataset Anomali M dan KP 02.2
AMKP_02_2_1 = df_kor.groupby("ID_ruta").agg(
    R407_1=("R407", lambda x: (x<=1).sum())
).reset_index()
AMKP_02_2 = pd.merge(
    AMKP_02_2_1,
    kp3_pivot[["ID_ruta", 275]],
    on="ID_ruta",
    how="left")
AMKP_02_2 = AMKP_02_2.rename(columns={275: "Biaya Untuk Pampers (R275)"})
df_AMKP_02_2=pd.merge(df_AMKP,AMKP_02_2,on="ID_ruta",how="left")
df_AMKP_02_2.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,M407_1,Biaya Untuk Pampers (R275)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,0,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,0,15000.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0.0

In [ ]:
#Dataset Anomali M dan KP 02.3
AMKP_02_3_1 = df_kor.groupby("ID_ruta").agg(
    R407_1=("R407", lambda x: (x<=1).sum())
).reset_index()
AMKP_02_3 = pd.merge(
    AMKP_02_3_1,
    kp1_pivot[["ID_ruta", 82]],
    on="ID_ruta",
    how="left")
AMKP_02_3 = AMKP_02_3.rename(columns={82: "Biaya Untuk Susu Bubuk Bayi (R82)"})
df_AMKP_02_3=pd.merge(df_AMKP,AMKP_02_3,on="ID_ruta",how="left")
df_AMKP_02_3.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,M407_1,Biaya Untuk Susu Bubuk Bayi (R82)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,0,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,0,0.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0.0

In [ ]:
#Dataset Anomali M dan KP 02.4
AMKP_02_4_1 = df_kor.groupby("ID_ruta").agg(
    R407_1=("R407", lambda x: (x<1).sum())
).reset_index()
AMKP_02_4 = pd.merge(
    AMKP_02_4_1,
    kp3_pivot_2[["ID_ruta", 276,277,278,279,280,281,282]],
    on="ID_ruta",
    how="left")
#AMKP_02_4 = AMKP_02_4.rename(columns={276: "Biaya Rumah Sakit Pemerintah (R276)",277: "Biaya Rumah Sakit Swasta (R277)",278: "Biaya Puskesmas-Pustu-Polindes-Posyandu (R278)",279: "Biaya Praktek Dokter-Klinik (R279)",280: "Biaya Praktek Petugas Kesehatan (R280)",281: "Biaya Praktek Pengobatan Tradisional (R281)",282: "Biaya Dukun Penolong Persalinan (R282)"})
df_AMKP_02_4=pd.merge(df_AMKP,AMKP_02_4,on="ID_ruta",how="left")
df_AMKP_02_4.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,...,NAMAKRT,ID_ruta,R407_1,276,277,278,279,280,281,282
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,...,AHMAD TAZLI,0063710,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,...,AHMAD ZULMAN,006721,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,...,NIDAR,006722,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,...,M. YASIR,501081,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,...,SUHAIMI,501082,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#Dataset Anomali M dan KP 03
f15=df_kor
f15["f_15"]=np.where((f15["R407"]>=15)&(f15["R405"]==2),"1","0")
AMKP_03_1 = f15.groupby("ID_ruta").agg(
    R407_f15_tahun_Keatas=("f_15", lambda x: (x=="1").sum())
).reset_index()
AMKP_03 = pd.merge(
    AMKP_03_1,
    kp3_pivot_2[["ID_ruta", 270]],
    on="ID_ruta",
    how="left")
AMKP_03 = AMKP_03.rename(columns={270: "Biaya Untuk Barang Kecantikan dan Pembalut (R270)"})
df_AMKP_03=pd.merge(df_AMKP,AMKP_03,on="ID_ruta",how="left")
df_AMKP_03.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,M407_f15_tahun_Keatas,Biaya Untuk Barang Kecantikan dan Pembalut (R270)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,1,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,1,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,1,310000.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,1,0.0

In [ ]:
#Dataset Anomali M dan KP 04
AMKP_04_1 = df_kor.groupby("ID_ruta").agg(
    M610_2=("R610", lambda x: (x==2).sum())
).reset_index()
AMKP_04 = pd.merge(
    AMKP_04_1,
    kp3_pivot_2[["ID_ruta", 292,293,294,295,296,297]],
    on="ID_ruta",
    how="left")
AMKP_04 = AMKP_04.rename(columns={292:"Uang Pangkal (R292)",293:"Uang Sekolah (R293)",294: "Iuran sekolah lainnya (R294)",295:"Buku pelajaran (R295)",296:"Alat-alat tulis (R296)",297:"Uang Bimbel (R297)"})
df_AMKP_04=pd.merge(df_AMKP,AMKP_04,on="ID_ruta",how="left")
df_AMKP_04.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,...,NAMAKRTDSR,NAMAKRT,ID_ruta,M610_2,Uang Pangkal (R292),Uang Sekolah (R293),Iuran sekolah lainnya (R294),Buku pelajaran (R295),Alat-alat tulis (R296),Uang Bimbel (R297)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,...,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN,NaN,NaN,NaN,NaN,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,...,AHMAD ZULMAN,AHMAD ZULMAN,006721,1,NaN,NaN,NaN,NaN,NaN,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,...,NIDAR,NIDAR,006722,0,NaN,NaN,NaN,NaN,NaN,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,...,M. YASIR,M. YASIR,501081,1,0.0,900000.0,0.0,150000.0,180000.0,0.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,...,SUHAIMI,SUHAIMI,501082,0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#Dataset Anomali M dan KP 04_1
AMKP_04_1_2 = df_kor.groupby("ID_ruta").agg(
    M610_2=("R610", lambda x: (x==2).sum())
).reset_index()
AMKP_042 = pd.merge(
    AMKP_04_1_2,
    df_kp10[["ID_ruta", "B5ER12K3"]],
    on="ID_ruta",
    how="left")
AMKP_042 = AMKP_042.rename(columns={"B5ER12K3":"Bantuan dari Pemerintah (BLOK_VE_R1B_KOL_3)"})
df_AMKP_042=pd.merge(df_AMKP,AMKP_042,on="ID_ruta",how="left")
df_AMKP_042.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,M610_2,Bantuan dari Pemerintah (BLOK_VE_R1B_KOL_3)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,1,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,0,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,1,900000.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,NaN

In [ ]:
#Dataset Anomali M dan KP 05
AMKP_05_1 = df_kor.groupby("ID_ruta").agg(
    R617_1_2=("R617", lambda x: (x<=2).sum())
).reset_index()
AMKP_05 = pd.merge(
    AMKP_05_1,
    df_kp10[["ID_ruta", "B5ER12K3"]],
    on="ID_ruta",
    how="left")
AMKP_05 = AMKP_05.rename(columns={"R617_1_2":"Jumlah Anak yang Pernah/Sedang Mendapat MBG (617<=2)","B5ER12K3":"Bantuan dari Pemerintah (BLOK_VE_R1B_KOL_3)"})
df_AMKP_05=pd.merge(df_AMKP,AMKP_05,on="ID_ruta",how="left")
df_AMKP_05.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,Jumlah Anak yang Pernah/Sedang Mendapat MBG (617<=2),Bantuan dari Pemerintah (BLOK_VE_R1B_KOL_3)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,0,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,0,900000.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,NaN

In [ ]:
#Dataset Anomali M dan KP 06
AMKP_06_1 = df_kor.groupby("ID_ruta").agg(
    R617_2=("R617", lambda x: (x==2).sum())
).reset_index()
AMKP_06 = pd.merge(
    AMKP_06_1,
    kp2_pivot[["ID_ruta", 196]],
    on="ID_ruta",
    how="left")
AMKP_06 = AMKP_06.rename(columns={"R617_2":"Jumlah Anak yang Sedang Mendapat MBG (617=2)",196:"Konsumsi Nasi Rames/Campur (R196)"})
df_AMKP_06=pd.merge(df_AMKP,AMKP_06,on="ID_ruta",how="left")
df_AMKP_06.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,Jumlah Anak yang Sedang Mendapat MBG (617=2),Konsumsi Nasi Rames/Campur (R196)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,0,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,0,105000.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0.0

In [ ]:
#Dataset Anomali M dan KP 06_2
AMKP_06_2 = df_kor.groupby("ID_ruta").agg(
    R617_2=("R617", lambda x: (x==2).sum())
).reset_index()
AMKP_06_2_1 = pd.merge(
    AMKP_06_2,
    kp1_pivot[["ID_ruta", 79, 129]],
    on="ID_ruta",
    how="left")
AMKP_06_2_1 = AMKP_06_2_1.rename(columns={79:"Konsumsi Susu Cair Pabrik (R79)",129:"Konsumsi Buah-Buahan (R129)"})
df_AMKP_06_2=pd.merge(df_AMKP,AMKP_06_2_1,on="ID_ruta",how="left")
df_AMKP_06_2.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,R617_2,Konsumsi Susu Cair Pabrik (R79),Konsumsi Buah-Buahan (R129)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,NaN,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,0,NaN,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,0,0.0,139000.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0.0,0.0

In [ ]:
#Dataset Anomali M dan KP 07
AMKP_07_1 = df_kor.groupby("ID_ruta").agg(
    R619_1=("R619", lambda x: (x==1).sum())
).reset_index()
AMKP_07 = pd.merge(
    AMKP_07_1,
    df_kp10[["ID_ruta", "B5ER12K2"]],
    on="ID_ruta",
    how="left")
AMKP_07 = AMKP_07.rename(columns={"B5ER12K2":"Bantuan dari Pemerintah (BLOK_VE_R1B_KOL_2)"})
df_AMKP_07=pd.merge(df_AMKP,AMKP_07,on="ID_ruta",how="left")
df_AMKP_07.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,R619_1,Bantuan dari Pemerintah (BLOK_VE_R1B_KOL_2)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,0,2400000.0
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,0,NaN
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,NaN

In [ ]:
#Dataset Anomali M dan KP 08
AMKP_08_1 = df_kor.groupby("ID_ruta").agg(
    R701_1=("R701", lambda x: (x==1).sum())
).reset_index()
AMKP_08 = pd.merge(
    AMKP_08_1,
    kp3_pivot_2[["ID_ruta", 305]],
    on="ID_ruta",
    how="left")
AMKP_08 = AMKP_08.rename(columns={305:"Pengeluaran Jasa Keuangan (R305)"})
df_AMKP_08=pd.merge(df_AMKP,AMKP_08,on="ID_ruta",how="left")
df_AMKP_08.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,R701_1,Pengeluaran Jasa Keuangan (R305)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,2,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,2,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,2,144000.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0.0

In [ ]:
#Dataset Anomali M dan KP 11
AMKP_11_1 = df_kor.groupby("ID_ruta").agg(
    R_802_1=("R802", lambda x: (x==1).sum())
).reset_index()

AMKP_11 = pd.merge(
    AMKP_11_1,
    kp3_pivot[["ID_ruta", 264]],
    on="ID_ruta",
    how="left")
AMKP_11 = AMKP_11.rename(columns={264: "Pulsa (R264)"})
df_AMKP_11=pd.merge(df_AMKP,AMKP_11,on="ID_ruta",how="left")
df_AMKP_11.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,R_802_1,Pulsa (R264)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,1,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,2,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,2,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,3,33000.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0.0

In [ ]:
#Dataset Anomali M dan KP 12
AMKP_12_1 = df_kor.groupby("ID_ruta").agg(
    R_804_1=("R804", lambda x: (x==1).sum())
).reset_index()

AMKP_12 = pd.merge(
    AMKP_12_1,
    kp3_pivot[["ID_ruta", 266]],
    on="ID_ruta",
    how="left")
AMKP_12 = AMKP_12.rename(columns={266: "Internet (R266)"})
df_AMKP_12=pd.merge(df_AMKP,AMKP_12,on="ID_ruta",how="left")
df_AMKP_12.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,R_804_1,Internet (R266)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,3,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,2,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,3,130000.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0.0

In [ ]:
#Dataset Anomali M dan KP 13
AMKP_13_1 = df_kor.groupby("ID_ruta").agg(
    R_901_1=("R901", lambda x: (x==1).sum())
).reset_index()

AMKP_13 = pd.merge(
    AMKP_13_1,
    kp3_pivot_2[["ID_ruta", 298, 299, 300]],
    on="ID_ruta",
    how="left")
AMKP_13 = AMKP_13.rename(columns={298: "Transportasi Darat (R298)", 299: "Transportasi Udara (R299)", 300: "Transportasi Laut (300)"})
df_AMKP_13=pd.merge(df_AMKP,AMKP_13,on="ID_ruta",how="left")
df_AMKP_13.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,R_901_1,Transportasi Darat (R298),Transportasi Udara (R299),Transportasi Laut (300)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN,NaN,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,NaN,NaN,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,0,NaN,NaN,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,0,0.0,0.0,0.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0.0,0.0,0.0

In [ ]:
#Dataset Anomali M dan KP 14
AMKP_14_1 = df_kor.groupby("ID_ruta").agg(
    R_1101_A=("R1101_A", lambda x: (x=="A").sum()),
    R_1101_B=("R1101_B", lambda x: (x=="B").sum()),
    R_1101_C=("R1101_C", lambda x: (x=="C").sum()),
    R_1101_D=("R1101_D", lambda x: (x=="D").sum()),
).reset_index()

AMKP_14 = pd.merge(
    AMKP_14_1,
    kp3_pivot_2[["ID_ruta", 338]],
    on="ID_ruta",
    how="left")
AMKP_14 = AMKP_14.rename(columns={338: "Asuransi Kesehatan (R338)"})
df_AMKP_14=pd.merge(df_AMKP,AMKP_14,on="ID_ruta",how="left")
df_AMKP_14.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,R_1101_A,R_1101_B,R_1101_C,R_1101_D,Asuransi Kesehatan (R338)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,0,0,0,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,3,0,0,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,0,0,0,0,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,4,0,0,0,1680000.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0,0,0,0.0

In [ ]:
#Dataset Anomali M dan KP 15
AMKP_15_1 = df_kor.groupby("ID_ruta").agg(
    R_1101_A=("R1101_A", lambda x: (x=="A").sum())
).reset_index()

AMKP_15 = pd.merge(
    AMKP_15_1,
    df_kp10[["ID_ruta", "B5ER12K3"]],
    on="ID_ruta",
    how="left")
AMKP_15 = AMKP_15.rename(columns={"B5ER12K3": "Penerima Bantuan Pemerintah(B5ER12K3)"})
df_AMKP_15=pd.merge(df_AMKP,AMKP_15,on="ID_ruta",how="left")
df_AMKP_15.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,R_1101_A,Penerima Bantuan Pemerintah(B5ER12K3)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,0,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,4,900000.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,NaN

In [ ]:
#Dataset Anomali M dan KP 16
AMKP_16_1 = df_kor.groupby("ID_ruta").agg(
    R_1104_A=("R1104", lambda x: (x==1).sum())
).reset_index()

AMKP_16 = pd.merge(
    AMKP_16_1,
    kp3_pivot_2[["ID_ruta", 284, 285]],
    on="ID_ruta",
    how="left")
AMKP_16 = AMKP_16.rename(columns={284: "Obat Modern (R284)", 285: "Obat Tradisional (R285)"})
df_AMKP_16=pd.merge(df_AMKP,AMKP_16,on="ID_ruta",how="left")
df_AMKP_16.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,R_1104_A,Obat Modern (R284),Obat Tradisional (R285)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,NaN,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,NaN,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,0,NaN,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,0,180000.0,90000.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0.0,0.0

In [ ]:
#Dataset Anomali M dan KP 17
AMKP_17_1 = df_kor.groupby("ID_ruta").agg(
    R_1105=("R1105", lambda x: (x==1).sum())
).reset_index()

AMKP_17 = pd.merge(
    AMKP_17_1,
    kp3_pivot_2[["ID_ruta", 276, 277, 278, 279, 280, 281, 282]],
    on="ID_ruta",
    how="left")
#AMKP_17 = AMKP_17.rename(columns={
#    276: "Rawat Jalan (Pemerintah) (R276a)",
#    277: "Rawat Jalan (Swasta) (R277a)",
#    278: "Rawat Jalan (Puskesmas) (R278a)",
#    279: "Praktik Dokter/Poliklinik (R279)",
#    280: "Praktik Petugas Kesehatan (R280)",
#    281: "Praktik Pengobatan Tradisional (R281)",
#    282: "Dukun Penolong Persalinan (R282)"
#    })
df_AMKP_17=pd.merge(df_AMKP,AMKP_17,on="ID_ruta",how="left")
df_AMKP_17.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,...,NAMAKRT,ID_ruta,R_1105,276,277,278,279,280,281,282
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,...,AHMAD TAZLI,0063710,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,...,AHMAD ZULMAN,006721,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,...,NIDAR,006722,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,...,M. YASIR,501081,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,...,SUHAIMI,501082,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#Dataset Anomali M dan KP 18
AMKP_18_1 = df_kor.groupby("ID_ruta").agg(
    R_1201=("R1201", lambda x: (x==1).sum())
).reset_index()

AMKP_18 = pd.merge(
    AMKP_18_1,
    kp3_pivot_2[["ID_ruta", 276, 277, 278, 279, 280, 281, 282]],
    on="ID_ruta",
    how="left")
#AMKP_18 = AMKP_18.rename(columns={
#    276: "Rawat Inap (Pemerintah) (R276b)",
#    277: "Rawat Inap (Swasta) (R277b)",
#    278: "Rawat Inap (Puskesmas) (R278b)",
#    279: "Praktik Dokter/Poliklinik (R279)",
#    280: "Praktik Petugas Kesehatan (R280)",
#    281: "Praktik Pengobatan Tradisional (R281)",
#    282: "Dukun Penolong Persalinan (R282)"
#    })
df_AMKP_18=pd.merge(df_AMKP,AMKP_18,on="ID_ruta",how="left")
df_AMKP_18.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,...,NAMAKRT,ID_ruta,R_1201,276,277,278,279,280,281,282
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,...,AHMAD TAZLI,0063710,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,...,AHMAD ZULMAN,006721,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,...,NIDAR,006722,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,...,M. YASIR,501081,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,...,SUHAIMI,501082,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#Dataset Anomali M dan KP 19.1
AMKP_19 = df_kor.groupby("ID_ruta").agg(
    R_1206=("R1206", lambda x: (x == 1).sum()),
    R_1207=("R1207", lambda x: (x == 1).sum())
).reset_index()

AMKP_19_1 = pd.merge(
    AMKP_19,
    kp2_pivot[["ID_ruta", 220]],
    on="ID_ruta",
    how="left"
)

AMKP_19_1 = AMKP_19_1.rename(columns={
    220: "Pengeluaran Rokok (R220)"
})

df_AMKP_19_1 = pd.merge(df_AMKP, AMKP_19_1, on="ID_ruta", how="left")
df_AMKP_19_1.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,R_1206,R_1207,Pengeluaran Rokok (R220)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,2,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,0,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,2,1,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,0,2,84000.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0,0.0

In [ ]:
#Dataset Anomali M dan KP 19.2
AMKP_19_2 = pd.merge(
    AMKP_19,
    kp3_pivot_2[["ID_ruta", 234]],
    on="ID_ruta",
    how="left"
)

AMKP_19_2 = AMKP_19_2.rename(columns={
    234: "Pengeluaran Korek Api (R234)"
})

df_AMKP_19_2 = pd.merge(df_AMKP, AMKP_19_2, on="ID_ruta", how="left")
df_AMKP_19_2.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,R_1206,R_1207,Pengeluaran Korek Api (R234)
0,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,0063710,0,2,NaN
1,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,1,1,AHMAD ZULMAN,AHMAD ZULMAN,006721,0,0,NaN
2,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,006722,2,1,NaN
3,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,501081,0,2,0.0
4,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,501082,0,0,0.0

In [ ]:
#Dataset Anomali M dan KP 20.1
AMKP_20 = df_kor_rt.groupby("ID_ruta").agg(
    R_1602=("R1602", lambda x: (x==1).sum())
).reset_index()

AMKP_20_1 = pd.merge(
    AMKP_20,
    kp3_pivot_2[["ID_ruta", 335]],
    on="ID_ruta",
    how="left"
)

AMKP_20_1 = AMKP_20_1.rename(columns={
    335: "Pengeluaran PBB (R335)"
})

df_AMKP_20_1 = pd.merge(df_AMKP, AMKP_20_1, on="ID_ruta", how="left")
df_AMKP_20_1.head()

In [ ]:
#Dataset Anomali M dan KP 20.2
AMKP_20_2 = pd.merge(
    AMKP_20,
    df_kp12[["ID_ruta", "B7R5K2"]],
    on="ID_ruta",
    how="left"
)

AMKP_20_2= AMKP_20_2.rename(columns={
     "B7R5K2": "Penerimaan Meminjam Uang (B7R5K2)"
})

df_AMKP_20_2 = pd.merge(df_AMKP, AMKP_20_2, on="ID_ruta", how="left")
df_AMKP_20_2.head()

In [ ]:
#Dataset Anomali M dan KP 06
AMKP_06_1 = df_kor.groupby("ID_ruta").agg(
    RawatJalanInap_M604_1=("M604", lambda x: (x==1).sum())
).reset_index()

AMKP_06 = pd.merge(
    AMKP_06_1,
    kp3_pivot_2[["ID_ruta", 276,277,278,279,280,281,282]],
    on="ID_ruta",
    how="left")
AMKP_06 = AMKP_06.rename(columns={276: "Rumah sakit pemerintah (R276)",277: "Rumah sakit Swasta(R277)",278: "Puskesmas-Pustu-polindes-posyandu(R278)",279: "Praktik Dokter-Poliklinik (R279)",280: "Praktik Petugas kesehatan(R280)",281: "Pengobatan Tradisional(R281)",282: "Dukun bersalin(R282)"})
df_AMKP_06=pd.merge(df_AMKP,AMKP_06,on="ID_ruta",how="left")
df_AMKP_06.head()

In [ ]:
#Dataset Anomali M dan KP 08
AMKP_08_1 = df_kor.groupby("ID_ruta").agg(
    AngkutanUmum_M608=("M608", lambda x: (x==3).sum())
).reset_index()

AMKP_08 = pd.merge(
    AMKP_08_1,
    kp3_pivot_2[["ID_ruta", 298,299,300]],
    on="ID_ruta",
    how="left")
AMKP_08 = AMKP_08.rename(columns={284: "Obat modern(R284)",285: "Obat tradisional-jamu(R285)"})
df_AMKP_08=pd.merge(df_AMKP,AMKP_08,on="ID_ruta",how="left")
df_AMKP_08.head()

In [ ]:
#Dataset Anomali M dan KP 09
AMKP_09_1 = df_kor.groupby("ID_ruta").agg(
    M702_1=("M702", lambda x: (x==1).sum())
).reset_index()
AMKP_09 = pd.merge(
    AMKP_09_1,
    kp1_pivot[["ID_ruta", 1,8]],
    on="ID_ruta",
    how="left")
AMKP_09 = AMKP_09.rename(columns={1: "Padi-Padian(1)",8:"Umbi-Umbian(8)"})
df_AMKP_09=pd.merge(df_AMKP,AMKP_09,on="ID_ruta",how="left")
df_AMKP_09.head()

In [ ]:
#Dataset Anomali M dan KP 10
AMKP_10_1 = df_kor.groupby("ID_ruta").agg(
    M704_1=("M704", lambda x: (x==1).sum())
).reset_index()

AMKP_10 = pd.merge(
    AMKP_10_1,
    kp1_pivot[["ID_ruta", 121]],
    on="ID_ruta",
    how="left")
AMKP_10 = AMKP_10.rename(columns={121: "Kacang-Kacangan(R121)"})
df_AMKP_10=pd.merge(df_AMKP,AMKP_10,on="ID_ruta",how="left")
df_AMKP_10.head()

In [ ]:
#Dataset Anomali M dan KP 11
AMKP_11_1 = df_kor.groupby("ID_ruta").agg(
    M705_1=("M705", lambda x: (x==1).sum())
).reset_index()

AMKP_11 = pd.merge(
    AMKP_11_1,
    kp1_pivot[["ID_ruta", 16,61,74]],
    on="ID_ruta",
    how="left")
AMKP_11 = AMKP_11.rename(columns={16: "Ikan-Udang-Cumi-Kerang(R16)",61: "Daging(R61)",74: "Telur dan Susu (R74)"})
df_AMKP_11=pd.merge(df_AMKP,AMKP_11,on="ID_ruta",how="left")
df_AMKP_11.head()

In [ ]:
#Dataset Anomali M dan KP 12
AMKP_12_1 = df_kor.groupby("ID_ruta").agg(
    Internet_M1014=("M1014", lambda x: (x==1).sum())
).reset_index()

AMKP_12 = pd.merge(
    AMKP_12_1,
    kp3_pivot[["ID_ruta", 266]],
    on="ID_ruta",
    how="left")
AMKP_12 = AMKP_12.rename(columns={266: "Biaya Internet(R266)"})
df_AMKP_12=pd.merge(df_AMKP,AMKP_12,on="ID_ruta",how="left")
df_AMKP_12.head()

In [ ]:
#Dataset Anomali M dan KP 13
AMKP_13_1 = df_kor.groupby("ID_ruta").agg(
    Hamil_M1012=("M1102", lambda x: (x==1).sum())
).reset_index()

AMKP_13 = pd.merge(
    AMKP_13_1,
    kp3_pivot_2[["ID_ruta", 287]],
    on="ID_ruta",
    how="left")
AMKP_13 = AMKP_13.rename(columns={287: "Biaya Periksa Kehamilan(R287)"})
df_AMKP_13=pd.merge(df_AMKP,AMKP_13,on="ID_ruta",how="left")
df_AMKP_13.head()

In [ ]:
#Dataset Anomali M dan KP 14
AMKP_14_1 = df_kor.groupby("ID_ruta").agg(
    M1117A=("M1117A", lambda x: (x=="A").sum()),
    M1117B=("M1117B", lambda x: (x=="B").sum()),
    M1117C=("M1117C", lambda x: (x=="C").sum())
).reset_index()
AMKP_14 = pd.merge(
    AMKP_14_1,
    df_kp10[["ID_ruta", "B5ER12K3"]],
    on="ID_ruta",
    how="left")
AMKP_14 = AMKP_14.rename(columns={"B5ER12K3":"Bantuan dari Pemerintah (BLOK_VE_R1B_KOL_3)"})
df_AMKP_14=pd.merge(df_AMKP,AMKP_14,on="ID_ruta",how="left")
df_AMKP_14.head()

In [ ]:
#Dataset Anomali M dan KP 15
AMKP_15_1 = df_kor.groupby("ID_ruta").agg(
    M1117D=("M1117D", lambda x: (x=="D").sum()),
    M1117E=("M1117E", lambda x: (x=="E").sum())
    ).reset_index()
AMKP_15 = pd.merge(
    AMKP_15_1,
    df_kp10[["ID_ruta", "B5ER2K2","B5ER2K3","B5ER4K2","B5ER4K3"]],
    on="ID_ruta",
    how="left")
AMKP_15 = AMKP_15.rename(columns={"B5ER2K2":"Bantuan uang dari Badan Usaha (Blok 5E Rincian 2 Kol 2)","B5ER2K3":"Bantuan Barang/jasa dari Badan Usaha (Blok 5E Rincian 2 Kol 3)","B5ER4K2":"Bantuan uang dari Lembaga Nirlaba (Blok 5E Rincian 4 Kol 2)","B5ER4K3":"Bantuan Barang/jasa dari Lembaga Nirlaba (Blok 5E Rincian 4 Kol 3)"})
df_AMKP_15=pd.merge(df_AMKP,AMKP_15,on="ID_ruta",how="left")
df_AMKP_15.head()

In [ ]:
#Dataset Anomali M dan KP 16
AMKP_16_1 = df_kor.groupby("ID_ruta").agg(
    UangPendaftaran_1118a=("M1118A", lambda x: (x>0).sum())
).reset_index()

AMKP_16 = pd.merge(
    AMKP_16_1,
    kp3_pivot_2[["ID_ruta", 292]],
    on="ID_ruta",
    how="left")
AMKP_16 = AMKP_16.rename(columns={292: "Biaya Sumbangan Sekolah(R292)"})
df_AMKP_16=pd.merge(df_AMKP,AMKP_16,on="ID_ruta",how="left")
df_AMKP_16.head()

In [ ]:
#Dataset Anomali M dan KP 17
AMKP_17_1 = df_kor.groupby("ID_ruta")[["M1118B","M1118C"]].sum().reset_index()

AMKP_17 = pd.merge(
    AMKP_17_1,
    kp3_pivot_2[["ID_ruta", 293]],
    on="ID_ruta",
    how="left")
AMKP_17 = AMKP_17.rename(columns={293: "Biaya uang sekolah dan Komite (R293)"})
df_AMKP_17=pd.merge(df_AMKP,AMKP_17,on="ID_ruta",how="left")
df_AMKP_17.head()

In [ ]:
#Dataset Anomali M dan KP 18
AMKP_18_1 = df_kor.groupby("ID_ruta")["M1118E"].sum().reset_index()

AMKP_18 = pd.merge(
    AMKP_18_1,
    kp3_pivot_2[["ID_ruta", 295]],
    on="ID_ruta",
    how="left")
AMKP_18 = AMKP_18.rename(columns={295: "Pengeluaran Buku Pelajaran (R295)"})
df_AMKP_18=pd.merge(df_AMKP,AMKP_18,on="ID_ruta",how="left")
df_AMKP_18.head()

In [ ]:
#Dataset Anomali M dan KP 19
AMKP_19_1 = df_kor.groupby("ID_ruta")["M1118D"].sum().reset_index()

AMKP_19 = pd.merge(
    AMKP_19_1,
    kp3_pivot_2[["ID_ruta", 310,313,314,315]],
    on="ID_ruta",
    how="left")
AMKP_19 = AMKP_19.rename(columns={295: "Pengeluaran Buku Pelajaran (R295)"})
df_AMKP_19=pd.merge(df_AMKP,AMKP_19,on="ID_ruta",how="left")
df_AMKP_19.head()

In [ ]:
#Dataset Anomali M dan KP 20
AMKP_20_1 = df_kor.groupby("ID_ruta")[["M1118G","M1118H","M1118J","M1118L","M1118M"]].sum().reset_index()

AMKP_20 = pd.merge(
    AMKP_20_1,
    kp3_pivot_2[["ID_ruta", 294]],
    on="ID_ruta",
    how="left")
AMKP_20 = AMKP_20.rename(columns={294: "Biaya uang iuran sekolah lainnya (R294)"})
df_AMKP_20=pd.merge(df_AMKP,AMKP_20,on="ID_ruta",how="left")
df_AMKP_20.head()

In [ ]:
#Dataset Anomali M dan KP 21
AMKP_21_1 = df_kor.groupby("ID_ruta")["M1118I"].sum().reset_index()
AMKP_21= pd.merge(
    AMKP_21_1,
    kp3_pivot_2[["ID_ruta",297]],
    on="ID_ruta",
    how="left")
AMKP_21 = AMKP_21.rename(columns={297: "Pengeluaran Untuk Bimbel (R297)"})
df_AMKP_21=pd.merge(df_AMKP,AMKP_21,on="ID_ruta",how="left")
df_AMKP_21.head()

In [ ]:
#Dataset Anomali M dan KP 22
AMKP_22_1 = df_kor.groupby("ID_ruta").agg(
    M_1208_1=("M1208", lambda x: (x==1).sum()),
    M_1208_3=("M1208", lambda x: (x==3).sum()),
    M_1209_1=("M1209", lambda x: (x==1).sum()),
    M_1209_3=("M1209", lambda x: (x==3).sum()),
).reset_index()

AMKP_22= pd.merge(
    AMKP_22_1,
    kp3_pivot_2[["ID_ruta",303]],
    on="ID_ruta",
    how="left")
AMKP_22 = AMKP_22.rename(columns={303: "Pengeluaran Untuk Hiburan(R303)"})
df_AMKP_22=pd.merge(df_AMKP,AMKP_22,on="ID_ruta",how="left")
df_AMKP_22.head()

In [ ]:
#Dataset Anomali M dan KP 23
AMKP_23_1 = df_kor.groupby("ID_ruta").agg(
    M_1312_1=("M1312", lambda x: (x==1).sum())
).reset_index()

AMKP_23= pd.merge(
    AMKP_23_1,
    df_kp10[["ID_ruta", "B5ER4K4"]],
    on="ID_ruta",
    how="left")
AMKP_23 = AMKP_23.rename(columns={"B5ER4K4": "Transfer untuk lembaga Nirlaba (Blok VE Rincian 4 Kolom 4) "})
df_AMKP_23=pd.merge(df_AMKP,AMKP_23,on="ID_ruta",how="left")
df_AMKP_23.head()

In [ ]:
#Dataset Anomali M dan KP 24_1
AMKP_24_1 = df_kor.groupby("ID_ruta").agg(
    RumahMilikSendiri_1501=("M1501", lambda x: (x==1).sum())
).reset_index()

AMKP_24= pd.merge(
    AMKP_24_1,
    kp3_pivot_2[["ID_ruta",335]],
    on="ID_ruta",
    how="left")
AMKP_24 = AMKP_24.rename(columns={335: "Pengeluaran Untuk PBB (R335)"})
df_AMKP_24=pd.merge(df_AMKP,AMKP_24,on="ID_ruta",how="left")
df_AMKP_24.head()

In [ ]:
#Dataset Anomali M dan KP 25
AMKP_25_1 = df_kor.groupby("ID_ruta").agg(
    ListrikPLN_1504=("M1504", lambda x: (x<=2).sum())
).reset_index()

AMKP_25= pd.merge(
    AMKP_25_1,
    kp3_pivot[["ID_ruta",234]],
    on="ID_ruta",
    how="left")
AMKP_25 = AMKP_25.rename(columns={234: "Pengeluaran Untuk Listrik(R234)"})
df_AMKP_25=pd.merge(df_AMKP,AMKP_25,on="ID_ruta",how="left")
df_AMKP_25.head()

In [ ]:
#Dataset Anomali M dan KP 26
AMKP_26_1 = df_kor.groupby("ID_ruta").agg(
    M_1701_1=("M1701", lambda x: (x==1).sum())
).reset_index()

AMKP_26= pd.merge(
    AMKP_26_1,
    df_kp10[["ID_ruta", "B5ER12K2"]],
    on="ID_ruta",
    how="left")
AMKP_26 = AMKP_26.rename(columns={"B5ER12K2": "Transfer bantuan dari pemerintah (Blok VE Rincian 1.b Kolom 2) "})
df_AMKP_26=pd.merge(df_AMKP,AMKP_26,on="ID_ruta",how="left")
df_AMKP_26.head()

In [ ]:
#Dataset Anomali M dan KP 27
AMKP_27_1 = df_kor.groupby("ID_ruta").agg(
    M_1703_1=("M1703", lambda x: (x==1).sum())
).reset_index()

AMKP_27= pd.merge(
    AMKP_27_1,
    df_kp10[["ID_ruta", "B5ER12K3"]],
    on="ID_ruta",
    how="left")
AMKP_27 = AMKP_27.rename(columns={"B5ER12K3": "Transfer bantuan dari pemerintah dalam bentuk barang jasa (Blok VE Rincian 1.b Kolom 3) "})
df_AMKP_27=pd.merge(df_AMKP,AMKP_27,on="ID_ruta",how="left")
df_AMKP_27.head()

In [ ]:
#Dataset Anomali M dan KP 28
AMKP_28_1 = df_kor.groupby("ID_ruta").agg(
    M_1704_1=("M1704", lambda x: (x==1).sum())
).reset_index()

AMKP_28= pd.merge(
    AMKP_28_1,
    df_kp10[["ID_ruta", "B5ER12K2","B5ER12K3"]],
    on="ID_ruta",
    how="left")
AMKP_28 = AMKP_28.rename(columns={"B5ER12K2": "Transfer bantuan dari pemerintah dalam bentuk uang (Blok VE Rincian 1.b Kolom 2)" ,"B5ER12K3": "Transfer bantuan dari pemerintah dalam bentuk barang jasa (Blok VE Rincian 1.b Kolom 3) "})
df_AMKP_28=pd.merge(df_AMKP,AMKP_28,on="ID_ruta",how="left")
df_AMKP_28.head()

# **02 ANOMALI VSEN25.K dan Anomali VSEN25.KP**

## Anomali VSEN25_Individu

In [ ]:
#Anomali M1
cols_to_keep=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','R401','R402','ID_art','R403','R407']
df_M1=df_kor[cols_to_keep]
df_M1["M1"]=np.where((df_M1["R403"]==1) & (df_M1["R407"]<20),"1","0")
df_M1["Keterangan"]=np.where(df_M1["M1"]=="1","KRT berumur dibawah 20 tahun (R407 < 20 tahun)","")
df_anomali_vsenM_01=df_M1[df_M1["M1"]=="1"]
df_anomali_vsenM_01.head()
#df_anomali_vsenM_01.to_excel("df_anomali_vsen_M_01.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
#df_anomali_vsenM_01.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/01 KRT berumur dibawah 20 tahun.xlsx', index=False)

/tmp/ipython-input-3820787714.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M1["M1"]=np.where((df_M1["R403"]==1) & (df_M1["R407"]<20),"1","0")
/tmp/ipython-input-3820787714.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M1["Keterangan"]=np.where(df_M1["M1"]=="1","KRT berumur dibawah 20 tahun (R407 < 20 tahun)","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, R401, R402, ID_art, R403, R407, M1, Keterangan]
Index: []

In [ ]:
#Anomali M2
cols_to_keep2=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','R401','R402','ID_art','R403','R404','R407']
df_M2=df_kor[cols_to_keep2]
df_M2["M2"]=np.where((df_M2["R404"]>1) & (df_M2["R407"]<20),"1","0")
df_M2["Keterangan"]=np.where(df_M2["M2"]=="1","Penduduk berstatus pernah kawin usia < 20 (R404>1 & R407<20)","")
df_anomali_vsenM_02=df_M2[df_M2["M2"]=="1"]
df_anomali_vsenM_02.head()
#df_anomali_vsenM_02.to_excel("df_anomali_vsen_M_02.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
#df_anomali_vsenM_02.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/02 Penduduk berstatus pernah kawin usia dibawah 20 tahun.xlsx', index=False)

/tmp/ipython-input-1744029680.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M2["M2"]=np.where((df_M2["R404"]>1) & (df_M2["R407"]<20),"1","0")
/tmp/ipython-input-1744029680.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M2["Keterangan"]=np.where(df_M2["M2"]=="1","Penduduk berstatus pernah kawin usia < 20 (R404>1 & R407<20)","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, R401, R402, ID_art, R403, R404, R407, M2, Keterangan]
Index: []

[0 rows x 21 columns]

In [ ]:
#Anomali M3
cols_to_keep3=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','R401','ID_art','R402','R407','R505']
df_M3=df_kor[cols_to_keep3]
df_M3["M3"]=np.where((df_M3["R505"]==5) & (df_M3["R407"]<18),"1","0")
df_M3["Keterangan"]=np.where(df_M3["M3"]=="1","Penduduk usia 18 tahun ke bawah tidak memiliki NIK (R501=5 & R407<18)","")
df_anomali_vsenM_03=df_M3[df_M3["M3"]=="1"]
df_anomali_vsenM_03.head()
#df_anomali_vsenM_03.to_excel("df_anomali_vsen_M_03.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
#df_anomali_vsenM_03.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/03 Penduduk usia 18 tahun ke bawah tidak memiliki NIK.xlsx', index=False)

/tmp/ipython-input-2364686132.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M3["M3"]=np.where((df_M3["R505"]==5) & (df_M3["R407"]<18),"1","0")
/tmp/ipython-input-2364686132.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M3["Keterangan"]=np.where(df_M3["M3"]=="1","Penduduk usia 18 tahun ke bawah tidak memiliki NIK (R501=5 & R407<18)","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, R401, ID_art, R402, R407, R505, M3, Keterangan]
Index: []

In [ ]:
#Anomali M4
cols_to_keep4=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','R401','R402','ID_art','R407','R509']
df_M4=df_kor[cols_to_keep4]
df_M4["M4"]=np.where((df_M4["R509"]==5) & (df_M4["R407"]<=18),"1","0")
df_M4["Keterangan"]=np.where(df_M4["M4"]=="1","Penduduk usia diatas 18 tahun kebawah tetapi tidak memiliki NIK (R509=5 & R407<=18)","")
df_anomali_vsenM_04=df_M4[df_M4["M4"]=="1"]
df_anomali_vsenM_04.head()

/tmp/ipython-input-434750011.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M4["M4"]=np.where((df_M4["R509"]==5) & (df_M4["R407"]<=18),"1","0")
/tmp/ipython-input-434750011.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M4["Keterangan"]=np.where(df_M4["M4"]=="1","Penduduk usia diatas 18 tahun kebawah tetapi tidak memiliki NIK (R509=5 & R407<=18)","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, R401, R402, ID_art, R407, R509, M4, Keterangan]
Index: []

In [354]:
df_anomali_AMKP_16

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, R_1104_A, Obat Modern (R284), Obat Tradisional (R285), AMKP16, Keterangan]
Index: []

In [ ]:
#Anomali M5
cols_to_keep5=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','R401','R402','ID_art','R407','R607_A','R607_B']
df_M5=df_kor[cols_to_keep5]
df_M5["M5"]=np.where(((df_M5["R607_A"]=="A")|(df_M5["R607_B"]=="B")) & (df_M5["R407"]<=10),"1","0")
df_M5["Keterangan"]=np.where(df_M5["M5"]=="1","Penduduk usia 10 tahun kebawah yang mengikuti Kursus. Perlu diperiksa ulang Kursus apa yang diikuti","")
df_anomali_vsenM_05=df_M4[df_M5["M5"]=="1"]
df_anomali_vsenM_05.head()

/tmp/ipython-input-2277599327.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M5["M5"]=np.where(((df_M5["R607_A"]=="A")|(df_M5["R607_B"]=="B")) & (df_M5["R407"]<=10),"1","0")
/tmp/ipython-input-2277599327.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M5["Keterangan"]=np.where(df_M5["M5"]=="1","Penduduk usia 10 tahun kebawah yang mengikuti Kursus. Perlu diperiksa ulang Kursus apa yang diikuti","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, R401, R402, ID_art, R407, R509, M4, Keterangan]
Index: []

In [ ]:
#Anomali M6
cols_to_keep6=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','R401','R402','ID_art','R407','R608']
df_M6=df_kor[cols_to_keep6]
df_M6["M6"]=np.where((df_M6["R608"]==5) & ((df_M6["R407"]<=45) & (df_M6["R407"]>6)) ,"1","0")
df_M6["Keterangan"]=np.where(df_M6["M6"],"Penduduk di bawah 45 tahun tetapi tidak bisa baca tulis huruf latin","")
df_anomali_vsenM6=df_M6[df_M6["M6"]=="1"]
df_anomali_vsenM6.head()
#df_anomali_vsenM6.to_excel("df_anomali_vsen_M_04_1.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
#df_anomali_vsenM_04_1.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/04_1 Ijazah SD krg 12 tahun.xlsx', index=False)

/tmp/ipython-input-1343971396.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M6["M6"]=np.where((df_M6["R608"]==5) & ((df_M6["R407"]<=45) & (df_M6["R407"]>6)) ,"1","0")
/tmp/ipython-input-1343971396.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M6["Keterangan"]=np.where(df_M6["M6"],"Penduduk di bawah 45 tahun tetapi tidak bisa baca tulis huruf latin","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,R401,R402,ID_art,R407,R608,M6,Keterangan
19,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50039,003901,1,1,EFRAN ZAMZAMI,EFRAN ZAMZAMI,4,GHASANI MUHAMMAD RAFA,5003914,9.0,5.0,1,Penduduk di bawah 45 tahun tetapi tidak bisa b...
49,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,3,RINTANI YASIRA,5010813,11.0,5.0,1,Penduduk di bawah 45 tahun tetapi tidak bisa b...

In [ ]:
#Anomali M7
cols_to_keep7=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','R401','R402','ID_art','R407','R610']
df_M7=df_kor[cols_to_keep7]
df_M7["M7"]=np.where(((df_M7["R407"]<=6)&(df_M7["R610"]==2)),"1","0")
df_M7["Keterangan"]=np.where(df_M7["M7"]=="1","Penduduk usia 5 tahun ke bawah tetapi telah bersekolah R610=2 & R407<=6","")
df_anomali_vsenM_07=df_M7[df_M7["M7"]=="1"]
#df_anomali_vsenM_07.to_excel("df_anomali_vsen_M_07.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
#df_anomali_vsenM_07.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/07 Angkutan Utama menggunakan kendaraan umum bermotor rute tertentu.xlsx', index=False)
df_anomali_vsenM_07.head()

/tmp/ipython-input-973412566.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M7["M7"]=np.where(((df_M7["R407"]<=6)&(df_M7["R610"]==2)),"1","0")
/tmp/ipython-input-973412566.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M7["Keterangan"]=np.where(df_M7["M7"]=="1","Penduduk usia 5 tahun ke bawah tetapi telah bersekolah R610=2 & R407<=6","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,R401,R402,ID_art,R407,R610,M7,Keterangan
15,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50033,003300,3,1,SLAMET SUPRIANTO,SLAMET SUPRIANTO,5,AISYAH AZIRA UFAIRAH,5003335,6.0,2.0,1,Penduduk usia 5 tahun ke bawah tetapi telah be...

In [ ]:
#Anomali M8
cols_to_keep8=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','R401','R402','ID_art','R407','R610']
df_M8=df_kor[cols_to_keep8]
df_M8["M8"]=np.where(((df_M8["R407"]>=7)&(df_M8["R407"]<=18))&(df_M8["R610"]==1),"1","0")
df_M8["Keterangan"]=np.where(df_M8["M8"]=="1","(Penduduk usia di 7-18 tahun tetapi belum bersekolah sama sekali","")
df_anomali_vsenM_08=df_M8[df_M8["M8"]=="1"]
df_anomali_vsenM_08
#df_anomali_vsenM_08.to_excel("df_anomali_vsen_M_08.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
#df_anomali_vsenM_08.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/08 Cek Isian Lainnya di M609.xlsx', index=False)

/tmp/ipython-input-151614719.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M8["M8"]=np.where(((df_M8["R407"]>=7)&(df_M8["R407"]<=18))&(df_M8["R610"]==1),"1","0")
/tmp/ipython-input-151614719.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M8["Keterangan"]=np.where(df_M8["M8"]=="1","(Penduduk usia di 7-18 tahun tetapi belum bersekolah sama sekali","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,R401,R402,ID_art,R407,R610,M8,Keterangan
19,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50039,003901,1,1,EFRAN ZAMZAMI,EFRAN ZAMZAMI,4,GHASANI MUHAMMAD RAFA,5003914,9.0,1.0,1,(Penduduk usia di 7-18 tahun tetapi belum bers...
49,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,1,M. YASIR,M. YASIR,3,RINTANI YASIRA,5010813,11.0,1.0,1,(Penduduk usia di 7-18 tahun tetapi belum bers...

In [ ]:
#Anomali M9
cols_to_keep9=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','R401','R402','ID_art','R407','R611','R612']
df_M9=df_kor[cols_to_keep9]
df_M9["M9"]=np.where((df_M9["R611"]==1) & (df_M9["R612"]>=18),"1","0")
df_M9["Keterangan"]=np.where(df_M9["M9"]=="1","Penduduk sedang bersekolah di perguruan tinggi negeri. (Khusus Tanjung Jabung Barat) Tidak ada perguruan tinggi negeri di Tanjung Jabung Barat","")
df_anomali_vsenM_09=df_M9[df_M9["M9"]=="1"]
df_anomali_vsenM_09

/tmp/ipython-input-3997029301.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M9["M9"]=np.where((df_M9["R611"]==1) & (df_M9["R612"]>=18),"1","0")
/tmp/ipython-input-3997029301.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M9["Keterangan"]=np.where(df_M9["M9"]=="1","Penduduk sedang bersekolah di perguruan tinggi negeri. (Khusus Tanjung Jabung Barat) Tidak ada perguruan tinggi negeri di Tanjung Jabung Barat","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, R401, R402, ID_art, R407, R611, R612, M9, Keterangan]
Index: []

[0 rows x 21 columns]

In [ ]:
#Anomali M10
cols_to_keep10=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','R401','R402','ID_art','R407','R610','R614']
df_M10=df_kor[cols_to_keep10]
df_M10["M10"]=np.where((df_M10["R610"]==2) & (df_M10["R407"]<12) & ((df_M10["R614"]==3)|(df_M10["R614"]==4)),"1","0")
df_M10["Keterangan"]=np.where(df_M10["M10"]=="1","Anak usia di bawah 12 tahun tetapi sudah ijazah SD/MI","")
df_anomali_vsenM_10=df_M10[df_M10["M10"]=="1"]
df_anomali_vsenM_10
#df_anomali_vsenM_09.to_excel("df_anomali_vsen_M_09.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
#df_anomali_vsenM_09.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/09 Cek Isian Lainnya di M703.xlsx', index=False)

/tmp/ipython-input-2597263102.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M10["M10"]=np.where((df_M10["R610"]==2) & (df_M10["R407"]<12) & ((df_M10["R614"]==3)|(df_M10["R614"]==4)),"1","0")
/tmp/ipython-input-2597263102.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M10["Keterangan"]=np.where(df_M10["M10"]=="1","Anak usia di bawah 12 tahun tetapi sudah ijazah SD/MI","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, R401, R402, ID_art, R407, R610, R614, M10, Keterangan]
Index: []

[0 rows x 21 columns]

In [ ]:
#Anomali M11
cols_to_keep11=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','R401','R402','ID_art','R407','R610','R614']
df_M11=df_kor[cols_to_keep11]
df_M11["M11"]=np.where((df_M11["R610"]==2) & (df_M11["R407"]<15) & ((df_M11["R614"]==8)|(df_M11["R614"]==9)),"1","0")
df_M11["Keterangan"]=np.where(df_M11["M11"]=="1","Anak usia di bawah 15 tahun tetapi sudah ijazah SMP/MTS","")
df_anomali_vsenM_11=df_M11[df_M11["M11"]=="1"]
df_anomali_vsenM_11

/tmp/ipython-input-3445621251.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M11["M11"]=np.where((df_M11["R610"]==2) & (df_M11["R407"]<15) & ((df_M11["R614"]==8)|(df_M11["R614"]==9)),"1","0")
/tmp/ipython-input-3445621251.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M11["Keterangan"]=np.where(df_M11["M11"]=="1","Anak usia di bawah 15 tahun tetapi sudah ijazah SMP/MTS","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, R401, R402, ID_art, R407, R610, R614, M11, Keterangan]
Index: []

[0 rows x 21 columns]

In [ ]:
#Anomali M12
cols_to_keep12=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','R401','R402','ID_art','R407','R610','R614']
df_M12=df_kor[cols_to_keep12]
df_M12["M12"]=np.where((df_M12["R610"]==2) & (df_M12["R407"]<18) & ((df_M12["R614"]>=13)&(df_M12["R614"]<=16)),"1","0")
df_M12["Keterangan"]=np.where(df_M12["M12"]=="1","Anak usia di bawah 15 tahun tetapi sudah ijazah SMA/MA/SMK","")
df_anomali_vsenM_12=df_M12[df_M12["M12"]=="1"]
df_anomali_vsenM_12

/tmp/ipython-input-3186026217.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M12["M12"]=np.where((df_M12["R610"]==2) & (df_M12["R407"]<18) & ((df_M12["R614"]>=13)&(df_M12["R614"]<=16)),"1","0")
/tmp/ipython-input-3186026217.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M12["Keterangan"]=np.where(df_M12["M12"]=="1","Anak usia di bawah 15 tahun tetapi sudah ijazah SMA/MA/SMK","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,...,NAMAKRTDSR,NAMAKRT,R401,R402,ID_art,R407,R610,R614,M12,Keterangan
38,7,TANJUNG JABUNG BARAT,21,SENYERANG,5,SENYERANG,2,01075,001100,9,...,BAMBANG BASUKI RAHMAT,BAMBANG BASUKI RAHMAT,3,A BAYU HANDHIKA P,0107593,17.0,2.0,15.0,1,Anak usia di bawah 15 tahun tetapi sudah ijaza...

In [ ]:
#Anomali M13
cols_to_keep13=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R610','R615']
df_M13=df_kor[cols_to_keep13]
df_M13["M13"]=np.where(((df_M13["R610"]==2) & (df_M13["R615"]==5) ),"1","0")
df_M13["Keterangan"]=np.where(df_M13["M13"]=="1","Anak sekolah tidak pernah sarapan/makan pagi","")
df_anomali_vsenM_13=df_M13[df_M13["M13"]=="1"]
df_anomali_vsenM_13.head()
#df_anomali_vsenM_13.to_excel("df_anomali_vsen_M_13.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
#df_anomali_vsenM_13.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/13 Cek Isian Lainnya di M806.xlsx', index=False)

/tmp/ipython-input-442022378.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M13["M13"]=np.where(((df_M13["R610"]==2) & (df_M13["R615"]==5) ),"1","0")
/tmp/ipython-input-442022378.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M13["Keterangan"]=np.where(df_M13["M13"]=="1","Anak sekolah tidak pernah sarapan/makan pagi","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_art,R401,R402,R610,R615,M13,Keterangan
85,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,15,SUNGAI NIBUNG,1,50137,000100,2,1,M. SARNUBI,M. SARNUBI,5013723,3,ZAHRA AQILA RAMADHANI,2.0,5.0,1,Anak sekolah tidak pernah sarapan/makan pagi

In [ ]:
#Anomali M14
cols_to_keep14=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R610','R616']
df_M14=df_kor[cols_to_keep14]
df_M14["M14"]=np.where(((df_M14["R610"]==2) & (df_M14["R616"]==5) ),"1","0")
df_M14["Keterangan"]=np.where(df_M14["M14"]=="1","Anak sekolah tidak pernah dapat uang saku","")
df_anomali_vsenM_14=df_M14[df_M14["M14"]=="1"]
df_anomali_vsenM_14.head()

/tmp/ipython-input-2499460075.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M14["M14"]=np.where(((df_M14["R610"]==2) & (df_M14["R616"]==5) ),"1","0")
/tmp/ipython-input-2499460075.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M14["Keterangan"]=np.where(df_M14["M14"]=="1","Anak sekolah tidak pernah dapat uang saku","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_art, R401, R402, R610, R616, M14, Keterangan]
Index: []

In [ ]:
#Anomali M15
cols_to_keep15=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R407','R610','R617']
df_M15=df_kor[cols_to_keep15]
df_M15["M15"]=np.where(((df_M15["R610"]==2) & (df_M15["R617"]==5) & (df_M15["R407"]<=18) & (df_M15["NAMAKECAMA"]=="TUNGKAL ILIR")),"1","0")
df_M15["Keterangan"]=np.where(df_M15["M15"]=="1","Anak sekolah berumur 18 tahun kebawah di Tungkal Ilir tidak mendapat MBG","")
df_anomali_vsenM_15=df_M15[df_M15["M15"]=="1"]
df_anomali_vsenM_15.head()

/tmp/ipython-input-4139454676.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M15["M15"]=np.where(((df_M15["R610"]==2) & (df_M15["R617"]==5) & (df_M15["R407"]<=18) & (df_M15["NAMAKECAMA"]=="TUNGKAL ILIR")),"1","0")
/tmp/ipython-input-4139454676.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M15["Keterangan"]=np.where(df_M15["M15"]=="1","Anak sekolah berumur 18 tahun kebawah di Tungkal Ilir tidak mendapat MBG","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,...,NAMAKRTDSR,NAMAKRT,ID_art,R401,R402,R407,R610,R617,M15,Keterangan
44,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50054,001300,5,...,RASIDI,RASIDI,5005453,3,M. RIDO SAPUTRA,17.0,2.0,5.0,1,Anak sekolah berumur 18 tahun kebawah di Tungk...
50,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,...,M. YASIR,M. YASIR,5010814,4,M. ALFARIZQI,7.0,2.0,5.0,1,Anak sekolah berumur 18 tahun kebawah di Tungk...
55,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,3,...,ABDULLAH,ABDULLAH,5010833,3,NILNA RUHAMA,12.0,2.0,5.0,1,Anak sekolah berumur 18 tahun kebawah di Tungk...
95,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50206,000702,8,...,MULYADI,MULYADI,5020683,3,MUHAMMAD RIZKI RAMADHAN,10.0,2.0,5.0,1,Anak sekolah berumur 18 tahun kebawah di Tungk...
99,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50213,001301,2,...,RUSLI,RUSLI,5021323,3,FARHAN SAIDINA MUHAMMAD,7.0,2.0,5.0,1,Anak sekolah berumur 18 tahun kebawah di Tungk...

In [ ]:
#Anomali M16
cols_to_keep16=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R407','R605','R623']
df_M16=df_kor[cols_to_keep16]
df_M16["M16"]=np.where(((df_M16["R623"]==1) & (df_M16["R605"]>1)),"1","0")
df_M16["Keterangan"]=np.where(df_M16["M16"]=="1","Anak sedang tidak mengikuti Prasekolah (R605>1) tetapi alasan belum pernah bersekolah/tidak bersekolah lagi adalah Sedang mengikuti pendidikan prasekolah (R623=1)","")
df_anomali_vsenM_16=df_M16[df_M16["M16"]=="1"]
df_anomali_vsenM_16.head()

/tmp/ipython-input-1353562999.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M16["M16"]=np.where(((df_M16["R623"]==1) & (df_M16["R605"]>1)),"1","0")
/tmp/ipython-input-1353562999.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M16["Keterangan"]=np.where(df_M16["M16"]=="1","Anak sedang tidak mengikuti Prasekolah (R605>1) tetapi alasan belum pernah bersekolah/tidak bersekolah lagi adalah Sedang mengikuti pendidikan prasekolah (R623=1)","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,...,NAMAKRTDSR,NAMAKRT,ID_art,R401,R402,R407,R605,R623,M16,Keterangan
15,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50033,003300,3,...,SLAMET SUPRIANTO,SLAMET SUPRIANTO,5003335,5,AISYAH AZIRA UFAIRAH,6.0,3.0,1.0,1,Anak sedang tidak mengikuti Prasekolah (R605>1...

In [ ]:
#Anomali M17
cols_to_keep17=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R407','R1002','R1003','R1004','R1005','R1006','R1007','R1008','R1009','R623']
df_M17=df_kor[cols_to_keep17]
df_M17["M17"]=np.where(((df_M17["R623"]==8) &
 ((df_M17["R1002"]<=2)&(df_M17["R1003"]<=6)&(df_M17["R1004"]<=2)&(df_M17["R1005"]<=6)
 &(df_M17["R1006"]<=2)&(df_M17["R1007"]<=6)&(df_M17["R1008"]<=2)&(df_M17["R1009"]<=6))),"1","0")
df_M17["Keterangan"]=np.where(df_M17["M17"]=="1","Anak tidak mengalami gangguan fungsional apapun (Blok X <= 2 atau Blok X>=6 ) tetapi alasan belum pernah bersekolah/tidak bersekolah lagi adalah mengalami gangguan fungsional atau kecacatan","")
df_anomali_vsenM_17=df_M17[df_M17["M17"]=="1"]
df_anomali_vsenM_17.head()

/tmp/ipython-input-2932283225.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M17["M17"]=np.where(((df_M17["R623"]==8) &
/tmp/ipython-input-2932283225.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M17["Keterangan"]=np.where(df_M17["M17"]=="1","Anak tidak mengalami gangguan fungsional apapun (Blok X <= 2 atau Blok X>=6 ) tetapi alasan belum pernah bersekolah/tidak bersekolah lagi adalah mengalami gangguan fungsional atau kecacatan","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_art, R401, R402, R407, R1002, R1003, R1004, R1005, R1006, R1007, R1008, R1009, R623, M17, Keterangan]
Index: []

[0 rows x 28 columns]

In [ ]:
#Anomali M18
cols_to_keep18=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R407','R623']
df_M18=df_kor[cols_to_keep18]
df_M18["M18"]=np.where(((df_M18["R623"]==11)),"1","0")
df_M18["Keterangan"]=np.where(df_M18["M18"]=="1","Cek kembali uraian lainnya di R623, periksa siapa tau ada yg pas dengan kode yg sdh ada di kues dan apabila telah sesuai tuliskan di catatan","")
df_anomali_vsenM_18=df_M18[df_M18["M18"]=="1"]
df_anomali_vsenM_18.head()

/tmp/ipython-input-1726746481.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M18["M18"]=np.where(((df_M18["R623"]==11)),"1","0")
/tmp/ipython-input-1726746481.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M18["Keterangan"]=np.where(df_M18["M18"]=="1","Cek kembali uraian lainnya di R623, periksa siapa tau ada yg pas dengan kode yg sdh ada di kues dan apabila telah sesuai tuliskan di catatan","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_art,R401,R402,R407,R623,M18,Keterangan
22,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,00637102,2,YOGI,21.0,11.0,1,"Cek kembali uraian lainnya di R623, periksa si..."

In [ ]:
#Anomali M19
cols_to_keep19=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R701','R706']
df_M19=df_kor[cols_to_keep19]
df_M19["M19"]=np.where(((df_M19["R701"]==5)&(df_M19["R706"]==5)),"1","0")
df_M19["Keterangan"]=np.where(df_M19["M19"]=="1","ART adalah PNS/TNI/POLRI/Pegawai BUMN/Pegawai BUMD/Pejabat Negara tetapi tidak memiliki rekening tabungan","")
df_anomali_vsenM_19=df_M19[df_M19["M19"]=="1"]
df_anomali_vsenM_19.head()

/tmp/ipython-input-1811445941.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M19["M19"]=np.where(((df_M19["R701"]==5)&(df_M19["R706"]==5)),"1","0")
/tmp/ipython-input-1811445941.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M19["Keterangan"]=np.where(df_M19["M19"]=="1","ART adalah PNS/TNI/POLRI/Pegawai BUMN/Pegawai BUMD/Pejabat Negara tetapi tidak memiliki rekening tabungan","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_art, R701, R706, M19, Keterangan]
Index: []

In [ ]:
#Anomali M20
cols_to_keep20=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R701','R706','R619']
df_M20=df_kor[cols_to_keep20]
df_M20["M20"]=np.where(((df_M20["R701"]==5)&(df_M20["R619"]==1)),"1","0")
df_M20["Keterangan"]=np.where(df_M20["M20"]=="1","ART tidak memiliki rekening tabungan (R702=5) tetapi menerima Program Indonesia Pintar (PIP) (R619=5)","")
df_anomali_vsenM_20=df_M20[df_M20["M20"]=="1"]
df_anomali_vsenM_20.head()

/tmp/ipython-input-4272245348.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M20["M20"]=np.where(((df_M20["R701"]==5)&(df_M20["R619"]==1)),"1","0")
/tmp/ipython-input-4272245348.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M20["Keterangan"]=np.where(df_M20["M20"]=="1","ART tidak memiliki rekening tabungan (R702=5) tetapi menerima Program Indonesia Pintar (PIP) (R619=5)","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_art,R701,R706,R619,M20,Keterangan
5,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,39,PEMATANG TEMBESU,2,00110,000400,1,1,A. RAFIK,A. RAFIK,0011013,5.0,NaN,1.0,1,ART tidak memiliki rekening tabungan (R702=5) ...
6,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,39,PEMATANG TEMBESU,2,00110,000400,1,1,A. RAFIK,A. RAFIK,0011014,5.0,NaN,1.0,1,ART tidak memiliki rekening tabungan (R702=5) ...
7,7,TANJUNG JABUNG BARAT,10,TUNGKAL ULU,39,PEMATANG TEMBESU,2,00110,000400,1,1,A. RAFIK,A. RAFIK,0011015,5.0,NaN,1.0,1,ART tidak memiliki rekening tabungan (R702=5) ...
80,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50114,000801,5,1,RESTUONO,RESTUONO,5011453,5.0,NaN,1.0,1,ART tidak memiliki rekening tabungan (R702=5) ...
92,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,16,SRIWIJAYA,1,50163,001300,9,1,MISRAN,MISRAN,5016394,5.0,NaN,1.0,1,ART tidak memiliki rekening tabungan (R702=5) ...

In [ ]:
#Anomali M21
cols_to_keep21=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R701','R1701A','R1701B','R1701C']
df_M21=df_kor[cols_to_keep21]
df_M21["M21"]=np.where(((df_M21["R701"]==5)&(df_M21["R1701A"]==1)&(df_M21["R1701B"]==1)&(df_M21["R1701C"]==1)),"1","0")
df_M21["Keterangan"]=np.where(df_M21["M21"]=="1","ART pernah menerima/mencairkan kredit (R1701 terisi 1) tetapi tidak memiliki rekening tabungan","")
df_anomali_vsenM_21=df_M21[df_M21["M21"]=="1"]
df_anomali_vsenM_21.head()

/tmp/ipython-input-1738303643.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M21["M21"]=np.where(((df_M21["R701"]==5)&(df_M21["R1701A"]==1)&(df_M21["R1701B"]==1)&(df_M21["R1701C"]==1)),"1","0")
/tmp/ipython-input-1738303643.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M21["Keterangan"]=np.where(df_M21["M21"]=="1","ART pernah menerima/mencairkan kredit (R1701 terisi 1) tetapi tidak memiliki rekening tabungan","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_art, R701, R1701A, R1701B, R1701C, M21, Keterangan]
Index: []

In [ ]:
#Anomali M22
cols_to_keep22=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R701','R702']
df_M22=df_kor[cols_to_keep22]
df_M22["M22"]=np.where(((df_M22["R701"]==1)&(df_M22["R702"]==5)),"1","0")
df_M22["Keterangan"]=np.where(df_M22["M22"]=="1","ART memiliki rekening tabungan (R701=1) tetapi tidak ernah menggunakan jasa lembaga keuangan.","")
df_anomali_vsenM_22=df_M22[df_M22["M22"]=="1"]
df_anomali_vsenM_22.head()

/tmp/ipython-input-805415056.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M22["M22"]=np.where(((df_M22["R701"]==1)&(df_M22["R702"]==5)),"1","0")
/tmp/ipython-input-805415056.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M22["Keterangan"]=np.where(df_M22["M22"]=="1","ART memiliki rekening tabungan (R701=1) tetapi tidak ernah menggunakan jasa lembaga keuangan.","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_art,R701,R702,M22,Keterangan
30,7,TANJUNG JABUNG BARAT,20,PENGABUAN,18,PASAR SENIN,2,00993,000500,2,1,ARIF HARIYANTO,ARIF HARIYANTO,0099322,1.0,5.0,1,ART memiliki rekening tabungan (R701=1) tetapi...
78,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50114,000801,5,1,RESTUONO,RESTUONO,5011451,1.0,5.0,1,ART memiliki rekening tabungan (R701=1) tetapi...
79,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50114,000801,5,1,RESTUONO,RESTUONO,5011452,1.0,5.0,1,ART memiliki rekening tabungan (R701=1) tetapi...
93,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50206,000702,8,1,MULYADI,MULYADI,5020681,1.0,5.0,1,ART memiliki rekening tabungan (R701=1) tetapi...
127,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,7,TANJUNG PASIR,2,01601,001300,1,1,MASTANIAH,MASTANIAH,0160111,1.0,5.0,1,ART memiliki rekening tabungan (R701=1) tetapi...

In [ ]:
#Anomali M23
cols_to_keep23=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R702','R1701A','R1701B','R1701C']
df_M23=df_kor[cols_to_keep23]
df_M23["M23"]=np.where(((df_M23["R702"]==5)&(df_M23["R1701A"]==1)&(df_M23["R1701B"]==1)&(df_M23["R1701C"]==1)),"1","0")
df_M23["Keterangan"]=np.where(df_M23["M23"]=="1","ART pernah menerima/mencairkan kredit (R1701 terisi 1) tetapi tidak memiliki rekening tabungan","")
df_anomali_vsenM_23=df_M23[df_M23["M23"]=="1"]
df_anomali_vsenM_23.head()

/tmp/ipython-input-3915188710.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M23["M23"]=np.where(((df_M23["R702"]==5)&(df_M23["R1701A"]==1)&(df_M23["R1701B"]==1)&(df_M23["R1701C"]==1)),"1","0")
/tmp/ipython-input-3915188710.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M23["Keterangan"]=np.where(df_M23["M23"]=="1","ART pernah menerima/mencairkan kredit (R1701 terisi 1) tetapi tidak memiliki rekening tabungan","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_art, R702, R1701A, R1701B, R1701C, M23, Keterangan]
Index: []

In [ ]:
#Anomali M24
cols_to_keep24=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R708','R1701A','R1701B','R1701C']
df_M24=df_kor[cols_to_keep24]
df_M24["M24"]=np.where(((df_M24["R708"]<=12)),"1","0")
df_M24["Keterangan"]=np.where(df_M24["M24"]=="1","Jam kerja seminggu terakhir dibawah 12 jam","")
df_anomali_vsenM_24=df_M24[df_M24["M24"]=="1"]
df_anomali_vsenM_24.head()

/tmp/ipython-input-4275256854.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M24["M24"]=np.where(((df_M24["R708"]<=12)),"1","0")
/tmp/ipython-input-4275256854.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M24["Keterangan"]=np.where(df_M24["M24"]=="1","Jam kerja seminggu terakhir dibawah 12 jam","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,...,NAMAKRT,ID_art,R401,R402,R708,R1701A,R1701B,R1701C,M24,Keterangan
83,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,15,SUNGAI NIBUNG,1,50137,000100,2,...,M. SARNUBI,5013721,1,M. SARNUBI,0.0,5,5,5,1,Jam kerja seminggu terakhir dibawah 12 jam
84,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,15,SUNGAI NIBUNG,1,50137,000100,2,...,M. SARNUBI,5013722,2,MARIANA,0.0,5,5,5,1,Jam kerja seminggu terakhir dibawah 12 jam

In [ ]:
#Anomali M25
cols_to_keep25=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R703_A','R802']
df_M25=df_kor[cols_to_keep25]
df_M25["M25"]=np.where(((df_M25["R703_A"]=="A")&(df_M25["R802"]==5)),"1","0")
df_M25["Keterangan"]=np.where(df_M25["M25"]=="1","ART bekerja tetapi tidak menguasai telpon seluler (R802=5). Bagaimana komunikasinya?","")
df_anomali_vsenM_25=df_M25[df_M25["M25"]=="1"]
df_anomali_vsenM_25.head()

/tmp/ipython-input-570817063.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M25["M25"]=np.where(((df_M25["R703_A"]=="A")&(df_M25["R802"]==5)),"1","0")
/tmp/ipython-input-570817063.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M25["Keterangan"]=np.where(df_M25["M25"]=="1","ART bekerja tetapi tidak menguasai telpon seluler (R802=5). Bagaimana komunikasinya?","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_art,R401,R402,R703_A,R802,M25,Keterangan
21,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,1,AHMAD TAZLI,AHMAD TAZLI,00637101,1,AHMAD TAZLI,A,5.0,1,ART bekerja tetapi tidak menguasai telpon selu...
26,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,1,NIDAR,NIDAR,0067221,1,NIDAR,A,5.0,1,ART bekerja tetapi tidak menguasai telpon selu...
32,7,TANJUNG JABUNG BARAT,20,PENGABUAN,18,PASAR SENIN,2,00993,000500,2,1,ARIF HARIYANTO,ARIF HARIYANTO,0099324,4,USWADI,A,5.0,1,ART bekerja tetapi tidak menguasai telpon selu...
51,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,1,SUHAIMI,SUHAIMI,5010821,1,SUHAIMI,A,5.0,1,ART bekerja tetapi tidak menguasai telpon selu...
54,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,3,1,ABDULLAH,ABDULLAH,5010832,2,MARDIANA,A,5.0,1,ART bekerja tetapi tidak menguasai telpon selu...

In [ ]:
#Anomali M26
cols_to_keep26=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R610','R612','R803A']
df_M26=df_kor[cols_to_keep26]
df_M26["M26"]=np.where(((df_M26["R803A"]=="")&(df_M26["R610"]==2)&((df_M26["R612"]<=16)&(df_M26["R612"]>=13))),"1","0")
df_M26["Keterangan"]=np.where(df_M26["M26"]=="1","ART sedang bersekolah tetapi tidak menggunakan PC/DESKTOP (R803_A)","")
df_anomali_vsenM_26=df_M26[df_M26["M26"]=="1"]
df_anomali_vsenM_26.head()

/tmp/ipython-input-2190909364.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M26["M26"]=np.where(((df_M26["R803A"]=="")&(df_M26["R610"]==2)&((df_M26["R612"]<=16)&(df_M26["R612"]>=13))),"1","0")
/tmp/ipython-input-2190909364.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M26["Keterangan"]=np.where(df_M26["M26"]=="1","ART sedang bersekolah tetapi tidak menggunakan PC/DESKTOP (R803_A)","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,...,NAMAKRTDSR,NAMAKRT,ID_art,R401,R402,R610,R612,R803A,M26,Keterangan
38,7,TANJUNG JABUNG BARAT,21,SENYERANG,5,SENYERANG,2,01075,001100,9,...,BAMBANG BASUKI RAHMAT,BAMBANG BASUKI RAHMAT,0107593,3,A BAYU HANDHIKA P,2.0,15.0,,1,ART sedang bersekolah tetapi tidak menggunakan...
44,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50054,001300,5,...,RASIDI,RASIDI,5005453,3,M. RIDO SAPUTRA,2.0,15.0,,1,ART sedang bersekolah tetapi tidak menggunakan...
117,7,TANJUNG JABUNG BARAT,40,BETARA,16,SUNGAI TERAP,2,01512,001000,5,...,USNAINI,USNAINI,0151253,3,JUNI AMANDA PUTRI,2.0,13.0,,1,ART sedang bersekolah tetapi tidak menggunakan...
121,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,3,BETARA KIRI,2,01551,000100,2,...,RIDWAN,RIDWAN,0155123,3,M. SALMAN,2.0,13.0,,1,ART sedang bersekolah tetapi tidak menggunakan...

In [ ]:
#Anomali M27
cols_to_keep27=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R804','R407']
df_M27=df_kor[cols_to_keep27]
df_M27["M27"]=np.where(((df_M27["R804"]=="")&(df_M27["R407"]<30)),"1","0")
df_M27["Keterangan"]=np.where(df_M27["M27"]=="1","ART usia kurang dari 30 tahun tetapi tidak pernah menggunakan internet 3 bulan terakhir (R804=5).","")
df_anomali_vsenM_27=df_M27[df_M27["M27"]=="1"]
df_anomali_vsenM_27.head()

/tmp/ipython-input-3501796552.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M27["M27"]=np.where(((df_M27["R804"]=="")&(df_M27["R407"]<30)),"1","0")
/tmp/ipython-input-3501796552.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M27["Keterangan"]=np.where(df_M27["M27"]=="1","ART usia kurang dari 30 tahun tetapi tidak pernah menggunakan internet 3 bulan terakhir (R804=5).","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_art, R804, R407, M27, Keterangan]
Index: []

In [ ]:
#Anomali M28
cols_to_keep28=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R809I']
df_M28=df_kor[cols_to_keep28]
df_M28["M28"]=np.where(((df_M28["R809I"]=="I")),"1","0")
df_M28["Keterangan"]=np.where(df_M28["M28"]=="1","Cek kembali uraian lainnya, siapa tau ada yg pas dengan kode yg sdh ada di kues","")
df_anomali_vsenM_28=df_M28[df_M28["M28"]=="1"]
df_anomali_vsenM_28.head()

/tmp/ipython-input-2268331506.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M28["M28"]=np.where(((df_M28["R809I"]=="I")),"1","0")
/tmp/ipython-input-2268331506.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M28["Keterangan"]=np.where(df_M28["M28"]=="1","Cek kembali uraian lainnya, siapa tau ada yg pas dengan kode yg sdh ada di kues","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_art,R401,R402,R809I,M28,Keterangan
96,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50206,000702,8,1,MULYADI,MULYADI,5020684,4,M. RIDHO,I,1,"Cek kembali uraian lainnya, siapa tau ada yg p..."

In [ ]:
#Anomali M29
cols_to_keep29=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R1302']
df_M29=df_kor[cols_to_keep29]
df_M29["M29"]=np.where(((df_M29["R1302"]==5)),"1","0")
df_M29["Keterangan"]=np.where(df_M29["M29"]=="1","Balita tidak diberikan imunisasi","")
df_anomali_vsenM_29=df_M29[df_M29["M29"]=="1"]
df_anomali_vsenM_29.head()

/tmp/ipython-input-1529084207.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M29["M29"]=np.where(((df_M29["R1302"]==5)),"1","0")
/tmp/ipython-input-1529084207.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M29["Keterangan"]=np.where(df_M29["M29"]=="1","Balita tidak diberikan imunisasi","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_art, R401, R402, R1302, M29, Keterangan]
Index: []

In [ ]:
#Anomali M30
cols_to_keep30=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R1307F']
df_M30=df_kor[cols_to_keep30]
df_M30["M30"]=np.where(((df_M30["R1307F"]==1)),"1","0")
df_M30["Keterangan"]=np.where(df_M30["M30"]=="1","(R1307F) Cek kembali uraian lainnya, siapa tau ada yg pas dengan kode yg sdh ada di kues","")
df_anomali_vsenM_30=df_M30[df_M30["M30"]=="1"]
df_anomali_vsenM_30.head()

/tmp/ipython-input-2242440472.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M30["M30"]=np.where(((df_M30["R1307F"]==1)),"1","0")
/tmp/ipython-input-2242440472.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M30["Keterangan"]=np.where(df_M30["M30"]=="1","(R1307F) Cek kembali uraian lainnya, siapa tau ada yg pas dengan kode yg sdh ada di kues","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_art,R401,R402,R1307F,M30,Keterangan
59,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,4,1,M. ANUARI,M. ANUARI,5010844,4,AISHWA NAHLA,1.0,1,"(R1307F) Cek kembali uraian lainnya, siapa tau..."

In [ ]:
#Anomali M31
cols_to_keep31=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R1309A']
df_M31=df_kor[cols_to_keep31]
df_M31["M31"]=np.where(((df_M31["R1309A"]==5)),"1","0")
df_M31["Keterangan"]=np.where(df_M31["M31"]=="1","Balita tidak diberikan ASI","")
df_anomali_vsenM_31=df_M31[df_M31["M31"]=="1"]
df_anomali_vsenM_31.head()

/tmp/ipython-input-608266692.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M31["M31"]=np.where(((df_M31["R1309A"]==5)),"1","0")
/tmp/ipython-input-608266692.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M31["Keterangan"]=np.where(df_M31["M31"]=="1","Balita tidak diberikan ASI","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_art, R401, R402, R1309A, M31, Keterangan]
Index: []

In [ ]:
#Anomali M32
cols_to_keep32=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R1401B']
df_M32=df_kor[cols_to_keep32]
df_M32["M32"]=np.where(((df_M32["R1401B"]<=17)),"1","0")
df_M32["Keterangan"]=np.where(df_M32["M32"]=="1","ART hamil pertama kali sebelum berumur 17 tahun","")
df_anomali_vsenM_32=df_M32[df_M32["M32"]=="1"]
df_anomali_vsenM_32.head()

/tmp/ipython-input-3505176158.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M32["M32"]=np.where(((df_M32["R1401B"]<=17)),"1","0")
/tmp/ipython-input-3505176158.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M32["Keterangan"]=np.where(df_M32["M32"]=="1","ART hamil pertama kali sebelum berumur 17 tahun","")

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_art,R401,R402,R1401B,M32,Keterangan
43,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50054,001300,5,1,RASIDI,RASIDI,5005452,2,HASBIAH,17.0,1,ART hamil pertama kali sebelum berumur 17 tahun

In [ ]:
#Anomali M33
cols_to_keep33=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R1402B']
df_M33=df_kor[cols_to_keep33]
df_M33["M33"]=np.where(((df_M33["R1402B"]<=17)),"1","0")
df_M33["Keterangan"]=np.where(df_M33["M33"]=="1","AR melahirkan pertama kali sebelum berumur 17 tahun","")
df_anomali_vsenM_33=df_M33[df_M33["M33"]=="1"]
df_anomali_vsenM_33.head()

/tmp/ipython-input-1874897432.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M33["M33"]=np.where(((df_M33["R1402B"]<=17)),"1","0")
/tmp/ipython-input-1874897432.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M33["Keterangan"]=np.where(df_M33["M33"]=="1","AR melahirkan pertama kali sebelum berumur 17 tahun","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_art, R401, R402, R1402B, M33, Keterangan]
Index: []

In [ ]:
#Anomali M34
cols_to_keep34=[ 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','ID_art','R401','R402','R1102','R1103','R1104','R1105']
df_M34=df_kor[cols_to_keep34]
df_M34["M34"]=np.where(((df_M34["R1102"]==1) & (df_M34["R1103"]==1) & (df_M34["R1104"]==5) & (df_M34["R1105"]==5)),"1","0")
df_M34["Keterangan"]=np.where(df_M34["M34"]=="1","Art Sakit tetapi tidak diobati ","")
df_anomali_vsenM_34=df_M34[df_M34["M34"]=="1"]
df_anomali_vsenM_34.head()

/tmp/ipython-input-1818145500.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M34["M34"]=np.where(((df_M34["R1102"]==1) & (df_M34["R1103"]==1) & (df_M34["R1104"]==5) & (df_M34["R1105"]==5)),"1","0")
/tmp/ipython-input-1818145500.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M34["Keterangan"]=np.where(df_M34["M34"]=="1","Art Sakit tetapi tidak diobati ","")

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_art, R401, R402, R1102, R1103, R1104, R1105, M34, Keterangan]
Index: []

[0 rows x 22 columns]

In [ ]:
### GABUNGKAN SELURUH ANOMALI KONSISTENSI M DAN KP DALAM 1 FILE
import pandas as pd
from functools import reduce

### 00 Masukkan Dataframe yang berisikan Keterangan Anomali
ket_anomali_M_individu = pd.read_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/04 Keterangan Anomali K_Individu.xlsx', engine="openpyxl")

### 01 Gabungkan Seluruh Kode Anomali dan Status Anomali dalam 1 Dataframe
df_M1_sel=df_M1[["ID_art","M1"]]
df_M2_sel=df_M2[["ID_art","M2"]]
df_M3_sel=df_M3[["ID_art","M3"]]
df_M4_sel=df_M4[["ID_art","M4"]]
df_M5_sel=df_M5[["ID_art","M5"]]
df_M6_sel=df_M6[["ID_art","M6"]]
df_M7_sel=df_M7[["ID_art","M7"]]
df_M8_sel=df_M8[["ID_art","M8"]]
df_M9_sel=df_M9[["ID_art","M9"]]
df_M10_sel=df_M10[["ID_art","M10"]]
df_M11_sel=df_M11[["ID_art","M11"]]
df_M12_sel=df_M12[["ID_art","M12"]]
df_M13_sel=df_M13[["ID_art","M13"]]
df_M14_sel=df_M14[["ID_art","M14"]]
df_M15_sel=df_M15[["ID_art","M15"]]
df_M16_sel=df_M16[["ID_art","M16"]]
df_M17_sel=df_M17[["ID_art","M17"]]
df_M18_sel=df_M18[["ID_art","M18"]]
df_M19_sel=df_M19[["ID_art","M19"]]
df_M20_sel=df_M20[["ID_art","M20"]]
df_M21_sel=df_M21[["ID_art","M21"]]
df_M22_sel=df_M22[["ID_art","M22"]]
df_M23_sel=df_M23[["ID_art","M23"]]
df_M24_sel=df_M24[["ID_art","M24"]]
df_M25_sel=df_M25[["ID_art","M25"]]
df_M26_sel=df_M26[["ID_art","M26"]]
df_M27_sel=df_M27[["ID_art","M27"]]
df_M28_sel=df_M28[["ID_art","M28"]]
df_M29_sel=df_M29[["ID_art","M29"]]
df_M30_sel=df_M30[["ID_art","M30"]]
df_M31_sel=df_M31[["ID_art","M31"]]
df_M32_sel=df_M32[["ID_art","M32"]]
df_M33_sel=df_M33[["ID_art","M33"]]
df_M34_sel=df_M34[["ID_art","M34"]]



df_merged_M=[df_M1_sel,
df_M2_sel,
df_M3_sel,
df_M4_sel,
df_M5_sel,
df_M6_sel,
df_M7_sel,
df_M8_sel,
df_M9_sel,
df_M10_sel,
df_M11_sel,
df_M12_sel,
df_M13_sel,
df_M14_sel,
df_M15_sel,
df_M16_sel,
             df_M17_sel,
             df_M18_sel,
             df_M19_sel,
             df_M20_sel,
             df_M21_sel,
             df_M22_sel,
             df_M23_sel,
             df_M24_sel,
             df_M25_sel,
             df_M26_sel,
             df_M27_sel,
df_M28_sel,
df_M29_sel,
df_M30_sel,
df_M31_sel,
df_M32_sel,
df_M33_sel,df_M34_sel]
df_M_pivot = reduce(lambda left, right: pd.merge(left, right, on="ID_art", how="outer"), df_merged_M)
df_M_pivot.head()

### 02 Unpivot Dataframe yanng berisikan ID_ruta dengan Kode Anomali dan Status Anomali
df_M_Ind_melted = pd.melt(
    df_M_pivot,
    id_vars=["ID_art"],          # rows
    value_vars=[ 'M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M7',
 'M8',
 'M9',
 'M10',
 'M11',
 'M12',
 'M13',
 'M14',
 'M15',
 'M16',
       'M17',
                 'M18',
                 'M19',
                 'M21',
                 'M22',
                 'M23',
                 'M24',
                 'M25',
                 'M26',
                 'M27',
 'M28',
 'M29',
 'M30',
 'M31',
 'M32',
 'M33','M34'],
    var_name="Kode Anomali",
    value_name="Status Anomali"
    )
df_M_Ind_melted

### 03 Siapkan Dataframe yang berisikan Identitas seluruh Ruta Sampel SSN
cols_to_keep_df_kor_ind=['ID_art', 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'NAMAKRTDSR', 'NAMAKRT','R401','R402','CATATAN']
df_M_ID=df_kor[cols_to_keep_df_kor_ind]

### 04 Merge Dataframe yang berisikan Identitas seluruh Ruta Sampel SSN dengan Dataframe yang berisikan Status Anomali
df_M_ind_full=pd.merge(df_M_ID,df_M_Ind_melted, on="ID_art", how="left")
df_M_ind_full_anomali=df_M_ind_full[df_M_ind_full["Status Anomali"]=="1"]
df_M_ind_full_anomali=df_M_ind_full_anomali.drop(columns="Status Anomali")

### 06 Merge Dataframe yang berisikan keterangan Anomali dengan Dataframe yang berisikan Ruta-Ruta berdasarkan Anomali
dfAnomaliM_ind=pd.merge(df_M_ind_full_anomali,ket_anomali_M_individu, on="Kode Anomali", how="left")

### 07 Export Dataframe yang berisikan Ruta dengan anomali beserta keterangannya
dfAnomaliM_ind.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/08. Kegiatan Teknis 2026/01 SUSENAS Maret dan SERUTI Triwulan I 2026/03 Pasca Lapangan/05 Pengolahan SUSENAS Maret dan SERUTI Triwulan I 2026/01 Hasil Evaluasi BPS Kabupaten Tanjung Jabung Barat/[00 Rekap Pengecekan Anomali VSEN25-M].xlsx', index=False)
dfAnomaliM_ind

,ID_art,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,NAMAKRTDSR,NAMAKRT,R401,R402,CATATAN,Kode Anomali,Keterangan
0,5003335,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50033,003300,3,SLAMET SUPRIANTO,SLAMET SUPRIANTO,5,AISYAH AZIRA UFAIRAH,,M7,Penduduk usia 5 tahun ke bawah tetapi telah be...
1,5003335,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50033,003300,3,SLAMET SUPRIANTO,SLAMET SUPRIANTO,5,AISYAH AZIRA UFAIRAH,,M16,Anak sedang tidak mengikuti Prasekolah (R605>1...
2,5003914,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50039,003901,1,EFRAN ZAMZAMI,EFRAN ZAMZAMI,4,GHASANI MUHAMMAD RAFA,,M6,Penduduk usia 45 tahun ke bawah tidak bisa bac...
3,5003914,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50039,003901,1,EFRAN ZAMZAMI,EFRAN ZAMZAMI,4,GHASANI MUHAMMAD RAFA,,M8,Penduduk usia di 7-18 tahun tetapi belum berse...
4,00637101,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,AHMAD TAZLI,AHMAD TAZLI,1,AHMAD TAZLI,,M25,ART bekerja tetapi tidak menguasai telpon selu...
5,00637102,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,2,SUNGAI ROTAN,2,00637,000500,10,AHMAD TAZLI,AHMAD TAZLI,2,YOGI,,M18,"Cek kembali uraian lainnya di R623, periksa si..."
6,0067221,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,5,PULAU PAUH,2,00672,000300,2,NIDAR,NIDAR,1,NIDAR,,M25,ART bekerja tetapi tidak menguasai telpon selu...
7,0099322,7,TANJUNG JABUNG BARAT,20,PENGABUAN,18,PASAR SENIN,2,00993,000500,2,ARIF HARIYANTO,ARIF HARIYANTO,2,WAFI MAGHFIROH,,M22,ART memiliki rekening tabungan (R701=1) tetapi...
8,0099324,7,TANJUNG JABUNG BARAT,20,PENGABUAN,18,PASAR SENIN,2,00993,000500,2,ARIF HARIYANTO,ARIF HARIYANTO,4,USWADI,,M25,ART bekerja tetapi tidak menguasai telpon selu...
9,0107593,7,TANJUNG JABUNG BARAT,21,SENYERANG,5,SENYERANG,2,01075,001100,9,BAMBANG BASUKI RAHMAT,BAMBANG BASUKI RAHMAT,3,A BAYU HANDHIKA P,,M12,Anak usia di bawah 15 tahun tetapi sudah ijaza...
10,0107593,7,TANJUNG JABUNG BARAT,21,SENYERANG,5,SENYERANG,2,01075,001100,9,BAMBANG BASUKI RAHMAT,BAMBANG BASUKI RAHMAT,3,A BAYU HANDHIKA P,,M26,ART sedang bersekolah tetapi tidak menggunakan...
11,5005452,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50054,001300,5,RASIDI,RASIDI,2,HASBIAH,,M32,ART hamil pertama kali sebelum berumur 17 tahun
12,5005453,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50054,001300,5,RASIDI,RASIDI,3,M. RIDO SAPUTRA,,M15,Anak sekolah tidak mendapat MBG
13,5005453,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50054,001300,5,RASIDI,RASIDI,3,M. RIDO SAPUTRA,,M26,ART sedang bersekolah tetapi tidak menggunakan...
14,5010813,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,M. YASIR,M. YASIR,3,RINTANI YASIRA,,M6,Penduduk usia 45 tahun ke bawah tidak bisa bac...
15,5010813,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,M. YASIR,M. YASIR,3,RINTANI YASIRA,,M8,Penduduk usia di 7-18 tahun tetapi belum berse...
16,5010814,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,1,M. YASIR,M. YASIR,4,M. ALFARIZQI,,M15,Anak sekolah tidak mendapat MBG
17,5010821,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,2,SUHAIMI,SUHAIMI,1,SUHAIMI,,M25,ART bekerja tetapi tidak menguasai telpon selu...
18,5010832,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,3,ABDULLAH,ABDULLAH,2,MARDIANA,,M25,ART bekerja tetapi tidak menguasai telpon selu...
19,5010833,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,3,ABDULLAH,ABDULLAH,3,NILNA RUHAMA,,M15,Anak sekolah tidak mendapat MBG
20,5010844,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50108,000200,4,M. ANUARI,M. ANUARI,4,AISHWA NAHLA,,M30,"Cek kembali uraian lainnya (R1307=F), siapa ta..."
21,5011451,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50114,000801,5,RESTUONO,RESTUONO,1,RESTUONO,,M22,ART memiliki rekening tabungan (R701=1) tetapi...
22,5011452,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50114,000801,5,RESTUONO,RESTUONO,2,SITI JUMARIAH,,M22,ART memiliki rekening tabungan (R701=1) tetapi...
23,0117522,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,11,TUNGKAL I,2,01175,000900,2,JUMRI SARMAN,JUMRI SARMAN,2,MUNIRAH,,M25,ART bekerja tetapi tidak menguasai telpon selu...
24,5013721,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,15,SUNGAI NIBUNG,1,50137,000100,2,M. SARNUBI,M. SARNUBI,1,M. SARNUBI,,M24,Jam kerja seminggu terakhir dibawah 12 jam
25,5013722,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,15,SUNGAI NIBUNG,1,50137,000100,2,M. SARNUBI,M. SARNUBI,2,MARIANA,,M24,Jam kerja seminggu terakhir dibawah 12 jam
26,5013723,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,15,SUNGAI NIBUNG,1,50137,000100,2,M. SARNUBI,M. SARNUBI,3,ZAHRA AQILA RAMADHANI,,M13,Anak sekolah tidak pernah sarapan/makan pagi
27,5016391,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,16,SRIWIJAYA,1,50163,001300,9,MISRAN,MISRAN,1,MISRAN,NUR ALIFA DAPAT MBG,M25,ART bekerja tetapi tidak menguasai telpon selu...
28,5020681,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50206,000702,8,MULYADI,MULYADI,1,MULYADI,,M22,ART memiliki rekening tabungan (R701=1) tetapi...
29,5020683,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50206,000702,8,MULYADI,MULYADI,3,MUHAMMAD RIZKI RAMADHAN,,M15,Anak sekolah tidak mendapat MBG
30,5020684,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50206,000702,8,MULYADI,MULYADI,4,M. RIDHO,,M28,"Cek kembali uraian lainnya di R809I, siapa tau..."
31,5021323,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50213,001301,2,RUSLI,RUSLI,3,FARHAN SAIDINA MUHAMMAD,,M15,Anak sekolah tidak mendapat MBG
32,5021382,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,18,KAMPUNG NELAYAN,1,50213,001301,8,DONI ADNAN,,2,HARTINI,,M25,ART bekerja tetapi tidak menguasai telpon selu...
33,0129714,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,9,MEKAR TANJUNG,2,01297,000400,1,BEJO WIYONO,BEJO WIYONO,4,MUJIONO,,M25,ART bekerja tetapi tidak menguasai telpon selu...
34,0129751,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,9,MEKAR TANJUNG,2,01297,000400,5,BADRAN,BADRAN,1,BADRAN,,M25,ART bekerja tetapi tidak menguasai telpon selu...
35,0151253,7,TANJUNG JABUNG BARAT,40,BETARA,16,SUNGAI TERAP,2,01512,001000,5,USNAINI,USNAINI,3,JUNI AMANDA PUTRI,"PIP SMA, BLT, BOS SMA, SD, BPJS PBI",M26,ART sedang bersekolah tetapi tidak menggunakan...
36,0155121,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,3,BETARA KIRI,2,01551,000100,2,RIDWAN,RIDWAN,1,RIDWAN,,M25,ART bekerja tetapi tidak menguasai telpon selu...
37,0155123,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,3,BETARA KIRI,2,01551,000100,2,RIDWAN,RIDWAN,3,M. SALMAN,,M26,ART sedang bersekolah tetapi tidak menggunakan...
38,0155141,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,3,BETARA KIRI,2,01551,000100,4,ASIAH,ASIAH,1,ASIAH,ART 02 MEMBANTU IBUNYA DI WARUNG NASI,M25,ART bekerja tetapi tidak menguasai telpon selu...
39,0160111,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,7,TANJUNG PASIR,2,01601,001300,1,MASTANIAH,MASTANIAH,1,MASTANIAH,,M22,ART memiliki rekening tabungan (R701=1) tetapi...
40,0160111,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,7,TANJUNG PASIR,2,01601,001300,1,MASTANIAH,MASTANIAH,1,MASTANIAH,,M25,ART bekerja tetapi tidak menguasai telpon selu...

## Anomali VSEN25_Rumah Tangga

In [ ]:
#Anomali M17
cols_to_keep17=['ID_ruta','KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','M1409A','M1409B']
df_M17=df_kor_rt[cols_to_keep17]
df_M17["M17"]=np.where(((df_M17["M1409A"]==7) | (df_M17["M1409B"]==7)),"1","0")
df_M17["Keterangan"]=np.where(df_M17["M17"]=="1","(M1409A dan M1409B) Menjalankan ibadah atau menggunakan layanan kesehatan tidak relevan. Pastikan apakah sudah sesuai","")
df_anomali_vsenM_17=df_M17[df_M17["M17"]=="1"]
df_anomali_vsenM_17.to_excel("df_anomali_vsen_M_17.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_vsenM_17.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/17 Ibadah atau Layanan Kesehatan Tidak Relevan.xlsx', index=False)
df_anomali_vsenM_17

/tmp/ipython-input-2961275675.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M17["M17"]=np.where(((df_M17["M1409A"]==7) | (df_M17["M1409B"]==7)),"1","0")
/tmp/ipython-input-2961275675.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M17["Keterangan"]=np.where(df_M17["M17"]=="1","(M1409A dan M1409B) Menjalankan ibadah atau menggunakan layanan kesehatan tidak relevan. Pastikan apakah sudah sesuai","")

Empty DataFrame
Columns: [ID_ruta, KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, M1409A, M1409B, M17, Keterangan]
Index: []

In [ ]:
#Anomali M18
cols_to_keep18=['ID_ruta','KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','M1411A','M1411C']
df_M18=df_kor_rt[cols_to_keep18]
df_M18["M18"]=np.where(((df_M18["M1411A"]==7) | (df_M18["M1411C"]==7)),"1","0")
df_M18["Keterangan"]=np.where(df_M18["M18"]=="1","(M1411A dan M1411C) Kebiasaan membuang sampah tidak relevan (R1411A) atau kondisi jalan (R1411C) terisi titidak relevan ","")
df_anomali_vsenM_18=df_M18[df_M18["M18"]=="1"]
df_anomali_vsenM_18.to_excel("df_anomali_vsen_M_18.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_vsenM_18.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/18 Kebiasaan Buang Sampah dan Kondisi Jalan.xlsx', index=False)
df_anomali_vsenM_18

/tmp/ipython-input-1790263105.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M18["M18"]=np.where(((df_M18["M1411A"]==7) | (df_M18["M1411C"]==7)),"1","0")
/tmp/ipython-input-1790263105.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M18["Keterangan"]=np.where(df_M18["M18"]=="1","(M1411A dan M1411C) Kebiasaan membuang sampah tidak relevan (R1411A) atau kondisi jalan (R1411C) terisi titidak relevan ","")

Empty DataFrame
Columns: [ID_ruta, KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, M1411A, M1411C, M18, Keterangan]
Index: []

In [ ]:
#Anomali M19
cols_to_keep19=[ 'ID_ruta','KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','M1501','M1501_LAIN']
df_M19=df_kor_rt[cols_to_keep19]
df_M19["M19"]=np.where(((df_M19["M1501"]==5)),"1","0")
df_M19["Keterangan"]=np.where(df_M19["M19"]=="1","(R1501) Cek kembali uraian lainnya, siapa tau ada yg pas dengan kode yg sdh ada di kues","")
df_anomali_vsenM_19=df_M19[df_M19["M19"]=="1"]
df_anomali_vsenM_19.to_excel("df_anomali_vsen_M_19.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_vsenM_19.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/19 Cek Isian Lainnya di R1501.xlsx', index=False)
df_anomali_vsenM_19

/tmp/ipython-input-1721782163.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M19["M19"]=np.where(((df_M19["M1501"]==5)),"1","0")
/tmp/ipython-input-1721782163.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M19["Keterangan"]=np.where(df_M19["M19"]=="1","(R1501) Cek kembali uraian lainnya, siapa tau ada yg pas dengan kode yg sdh ada di kues","")

Empty DataFrame
Columns: [ID_ruta, KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, M1501, M1501_LAIN, M19, Keterangan]
Index: []

In [ ]:
#Anomali M20
cols_to_keep20=['ID_ruta','KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','M1502A','M1502A_LAI']
df_M20=df_kor_rt[cols_to_keep20]
df_M20["M20"]=np.where(((df_M20["M1502A"]==4)),"1","0")
df_M20["Keterangan"]=np.where(df_M20["M20"]=="1","(M1502A) Cek kembali uraian lainnya, siapa tau ada yg pas dengan kode yg sdh ada di kues","")
df_anomali_vsenM_20=df_M20[df_M20["M20"]=="1"]
df_anomali_vsenM_20.to_excel("df_anomali_vsen_M_20.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_vsenM_20.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/20 Cek Isian Lainnya di R1502A.xlsx', index=False)
df_anomali_vsenM_20

/tmp/ipython-input-3326954350.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M20["M20"]=np.where(((df_M20["M1502A"]==4)),"1","0")
/tmp/ipython-input-3326954350.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M20["Keterangan"]=np.where(df_M20["M20"]=="1","(M1502A) Cek kembali uraian lainnya, siapa tau ada yg pas dengan kode yg sdh ada di kues","")

,ID_ruta,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,M1502A,M1502A_LAI,M20,Keterangan
5,001758,7,TANJUNG JABUNG BARAT,11,MERLUNG,21,MERLUNG,2,00175,000900,8,2,FITRI ARIATI SIAGIAN,FITRI ARIATI SIAGIAN,4.0,WARISAN,1,"(M1502A) Cek kembali uraian lainnya, siapa tau..."
55,502968,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50296,001600,8,2,SYAHRONI,SYAHRONI / MUHAZIR,4.0,PUNYA ORANG TUA,1,"(M1502A) Cek kembali uraian lainnya, siapa tau..."
56,502969,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50296,001600,9,2,LIZA NOVIANTI,LIZA NOVIANTI,4.0,DARI ORANG TUA,1,"(M1502A) Cek kembali uraian lainnya, siapa tau..."

In [ ]:
#Anomali M21
cols_to_keep21=['ID_ruta', 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','M1502A','M1503']
df_M21=df_kor_rt[cols_to_keep21]
df_M21["M21"]=np.where(((df_M21["M1502A"]==1) & ((df_M21["M1503"]==2))),"1","0")
df_M21["Keterangan"]=np.where(df_M21["M21"]=="1","(M1502A dan M1503)Rumah dibeli dari Developer tadi tidak memiliki IMB/PBG/SLF","")
df_anomali_vsenM_21=df_M21[df_M21["M21"]=="1"]
df_anomali_vsenM_21.to_excel("df_anomali_vsen_M_21.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_vsenM_21.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/21 Beli dari Pengembang tapi tidak ada IMB-PBG-SLF.xlsx', index=False)
df_anomali_vsenM_21

/tmp/ipython-input-169443890.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M21["M21"]=np.where(((df_M21["M1502A"]==1) & ((df_M21["M1503"]==2))),"1","0")
/tmp/ipython-input-169443890.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M21["Keterangan"]=np.where(df_M21["M21"]=="1","(M1502A dan M1503)Rumah dibeli dari Developer tadi tidak memiliki IMB/PBG/SLF","")

Empty DataFrame
Columns: [ID_ruta, KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, M1502A, M1503, M21, Keterangan]
Index: []

In [ ]:
#Anomali M22
cols_to_keep22=[ 'ID_ruta','KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','M1503']
df_M22=df_kor_rt[cols_to_keep22]
df_M22["M22"]=np.where(((df_M22["M1503"]==3)),"1","0")
df_M22["Keterangan"]=np.where(df_M22["M22"]=="1","R1503 terisi tidak tahu","")
df_anomali_vsenM_22=df_M22[df_M22["M22"]=="1"]
df_anomali_vsenM_22.to_excel("df_anomali_vsen_M_22.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_vsenM_22.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/22 R1503 terisi tidak tahu.xlsx', index=False)
df_anomali_vsenM_22

/tmp/ipython-input-396981341.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M22["M22"]=np.where(((df_M22["M1503"]==3)),"1","0")
/tmp/ipython-input-396981341.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M22["Keterangan"]=np.where(df_M22["M22"]=="1","R1503 terisi tidak tahu","")

Empty DataFrame
Columns: [ID_ruta, KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, M1503, M22, Keterangan]
Index: []

In [ ]:
#Anomali M23
cols_to_keep23=[ 'ID_ruta','KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','M1502B']
df_M23=df_kor_rt[cols_to_keep23]
df_M23["M23"]=np.where(((df_M23["M1502B"]==4)),"1","0")
df_M23["Keterangan"]=np.where(df_M23["M23"]=="1","(M1502B) Cek kembali uraian lainnya, siapa tau ada yg pas dengan kode yg sdh ada di kues","")
df_anomali_vsenM_23=df_M23[df_M23["M23"]=="1"]
df_anomali_vsenM_23.to_excel("df_anomali_vsen_M_23.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_vsenM_23.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/23 Cek Isian Lainnya di R1502B.xlsx', index=False)
df_anomali_vsenM_23

/tmp/ipython-input-760049086.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M23["M23"]=np.where(((df_M23["M1502B"]==4)),"1","0")
/tmp/ipython-input-760049086.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M23["Keterangan"]=np.where(df_M23["M23"]=="1","(M1502B) Cek kembali uraian lainnya, siapa tau ada yg pas dengan kode yg sdh ada di kues","")

Empty DataFrame
Columns: [ID_ruta, KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, M1502B, M23, Keterangan]
Index: []

In [ ]:
#Anomali M24
cols_to_keep24=[ 'ID_ruta','KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','M1504']
df_M24=df_kor_rt[cols_to_keep24]
df_M24["M24"]=np.where(((df_M24["M1504"]>=3)),"1","0")
df_M24["Keterangan"]=np.where(df_M24["M24"]=="1","(M1504) Jenis Listrik yang digunakana Listrik non-PLN/Bukan Listrik","")
df_anomali_vsenM_24=df_M24[df_M24["M24"]=="1"]
df_anomali_vsenM_24.to_excel("df_anomali_vsen_M_24.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_vsenM_24.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/24 Jenis Listrik yang digunakan Listrik non-PLN-Bukan Listrik.xlsx', index=False)
df_anomali_vsenM_24

/tmp/ipython-input-2817391820.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M24["M24"]=np.where(((df_M24["M1504"]>=3)),"1","0")
/tmp/ipython-input-2817391820.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M24["Keterangan"]=np.where(df_M24["M24"]=="1","(M1504) Jenis Listrik yang digunakana Listrik non-PLN/Bukan Listrik","")

Empty DataFrame
Columns: [ID_ruta, KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, M1504, M24, Keterangan]
Index: []

In [ ]:
#Anomali M25
cols_to_keep25=[ 'ID_ruta','KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','M1602G']
df_M25=df_kor_rt[cols_to_keep25]
df_M25["M25"]=np.where(((df_M25["M1602G"]=="G")),"1","0")
df_M25["Keterangan"]=np.where(df_M25["M25"]=="1","(M1602G) Cek kembali uraian lainnya, siapa tau ada yg pas dengan kode yg sdh ada di kues","")
df_anomali_vsenM_25=df_M25[df_M25["M25"]=="1"]
df_anomali_vsenM_25.to_excel("df_anomali_vsen_M_25.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_vsenM_25.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/25 Cek Isian Lainnya di R1602G.xlsx', index=False)
df_anomali_vsenM_25

/tmp/ipython-input-3884293466.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M25["M25"]=np.where(((df_M25["M1602G"]=="G")),"1","0")
/tmp/ipython-input-3884293466.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M25["Keterangan"]=np.where(df_M25["M25"]=="1","(M1602G) Cek kembali uraian lainnya, siapa tau ada yg pas dengan kode yg sdh ada di kues","")

Empty DataFrame
Columns: [ID_ruta, KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, M1602G, M25, Keterangan]
Index: []

In [ ]:
#Anomali M26
cols_to_keep26=[ 'ID_ruta','KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','M1604A','M1604B','M1604C','M1604D','M1604E','M1604F']
df_M26=df_kor_rt[cols_to_keep26]
df_M26["M26"]=np.where(((df_M26["M1604A"]==8)|(df_M26["M1604B"]==8)|(df_M26["M1604C"]==8)|(df_M26["M1604D"]==8)|(df_M26["M1604E"]==8)|(df_M26["M1604F"]==8)),"1","0")
df_M26["Keterangan"]=np.where(df_M26["M26"]=="1","R1604 terisi tidak tahu","")
df_anomali_vsenM_26=df_M26[df_M26["M26"]=="1"]
df_anomali_vsenM_26.to_excel("df_anomali_vsen_M_26.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_vsenM_26.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/26 R1604 terisi tidak tahu.xlsx', index=False)
df_anomali_vsenM_26

/tmp/ipython-input-1631373060.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M26["M26"]=np.where(((df_M26["M1604A"]==8)|(df_M26["M1604B"]==8)|(df_M26["M1604C"]==8)|(df_M26["M1604D"]==8)|(df_M26["M1604E"]==8)|(df_M26["M1604F"]==8)),"1","0")
/tmp/ipython-input-1631373060.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M26["Keterangan"]=np.where(df_M26["M26"]=="1","R1604 terisi tidak tahu","")

,ID_ruta,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,...,NAMAKRTDSR,NAMAKRT,M1604A,M1604B,M1604C,M1604D,M1604E,M1604F,M26,Keterangan
15,501506,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,...,AFRIZAL TANJUNG,AFRIZAL TANJUNG,8.0,1.0,1.0,1.0,1.0,8.0,1,R1604 terisi tidak tahu
26,004724,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00472,000100,...,ISMA,ISMA,8.0,1.0,8.0,1.0,1.0,8.0,1,R1604 terisi tidak tahu
29,004746,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00474,000300,...,SLAMET WAHYUDI,SLAMET WAHYUDI,8.0,1.0,8.0,8.0,1.0,8.0,1,R1604 terisi tidak tahu
30,004726,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00472,000100,...,ARSA,ARSA,8.0,8.0,8.0,8.0,8.0,8.0,1,R1604 terisi tidak tahu
31,004727,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00472,000100,...,UJANG SUBANDI,UJANG SUBANDI,8.0,8.0,1.0,8.0,8.0,8.0,1,R1604 terisi tidak tahu
70,503687,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,...,RENDRA MONTI,RENDRA MONTI,1.0,1.0,1.0,1.0,1.0,8.0,1,R1604 terisi tidak tahu
72,503638,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50363,001800,...,ABD.WAHAB,ABD.WAHAB,1.0,1.0,5.0,1.0,1.0,8.0,1,R1604 terisi tidak tahu
73,503688,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,...,ERNA WATI,ERNA WATI,8.0,1.0,1.0,1.0,1.0,8.0,1,R1604 terisi tidak tahu
78,5036812,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,...,ACHMAD MARZUKI,ACHMAD MARZUKI,8.0,1.0,1.0,1.0,1.0,5.0,1,R1604 terisi tidak tahu
100,009791,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,...,M. AKHYAR,M. AKHYAR,8.0,1.0,8.0,8.0,1.0,8.0,1,R1604 terisi tidak tahu
104,009795,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,...,M. SAINI,M. SAINI,8.0,1.0,8.0,8.0,1.0,8.0,1,R1604 terisi tidak tahu
105,009796,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,...,DG. MANAMBUNG,DG. MANAMBUNG,8.0,1.0,1.0,1.0,1.0,1.0,1,R1604 terisi tidak tahu
108,009799,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,...,ABDUL GANI,ABDUL GANI,8.0,1.0,8.0,5.0,1.0,8.0,1,R1604 terisi tidak tahu
109,0097910,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,...,HABIBURRAHMAN,HABIBURRAHMAN,8.0,1.0,8.0,8.0,8.0,8.0,1,R1604 terisi tidak tahu
111,011582,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,...,BAHERUDDIN. S,BAHERUDDIN,8.0,8.0,8.0,8.0,8.0,8.0,1,R1604 terisi tidak tahu
112,011583,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,...,SUDIYONO,SUDIONO,5.0,1.0,8.0,5.0,1.0,8.0,1,R1604 terisi tidak tahu
116,011588,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,...,HAMIM YUSUF,HAMIM YUSUF,8.0,1.0,5.0,1.0,1.0,5.0,1,R1604 terisi tidak tahu
119,0115813,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,...,A. HAIRI,A. HAIRI,8.0,1.0,5.0,1.0,1.0,1.0,1,R1604 terisi tidak tahu
130,013771,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,...,MIMING,MIMING,8.0,1.0,5.0,8.0,1.0,8.0,1,R1604 terisi tidak tahu
131,013772,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,...,ACOK,ACOK,8.0,1.0,8.0,8.0,1.0,8.0,1,R1604 terisi tidak tahu
132,013773,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,...,M. TAHER,M. TAHER,8.0,1.0,8.0,8.0,1.0,8.0,1,R1604 terisi tidak tahu
133,013774,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,...,AGUS TUJIARTO,AGUS TUJIARTO,8.0,1.0,5.0,8.0,1.0,8.0,1,R1604 terisi tidak tahu
134,013775,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,...,AMIRUDDIN,AMIRUDDIN,8.0,1.0,8.0,8.0,1.0,8.0,1,R1604 terisi tidak tahu
135,013776,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,...,ARMAIN,ARMAIN,8.0,1.0,5.0,5.0,1.0,8.0,1,R1604 terisi tidak tahu
138,013779,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,...,IRWAN NUDIN,IRWAN NUDIN,8.0,1.0,5.0,5.0,1.0,5.0,1,R1604 terisi tidak tahu

In [ ]:
#Anomali M27
cols_to_keep27=[ 'ID_ruta','KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'SEMESTER', 'NAMAKRTDSR', 'NAMAKRT','M1504','M1606A']
df_M27=df_kor_rt[cols_to_keep27]
df_M27["M27"]=np.where(((df_M27["M1504"]<=3)&(df_M27["M1606A"]==7)),"1","0")
df_M27["Keterangan"]=np.where(df_M27["M27"]=="1","(M1504 dan M1606A) Rumah tangga menggunakan listrik sebagai sumber penerangan utama tapi Kebiasaan mematikan elektronik apabila tidak digunakan terisi tidak relevan","")
df_anomali_vsenM_27=df_M27[df_M27["M27"]=="1"]
df_anomali_vsenM_27.to_excel("df_anomali_vsen_M_27.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_vsenM_27.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/27 Kebiasaan Mematikan Alat Elektronik tidak relevan.xlsx', index=False)
df_anomali_vsenM_27

/tmp/ipython-input-4224841824.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M27["M27"]=np.where(((df_M27["M1504"]<=3)&(df_M27["M1606A"]==7)),"1","0")
/tmp/ipython-input-4224841824.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_M27["Keterangan"]=np.where(df_M27["M27"]=="1","(M1504 dan M1606A) Rumah tangga menggunakan listrik sebagai sumber penerangan utama tapi Kebiasaan mematikan elektronik apabila tidak digunakan terisi tidak relevan","")

Empty DataFrame
Columns: [ID_ruta, KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, M1504, M1606A, M27, Keterangan]
Index: []

In [ ]:
### GABUNGKAN SELURUH ANOMALI KONSISTENSI M ruta 1 FILE
import pandas as pd
from functools import reduce

### 01 Gabungkan Seluruh Kode Anomali dan Status Anomali dalam 1 Dataframe
df_M17_sel=df_M17[["ID_ruta","M17"]]
df_M18_sel=df_M18[["ID_ruta","M18"]]
df_M19_sel=df_M19[["ID_ruta","M19"]]
df_M20_sel=df_M20[["ID_ruta","M20"]]
df_M21_sel=df_M21[["ID_ruta","M21"]]
df_M22_sel=df_M22[["ID_ruta","M22"]]
df_M23_sel=df_M23[["ID_ruta","M23"]]
df_M24_sel=df_M24[["ID_ruta","M24"]]
df_M25_sel=df_M25[["ID_ruta","M25"]]
df_M26_sel=df_M26[["ID_ruta","M26"]]
df_M27_sel=df_M27[["ID_ruta","M27"]]
df_M_ruta_merged=[df_M17_sel,
df_M18_sel,
df_M19_sel,
df_M20_sel,
df_M21_sel,
df_M22_sel,
df_M23_sel,
df_M24_sel,
df_M25_sel,
df_M26_sel,
df_M27_sel]
df_M_ruta_merged_pivot = reduce(lambda left, right: pd.merge(left, right, on="ID_ruta", how="outer"), df_M_ruta_merged)
df_M_ruta_merged_pivot.head()

### 02 Import Dataframe yang berisikan keterangan Anomali
ket_anomali_M_ruta = pd.read_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/02 Keterangan Anomali M_Ruta.xlsx', engine="openpyxl")

### 03 Unpivot Dataframe yanng berisikan ID_ruta dengan Kode Anomali dan Status Anomali
df_Mruta_melted = pd.melt(
    df_M_ruta_merged_pivot,
    id_vars=["ID_ruta"],          # rows
    value_vars=['M17', 'M18', 'M19', 'M20', 'M21', 'M22', 'M23', 'M24', 'M25', 'M26', 'M27'],
    var_name="Kode Anomali",
    value_name="Status Anomali"
    )

### 03 Siapkan Dataframe yang berisikan Identitas seluruh Ruta Sampel SSN
cols_to_keep_df_kor_M_ruta=['ID_ruta', 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'NAMAKRTDSR', 'NAMAKRT','CATATAN']
df_Mruta_ID=df_kor_rt[cols_to_keep_df_kor_M_ruta]


### 04 Merge Dataframe yang berisikan Identitas seluruh Ruta Sampel SSN dengan Dataframe yang berisikan Status Anomali
df_M_ruta_full=pd.merge(df_Mruta_ID,df_Mruta_melted, on="ID_ruta", how="left")
df_M_ruta_full_anomali=df_M_ruta_full[df_M_ruta_full["Status Anomali"]=="1"]
df_M_ruta_full_anomali=df_M_ruta_full_anomali.drop(columns="Status Anomali")
df_M_ruta_full_anomali


### 06 Merge Dataframe yang berisikan keterangan Anomali dengan Dataframe yang berisikan Ruta-Ruta berdasarkan Anomali
dfM_ruta=pd.merge(df_M_ruta_full_anomali,ket_anomali_M_ruta, on="Kode Anomali", how="left")

### 07 Export Dataframe yang berisikan Ruta dengan anomali beserta keterangannya
dfM_ruta.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali/[01 Pengecekan Anomali VSEN25-M Rumah Tangga].xlsx', index=False)
dfM_ruta

,ID_ruta,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,NAMAKRTDSR,NAMAKRT,CATATAN,Kode Anomali,Keterangan
0,001758,7,TANJUNG JABUNG BARAT,11,MERLUNG,21,MERLUNG,2,00175,000900,8,FITRI ARIATI SIAGIAN,FITRI ARIATI SIAGIAN,R1502A:RUTA MENDAPATKAN RUMAH DARI WARISAN ORA...,M20,"Cek kembali uraian lainnya, siapa tau ada yg p..."
1,501506,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,6,AFRIZAL TANJUNG,AFRIZAL TANJUNG,BPNT DAPAT APRIL- JUNI 600. TV TIDAK ADA RUSAK...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
2,004724,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00472,000100,4,ISMA,ISMA,M1604 RESPONDEN SUDAH TUA DAN TIDAK TERLALU ME...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
3,004746,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00474,000300,6,SLAMET WAHYUDI,SLAMET WAHYUDI,R1209: ANAKNYA TIDAK SUKA NONTON FILM ATAU SIN...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
4,004726,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00472,000100,6,ARSA,ARSA,M1005-M1011 TERISI KODE SEMUA KARNA ART ARSA M...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
5,004727,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00472,000100,7,UJANG SUBANDI,UJANG SUBANDI,R1604 TERISI TIDAK TAHU KARNA RESPONDEN TIDAK ...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
6,502968,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50296,001600,8,SYAHRONI,SYAHRONI / MUHAZIR,BERGANTI KRT MENJADI MUHAZIR. R1502A RUMAH DI...,M20,"Cek kembali uraian lainnya, siapa tau ada yg p..."
7,502969,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,7,TUNGKAL HARAPAN,1,50296,001600,9,LIZA NOVIANTI,LIZA NOVIANTI,R.1501 1502 LAINNYA DIKASIH ORANG TUANYA WARIS...,M20,"Cek kembali uraian lainnya, siapa tau ada yg p..."
8,503687,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,7,RENDRA MONTI,RENDRA MONTI,RINCIA 502 SESUAI KONDISI LAPANGAN. R609 TERIS...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
9,503638,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50363,001800,8,ABD.WAHAB,ABD.WAHAB,R502 SUDAH SESUAI DENGAN KK RESPONDEN. R906 DA...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
10,503688,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,8,ERNA WATI,ERNA WATI,RINCIAN 502 SESUAI KONDISI LAPANGAN. R1604 RES...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
11,5036812,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,12,ACHMAD MARZUKI,ACHMAD MARZUKI,RESPONDEN INI TIDAK MENGETAHUI PERKEMBANGAN TE...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
12,009791,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,1,M. AKHYAR,M. AKHYAR,"R502 NIK SUDAH SESUAI, R903: IBU PERNAH BERCER...",M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
13,009795,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,5,M. SAINI,M. SAINI,"NIK SUDAH SESUAI, 1013: MENGIKUTI PROGRAM GEMA...",M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
14,009796,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,6,DG. MANAMBUNG,DG. MANAMBUNG,"NIK SUDAH SESUAI, R704=5: KARENA MENGURANGI PR...",M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
15,009799,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,9,ABDUL GANI,ABDUL GANI,R502 NIK SUDAH SESUAI DENGAN KARTU KELUARGA RE...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
16,0097910,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,10,HABIBURRAHMAN,HABIBURRAHMAN,RUTA PENERIMA BPJS PBI. M. ERWINSYAH MONDOK/ P...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
17,011582,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,2,BAHERUDDIN. S,BAHERUDDIN,NAMA KRT DIUBAH SESUAI DOKUMEN JADI BAHERUDDIN...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
18,011583,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,3,SUDIYONO,SUDIONO,NAMA KRT DIUBAH SESUAI DENGAN DOKUMEN JADI SUD...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
19,011588,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,8,HAMIM YUSUF,HAMIM YUSUF,SEBAGIAN RINCIAN 1604 TERISI TIDAK TAHU KARENA...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
20,0115813,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,13,A. HAIRI,A. HAIRI,BEBERAPA RINCIAN 1604 TERISI TIDAK TAHU KARENA...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
21,013771,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,1,MIMING,MIMING,RINCIAN 910 TERISI TIDAK RELEVAN UNTUK ART NO ...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
22,013772,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,2,ACOK,ACOK,TIDAK ADA ART YANG BERSEKOLAH HINGGA JENJANG S...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
23,013773,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,3,M. TAHER,M. TAHER,KEPALA RUMAH TANGGA A.N M TAHER SUDAH MENINGGA...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
24,013774,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,4,AGUS TUJIARTO,AGUS TUJIARTO,SEBAGIAN RINCIAN 1604 TERISI TIDAK TAHU KARENA...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
25,013775,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,5,AMIRUDDIN,AMIRUDDIN,MUHAMMAD HAFIZ MEMANG BELUM ADA BUAT NIK. ANAK...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
26,013776,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,6,ARMAIN,ARMAIN,SEBAGIAN RINCIAN 1604 TERISI TIDAK TAHU KARENA...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...
27,013779,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,9,IRWAN NUDIN,IRWAN NUDIN,AKHSAN IRAWAN BARU MASUK SD DAN SEBELUM NYA TI...,M26,R1604 terisi tidak tahu (1604A=8|1604B=8|1604C...

# **03 KONSISTENSI VSEN25.K DAN VSEN25.KP**

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 1
df_AMKP_01["AMKP01"]=np.where((df_AMKP_01["M403_8"]>0) & (df_AMKP_01["Gaji Pembantu (R304)"]==0),"1","0")
df_AMKP_01["Keterangan"]=np.where(df_AMKP_01["AMKP01"]=="1","Ruta mempunyai Pembantu Rumah Tangga sebanyak "+ df_AMKP_01["M403_8"].astype(str) + "maka pengeluaran untuk Gaji Pembantu/Sopir Harus terisi","")
df_anomali_AMKP_01=df_AMKP_01[df_AMKP_01["AMKP01"]=="1"]
df_anomali_AMKP_01

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M403_8, Gaji Pembantu (R304), AMKP01, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 2.1
df_AMKP_02_1["AMKP02_1"]=np.where((df_AMKP_02_1["R407_1"]>0) & (df_AMKP_02_1["Imunisasi (R288)"]) & (df_AMKP_02_1["Periksa Kehamilan (R287)"]==0),"1","0")
df_AMKP_02_1["Keterangan"]=np.where(df_AMKP_02_1["AMKP02_1"]=="1","Pengeluaran untuk Imunisasi (R288) harus terisi karna terdapat "+df_AMKP_02_1["R407_1"].astype(str)+" ART yang berusia 1 tahun","")
df_anomali_AMKP_02_1=df_AMKP_02_1[df_AMKP_02_1["AMKP02_1"]=="1"]
#df_anomali_AMKP_02_1.to_excel("df_anomali_Konsistensi_MdanKP_02_1.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
#df_anomali_AMKP_02_1.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/02_1 Konsistensi Pengeluaran Periksa Kehamilan dan Imunisasi untuk ART 1 Tahun.xlsx', index=False)
df_anomali_AMKP_02_1

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, R407_1, Periksa Kehamilan (R287), Imunisasi (R288), AMKP02_1, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 2.2
df_AMKP_02_2["AMKP02_2"]=np.where((df_AMKP_02_2["R407_1"]>0) & (df_AMKP_02_2["Biaya Untuk Pampers (R275)"]==0),"1","0")
df_AMKP_02_2["Keterangan"]=np.where(df_AMKP_02_2["AMKP02_2"]=="1","Pengeluaran untuk Pampers (R275) harus terisi karna terdapat "+ df_AMKP_02_2["R407_1"].astype(str) +" ART yang berusia 1 tahun","")
df_anomali_AMKP_02_2=df_AMKP_02_2[df_AMKP_02_2["AMKP02_2"]=="1"]
#df_anomali_AMKP_02_2.to_excel("df_anomali_Konsistensi_MdanKP_02_2.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
#df_anomali_AMKP_02_2.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/02_2 Konsistensi Pengeluaran Pampers untuk ART 1 Tahun.xlsx', index=False)
df_anomali_AMKP_02_2

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, R407_1, Biaya Untuk Pampers (R275), AMKP02_2, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 2.3
df_AMKP_02_3["AMKP02_3"]=np.where((df_AMKP_02_3["R407_1"]>0) & (df_AMKP_02_3["Biaya Untuk Susu Bubuk Bayi (R82)"]==0),"1","0")
df_AMKP_02_3["Keterangan"]=np.where(df_AMKP_02_3["AMKP02_3"]=="1","Pengeluaran untuk Susu Bubuk Bayi (R82) harus terisi karena terdapat "+df_AMKP_02_3["R407_1"].astype(str)+" ART yang berusia 1 tahun","")
df_anomali_AMKP_02_3=df_AMKP_02_3[df_AMKP_02_3["AMKP02_3"]=="1"]
#df_anomali_AMKP_02_3.to_excel("df_anomali_Konsistensi_MdanKP_02_3.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
#df_anomali_AMKP_02_3.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/02_3 Konsistensi Pengeluaran Susu Bubuk Bayi untuk ART 1 Tahun.xlsx', index=False)
df_anomali_AMKP_02_3

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, R407_1, Biaya Untuk Susu Bubuk Bayi (R82), AMKP02_3, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 2.4
df_AMKP_02_4["BiayaKes"]=df_AMKP_02_4[276]+df_AMKP_02_4[277]+df_AMKP_02_4[278]+df_AMKP_02_4[279]+df_AMKP_02_4[280]+df_AMKP_02_4[281]+df_AMKP_02_4[282]
df_AMKP_02_4["AMKP02_4"]=np.where((df_AMKP_02_4["R407_1"]>0) & (df_AMKP_02_4["BiayaKes"]==0),"1","0")
df_AMKP_02_4["Keterangan"]=np.where(df_AMKP_02_4["AMKP02_4"]=="1","Pengeluaran untuk Rawat inap ketika melahirkan harus terisi (R276-282) sesuai tempat dimana bayi tsb dilahirkan karena terdapat "+ df_AMKP_02_4["R407_1"].astype(str)+" ART yang berusia 1 tahun","")
df_anomali_AMKP_02_4=df_AMKP_02_4[df_AMKP_02_4["AMKP02_4"]=="1"]
df_anomali_AMKP_02_4.to_excel("df_anomali_Konsistensi_MdanKP_02_4.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_02_4.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/02_4 Konsistensi Biaya Kelahiran untuk ART 1 Tahun.xlsx', index=False)
df_anomali_AMKP_02_4

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M407_1, 276, 277, 278, 279, 280, 281, 282, BiayaKes, AMKP02_4, Keterangan]
Index: []

[0 rows x 25 columns]

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 3
df_AMKP_03["AMKP03"]=np.where((df_AMKP_03["R407_f15_tahun_Keatas"]>0) & (df_AMKP_03["Biaya Untuk Barang Kecantikan dan Pembalut (R270)"]==0),"1","0")
df_AMKP_03["Keterangan"]=np.where(df_AMKP_03["AMKP03"]=="1","Periksa kembali pengeluaran untuk barang kecantikan dan pembalut (r270) yang tidak terisi","")
df_anomali_AMKP_03=df_AMKP_03[df_AMKP_03["AMKP03"]=="1"]
df_anomali_AMKP_03.to_excel("df_anomali_Konsistensi_MdanKP_03.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_03.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/03 Konsistensi Pengeluaran Barang Kecantikan dan Pembalut untuk ART Perempuan 15 Tahun keatas.xlsx', index=False)
df_anomali_AMKP_03

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M407_f15_tahun_Keatas, Biaya Untuk Barang Kecantikan dan Pembalut (R270), AMKP03, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 4
df_AMKP_04["BiayaPendidikan"]=df_AMKP_04["Uang Pangkal (R292)"]+df_AMKP_04["Uang Sekolah (R293)"]+df_AMKP_04["Iuran sekolah lainnya (R294)"]+df_AMKP_04["Buku pelajaran (R295)"]+df_AMKP_04["Alat-alat tulis (R296)"]+df_AMKP_04["Uang Bimbel (R297)"]
df_AMKP_04["AMKP04"]=np.where((df_AMKP_04["M503_2"]>0) & (df_AMKP_04["BiayaPendidikan"]==0),"1","0")
df_AMKP_04["Keterangan"]=np.where(df_AMKP_04["AMKP04"]=="1","Pengeluaran untuk biaya Sekolah (r292-r297) harus terisi minimal sebesar biaya M1118O yang dibayarkan selama setahun terakhir","")
df_anomali_AMKP_04=df_AMKP_04[df_AMKP_04["AMKP04"]=="1"]
df_anomali_AMKP_04.to_excel("df_anomali_Konsistensi_MdanKP_04.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_04.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/04 Konsistensi Biaya Pendidikan untuk ART sekolah.xlsx', index=False)
df_anomali_AMKP_04

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M503_2, Uang Pangkal (R292), Uang Sekolah (R293), Iuran sekolah lainnya (R294), Buku pelajaran (R295), Alat-alat tulis (R296), Uang Bimbel (R297), BiayaPendidikan, AMKP04, Keterangan]
Index: []

[0 rows x 24 columns]

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 4_1
df_AMKP_041["AMKP041"]=np.where((df_AMKP_041["M503_2"]>0) & (df_AMKP_041["Bantuan dari Pemerintah (BLOK_VE_R1B_KOL_3)"]==0),"1","0")
df_AMKP_041["Keterangan"]=np.where(df_AMKP_041["AMKP041"]=="1","Biaya Bantuan Pemerintah dalam bentuk barang sekolah (BOS) Harus Terisi sebagai penerimaan Transfer di Rincian 1b Kol 3 Blok VE","")
df_anomali_AMKP_041=df_AMKP_041[df_AMKP_041["AMKP041"]=="1"]
df_anomali_AMKP_041.to_excel("df_anomali_Konsistensi_MdanKP_041.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_041.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/04_1 Konsistensi Transfer dari Pemerintah untuk ART sekolah.xlsx', index=False)
df_anomali_AMKP_041

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,M503_2,Bantuan dari Pemerintah (BLOK_VE_R1B_KOL_3),AMKP041,Keterangan
29,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00474,000300,6,2,SLAMET WAHYUDI,SLAMET WAHYUDI,004746,1,0.0,1,Biaya Bantuan Pemerintah dalam bentuk barang s...
32,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00474,000300,7,2,SUNGKONO,SUNGKONO,004747,1,0.0,1,Biaya Bantuan Pemerintah dalam bentuk barang s...
33,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00474,000300,8,2,ABDUL GHOFUR,ABDUL GHOFUR,004748,1,0.0,1,Biaya Bantuan Pemerintah dalam bentuk barang s...
37,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00474,000300,10,2,MAHFUD RIDHO ANSHORI,MAHFUD RIDHO ANSHORI,0047410,2,0.0,1,Biaya Bantuan Pemerintah dalam bentuk barang s...
41,7,TANJUNG JABUNG BARAT,20,PENGABUAN,7,PARIT PUDIN,2,00661,001300,2,2,SAMSUL BAHRI,SAMSUL BAHRI,006612,1,0.0,1,Biaya Bantuan Pemerintah dalam bentuk barang s...
43,7,TANJUNG JABUNG BARAT,20,PENGABUAN,7,PARIT PUDIN,2,00661,001300,4,2,DARMADI,DARMADI,006614,2,0.0,1,Biaya Bantuan Pemerintah dalam bentuk barang s...
47,7,TANJUNG JABUNG BARAT,20,PENGABUAN,7,PARIT PUDIN,2,00661,001300,8,2,SAHIDIN,SAHIDIN,006618,1,0.0,1,Biaya Bantuan Pemerintah dalam bentuk barang s...
49,7,TANJUNG JABUNG BARAT,20,PENGABUAN,7,PARIT PUDIN,2,00661,001300,13,2,NUR ASIAH,SYAHRUNI,0066113,2,0.0,1,Biaya Bantuan Pemerintah dalam bentuk barang s...
104,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,5,2,M. SAINI,M. SAINI,009795,1,0.0,1,Biaya Bantuan Pemerintah dalam bentuk barang s...
130,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,1,2,MIMING,MIMING,013771,1,0.0,1,Biaya Bantuan Pemerintah dalam bentuk barang s...

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 5
df_AMKP_05["BiayaBerobatSendiri"]=df_AMKP_05["Obat modern(R284)"]+df_AMKP_05["Obat tradisional-jamu(R285)"]
df_AMKP_05["AMKP05"]=np.where((df_AMKP_05["Mengobati_Sendiri_M603_1"]>0) & (df_AMKP_05["BiayaBerobatSendiri"]==0),"1","0")
df_AMKP_05["Keterangan"]=np.where(df_AMKP_05["AMKP05"]=="1","Obat yang dibeli tanpa resep tenaga kesehatan atau obat/tradisional/jamu untuk pengobatan harus terisi","")
df_anomali_AMKP_05=df_AMKP_05[df_AMKP_05["AMKP05"]=="1"]
df_anomali_AMKP_05.to_excel("df_anomali_Konsistensi_MdanKP_05.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_05.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/05 Konsistensi Biaya Berobat Mandiri untuk ART yang pernah mengobati sendiri.xlsx', index=False)
df_anomali_AMKP_05

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, Mengobati_Sendiri_M603_1, Obat modern(R284), Obat tradisional-jamu(R285), BiayaBerobatSendiri, AMKP05, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 6
df_AMKP_06["TotalBiayaRawatJalanInap"]=df_AMKP_06["Rumah sakit pemerintah (R276)"]+df_AMKP_06["Rumah sakit Swasta(R277)"]+df_AMKP_06["Rumah sakit Swasta(R277)"]+df_AMKP_06["Puskesmas-Pustu-polindes-posyandu(R278)"]+df_AMKP_06["Praktik Dokter-Poliklinik (R279)"]+df_AMKP_06["Praktik Petugas kesehatan(R280)"]+df_AMKP_06["Pengobatan Tradisional(R281)"]+df_AMKP_06["Dukun bersalin(R282)"]
df_AMKP_06["AMKP06"]=np.where((df_AMKP_06["RawatJalanInap_M604_1"]>0) & (df_AMKP_06["TotalBiayaRawatJalanInap"]==0),"1","0")
df_AMKP_06["Keterangan"]=np.where(df_AMKP_06["AMKP06"]=="1","Biaya pelayanan pengobatan/kuratif harus terisi","")
df_anomali_AMKP_06=df_AMKP_06[df_AMKP_06["AMKP06"]=="1"]
df_anomali_AMKP_06.to_excel("df_anomali_Konsistensi_MdanKP_06.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_06.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/06 Konsistensi Biaya Berobat Rawat Jalan untuk ART yang Rawat Jalan-Inap.xlsx', index=False)
df_anomali_AMKP_06

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,...,Rumah sakit pemerintah (R276),Rumah sakit Swasta(R277),Puskesmas-Pustu-polindes-posyandu(R278),Praktik Dokter-Poliklinik (R279),Praktik Petugas kesehatan(R280),Pengobatan Tradisional(R281),Dukun bersalin(R282),TotalBiayaRawatJalanInap,AMKP06,Keterangan
120,7,TANJUNG JABUNG BARAT,40,BETARA,16,SUNGAI TERAP,2,01262,000500,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,Biaya pelayanan pengobatan/kuratif harus terisi

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 8
df_AMKP_08["Total_Biaya_Angkutan_Umum"]=df_AMKP_08[298]+df_AMKP_08[299]+df_AMKP_08[300]
df_AMKP_08["AMKP08"]=np.where((df_AMKP_08["AngkutanUmum_M608"]>0) & (df_AMKP_08["Total_Biaya_Angkutan_Umum"]==0),"1","0")
df_AMKP_08["Keterangan"]=np.where(df_AMKP_08["AMKP08"]=="1","Biaya transportasi darat, udara/pesawat, laut/kapal feri, kapal laut harus terisi","")
df_anomali_AMKP_08=df_AMKP_08[df_AMKP_08["AMKP08"]=="1"]
df_anomali_AMKP_08.to_excel("df_anomali_Konsistensi_MdanKP_08.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_08.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/08 Konsistensi Biaya Angkutan Umum untuk ART yg pakai angkutan umum.xlsx', index=False)
df_anomali_AMKP_08

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, AngkutanUmum_M608, 298, 299, 300, Total_Biaya_Angkutan_Umum, AMKP08, Keterangan]
Index: []

[0 rows x 21 columns]

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 9
df_AMKP_09["Total_Biaya_Makanan_Pokok"]=df_AMKP_09["Padi-Padian(1)"]+df_AMKP_09["Umbi-Umbian(8)"]
df_AMKP_09["AMKP09"]=np.where(((df_AMKP_09["M702_1"]>0) & (df_AMKP_09["Total_Biaya_Makanan_Pokok"]==0)|(df_AMKP_09["M702_1"]==0) & (df_AMKP_09["Total_Biaya_Makanan_Pokok"]>0)),"1","0")
df_AMKP_09["Keterangan"]=np.where(df_AMKP_09["AMKP09"]=="1","Tidak Konsisten antara ART yang mengkonsumsi makanan pokok (M702) dengan Konsumsi dan pengeluaran bahan makanan padi-padian dan umbi-umbian di VSEN25.KP","")
df_anomali_AMKP_09=df_AMKP_09[df_AMKP_09["AMKP09"]=="1"]
df_anomali_AMKP_09.to_excel("df_anomali_Konsistensi_MdanKP_09.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_09.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/09 Konsistensi Pengeluaran Bahan Makanan Karbohidrat untuk ART yg konsumsi makanan pokok.xlsx', index=False)
df_anomali_AMKP_09

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,M702_1,Padi-Padian(1),Umbi-Umbian(8),Total_Biaya_Makanan_Pokok,AMKP09,Keterangan
117,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,9,2,MULYADI,MULYADI,011589,1,0.0,0.0,0.0,1,Tidak Konsisten antara ART yang mengkonsumsi m...

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 10
df_AMKP_10["AMKP10"]=np.where(((df_AMKP_10["M704_1"]>0) & (df_AMKP_10["Kacang-Kacangan(R121)"]==0)|(df_AMKP_10["M704_1"]==0) & (df_AMKP_10["Kacang-Kacangan(R121)"]>0)),"1","0")
df_AMKP_10["Keterangan"]=np.where(df_AMKP_10["AMKP10"]=="1","Tidak konsisten antara ART yang mengkonsumsi protein nabati dengan konsumsi dan pengeluaran kacang-kacangan di VSEN25.KP","")
df_anomali_AMKP_10=df_AMKP_10[df_AMKP_10["AMKP10"]=="1"]
df_anomali_AMKP_10.to_excel("df_anomali_Konsistensi_MdanKP_10.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_10.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/10 Konsistensi Pengeluaran Bahan Makanan Kacang-kacangan untuk ART yg konsumsi lauk pauk nabati.xlsx', index=False)
df_anomali_AMKP_10

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M704_1, Kacang-Kacangan(R121), AMKP10, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 11
df_AMKP_11["AMKP11"]=np.where(((df_AMKP_11["M705_1"]>0) & (df_AMKP_11["Ikan-Udang-Cumi-Kerang(R16)"]==0)& (df_AMKP_11["Daging(R61)"]==0)& (df_AMKP_11["Telur dan Susu (R74)"]==0)|(df_AMKP_11["M705_1"]==0) & ((df_AMKP_11["Ikan-Udang-Cumi-Kerang(R16)"]>0)|(df_AMKP_11["Daging(R61)"]>0)| (df_AMKP_11["Telur dan Susu (R74)"]>0))),"1","0")
df_AMKP_11["Keterangan"]=np.where(df_AMKP_11["AMKP11"]=="1","Tidak konsisten antara ART yang konsumsi protein hewani dan Konsumsi ikan/udang/cumi/kerang, daging, dan telur di VSEN25.KP","")
df_anomali_AMKP_11=df_AMKP_11[df_AMKP_11["AMKP11"]=="1"]
df_anomali_AMKP_11.to_excel("df_anomali_Konsistensi_MdanKP_11.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_11.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/11 Konsistensi Pengeluaran Bahan Ikan-Daging-Telur untuk ART yg konsumsi protein hewani.xlsx', index=False)
df_anomali_AMKP_11

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M705_1, Ikan-Udang-Cumi-Kerang(R16), Daging(R61), Telur dan Susu (R74), AMKP11, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 12
df_AMKP_12["AMKP12"]=np.where(((df_AMKP_12["Internet_M1014"]>0) & (df_AMKP_12["Biaya Internet(R266)"]==0)|(df_AMKP_12["Internet_M1014"]==0) & (df_AMKP_12["Biaya Internet(R266)"]>0)),"1","0")
df_AMKP_12["Keterangan"]=np.where(df_AMKP_12["AMKP12"]=="1","Tidak konsisten antara ART yang menggunakan internet (M1014) dengan Pengeluaran untuk Internet di VSEN25.KP","")
df_anomali_AMKP_12=df_AMKP_12[df_AMKP_12["AMKP12"]=="1"]
df_anomali_AMKP_12.to_excel("df_anomali_Konsistensi_MdanKP_12.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_12.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/12 Konsistensi Pengeluaran Internet untuk ART yg pakai Internet.xlsx', index=False)
df_anomali_AMKP_12

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, Internet_M1014, Biaya Internet(R266), AMKP12, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 13
df_AMKP_13["AMKP13"]=np.where((df_AMKP_13["Hamil_M1012"]>0) & (df_AMKP_13["Biaya Periksa Kehamilan(R287)"]==0),"1","0")
df_AMKP_13["Keterangan"]=np.where(df_AMKP_13["AMKP13"]=="1","Biaya pemeriksaan kehamilan harus terisi","")
df_anomali_AMKP_13=df_AMKP_13[df_AMKP_13["AMKP13"]=="1"]
df_anomali_AMKP_13.to_excel("df_anomali_Konsistensi_MdanKP_13.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_13.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/13 Konsistensi Pengeluaran Pemeriksaan Kehamilan untuk ART yg sedang hamil.xlsx', index=False)
df_anomali_AMKP_13

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, Hamil_M1012, Biaya Periksa Kehamilan(R287), AMKP13, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 14
df_AMKP_14["AMKP14"]=np.where((((df_AMKP_14["M1117A"]=="A") | (df_AMKP_14["M1117B"]=="B") |(df_AMKP_14["M1117C"]=="C"))&(df_AMKP_14["Bantuan dari Pemerintah (BLOK_VE_R1B_KOL_3)"]==0)),"1","0")
df_AMKP_14["Keterangan"]=np.where(df_AMKP_14["AMKP14"]=="1","Penerimaan Transfer dari Pemerintah Harus terisi untuk ART yang mendapatkan beasiswa","")
df_anomali_AMKP_14=df_AMKP_14[df_AMKP_14["AMKP14"]=="1"]
df_anomali_AMKP_14.to_excel("df_anomali_Konsistensi_MdanKP_14.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_14.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/14 Konsistensi Penerimaan Transfer Pemerintah untuk ART yg dapat beasiswa.xlsx', index=False)
df_anomali_AMKP_14

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M1117A, M1117B, M1117C, Bantuan dari Pemerintah (BLOK_VE_R1B_KOL_3), AMKP14, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 15
df_AMKP_15["Total_transfer"]=df_AMKP_15["Bantuan uang dari Badan Usaha (Blok 5E Rincian 2 Kol 2)"]+df_AMKP_15["Bantuan Barang/jasa dari Badan Usaha (Blok 5E Rincian 2 Kol 3)"]+df_AMKP_15["Bantuan uang dari Lembaga Nirlaba (Blok 5E Rincian 4 Kol 2)"]+df_AMKP_15["Bantuan Barang/jasa dari Lembaga Nirlaba (Blok 5E Rincian 4 Kol 3)"]
df_AMKP_15["AMKP15"]=np.where(((df_AMKP_15["M1117D"]>0)|(df_AMKP_15["M1117E"]>0))&(df_AMKP_15["Total_transfer"]==0),"1","0")
df_AMKP_15["Keterangan"]=np.where(df_AMKP_15["AMKP15"]=="1","Penerimaan Transfer dari badan usaha atau lembaga nirlaba Harus terisi untuk ART yang mendapatkan beasiswa nonpemerintah","")
df_anomali_AMKP_15=df_AMKP_15[df_AMKP_15["AMKP15"]=="1"]
df_anomali_AMKP_15.to_excel("df_anomali_Konsistensi_MdanKP_15.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_15.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/15 Konsistensi Penerimaan Transfer Non Pemerintah untuk ART yg dapat beasiswa.xlsx', index=False)
df_anomali_AMKP_15

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,...,ID_ruta,M1117D,M1117E,Bantuan uang dari Badan Usaha (Blok 5E Rincian 2 Kol 2),Bantuan Barang/jasa dari Badan Usaha (Blok 5E Rincian 2 Kol 3),Bantuan uang dari Lembaga Nirlaba (Blok 5E Rincian 4 Kol 2),Bantuan Barang/jasa dari Lembaga Nirlaba (Blok 5E Rincian 4 Kol 3),Total_transfer,AMKP15,Keterangan
102,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,3,...,009793,0,1,0.0,0.0,0.0,0.0,0.0,1,Penerimaan Transfer dari badan usaha atau lemb...

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 16
df_AMKP_16["AMKP16"]=np.where((df_AMKP_16["UangPendaftaran_1118a"]>0) & (df_AMKP_16["Biaya Sumbangan Sekolah(R292)"]==0),"1","0")
df_AMKP_16["Keterangan"]=np.where(df_AMKP_16["AMKP16"]=="1","Pengeluaran sumbangan pembangunan sekolah harus terisi","")
df_anomali_AMKP_16=df_AMKP_16[df_AMKP_16["AMKP16"]=="1"]
df_anomali_AMKP_16.to_excel("df_anomali_Konsistensi_MdanKP_16.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_16.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/16 Konsistensi Pengeluaran Sumbangan Pembangunan untuk ART yg bayar uang pendaftaran.xlsx', index=False)
df_anomali_AMKP_16

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,UangPendaftaran_1118a,Biaya Sumbangan Sekolah(R292),AMKP16,Keterangan
12,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,3,2,SYAMSUL PALAMANI,SYAMSUL PALAMANI,501503,1,0.0,1,Pengeluaran sumbangan pembangunan sekolah haru...
14,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,5,2,MISPAN,MISPAN,501505,1,0.0,1,Pengeluaran sumbangan pembangunan sekolah haru...
15,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,6,2,AFRIZAL TANJUNG,AFRIZAL TANJUNG,501506,1,0.0,1,Pengeluaran sumbangan pembangunan sekolah haru...
18,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,10,2,MUSA LASTIAR HUTAGALUNG,MUSA LASTIAR HUTAGALUNG,5015010,1,0.0,1,Pengeluaran sumbangan pembangunan sekolah haru...
70,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,7,2,RENDRA MONTI,RENDRA MONTI,503687,1,0.0,1,Pengeluaran sumbangan pembangunan sekolah haru...
78,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,12,2,ACHMAD MARZUKI,ACHMAD MARZUKI,5036812,1,0.0,1,Pengeluaran sumbangan pembangunan sekolah haru...
137,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,8,2,BAHRAN,BAHRAN,013778,1,0.0,1,Pengeluaran sumbangan pembangunan sekolah haru...

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 17
df_AMKP_17["AMKP17"]=np.where(((df_AMKP_17["M1118B"]>0)|(df_AMKP_17["M1118C"]>0)) & (df_AMKP_17["Biaya uang sekolah dan Komite (R293)"]==0),"1","0")
df_AMKP_17["Keterangan"]=np.where(df_AMKP_17["AMKP17"]=="1","Pengeluaran uang sekolah (SPP/UKT) dan iuran komite sekolah/POMG harus terisi karena (M118B) terisi "+df_AMKP_17["M1118B"].astype(str) +" dan (M118C) sebesar " + df_AMKP_17["M1118C"].astype(str),"")
df_anomali_AMKP_17=df_AMKP_17[df_AMKP_17["AMKP17"]=="1"]
df_anomali_AMKP_17.to_excel("df_anomali_Konsistensi_MdanKP_17.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_17.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/17 Konsistensi Pengeluaran uang sekolah dan komite untuk ART yg Sekolah dan bayar uang sekolah.xlsx', index=False)
df_anomali_AMKP_17

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M1118B, M1118C, Biaya uang sekolah dan Komite (R293), AMKP17, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 18
df_AMKP_18["AMKP18"]=np.where((df_AMKP_18["M1118E"]>0) & (df_AMKP_18["Pengeluaran Buku Pelajaran (R295)"]==0),"1","0")
df_AMKP_18["Keterangan"]=np.where(df_AMKP_18["AMKP18"]=="1"," (VSEN25.KP R295) Pengeluaran buku pelajaran, fotocopy bahan pelajaran harus terisi karena (M1118E) terisi sebesar " +df_AMKP_18["M1118E"].astype(str),"")
df_anomali_AMKP_18=df_AMKP_18[df_AMKP_18["AMKP18"]=="1"]
df_anomali_AMKP_18.to_excel("df_anomali_Konsistensi_MdanKP_18.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_18.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/18 Konsistensi Pengeluaran Buku Pelajaran untuk ART yg bayar beli LKS.xlsx', index=False)
df_anomali_AMKP_18

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M1118E, Pengeluaran Buku Pelajaran (R295), AMKP18, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 19
df_AMKP_19["Total_Biaya_Seragam"]=df_AMKP_19[310]+df_AMKP_19[313]+df_AMKP_19[314]+df_AMKP_19[315]
df_AMKP_19["AMKP19"]=np.where((df_AMKP_19["M1118D"]>0) & (df_AMKP_19["Total_Biaya_Seragam"]==0),"1","0")
df_AMKP_19["Keterangan"]=np.where(df_AMKP_19["AMKP19"]=="1","(VSEN25.KP R310-315) Pengeluaran pakaian jadi untuk anak-anak, alas kaki, tutup kepala untuk anak-anak, lainnya harus ada yang terisi karna (M1118D) terisi sebesar " + df_AMKP_19["M1118D"].astype(str),"")
df_anomali_AMKP_19=df_AMKP_19[df_AMKP_19["AMKP19"]=="1"]
df_anomali_AMKP_19.to_excel("df_anomali_Konsistensi_MdanKP_19.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_19.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/19 Konsistensi Pengeluaran Pakaian untuk ART yg beli baju seragam.xlsx', index=False)
df_anomali_AMKP_19

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M1118D, 310, 313, 314, 315, Total_Biaya_Seragam, AMKP19, Keterangan]
Index: []

[0 rows x 22 columns]

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 20
df_AMKP_20["Total_ART_yang_Membayar_Iuran_Sekolah_lainnya"]=df_AMKP_20["M1118G"]+df_AMKP_20["M1118H"]+df_AMKP_20["M1118J"]+df_AMKP_20["M1118L"]+df_AMKP_20["M1118M"]
df_AMKP_20["AMKP20"]=np.where((df_AMKP_20["Total_ART_yang_Membayar_Iuran_Sekolah_lainnya"]>0) & (df_AMKP_20["Biaya uang iuran sekolah lainnya (R294)"]==0),"1","0")
df_AMKP_20["Keterangan"]=np.where(df_AMKP_20["AMKP20"]=="1","(VSEN25.KP R294) Pengeluaran iuran sekolah lainnya harus terisi karna total biaya sekolah lainnya (M1118G,M1118H,M1118J,M1118L,M1118M) terisi sebesar "+ df_AMKP_20["Total_ART_yang_Membayar_Iuran_Sekolah_lainnya"].astype(str) +" " ,"")
df_anomali_AMKP_20=df_AMKP_20[df_AMKP_20["AMKP20"]=="1"]
df_anomali_AMKP_20.to_excel("df_anomali_Konsistensi_MdanKP_20.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_20.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/20 Konsistensi Pengeluaran Iuran Lainnya untuk ART yg bersekolah.xlsx', index=False)
df_anomali_AMKP_20.head()

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,...,ID_ruta,M1118G,M1118H,M1118J,M1118L,M1118M,Biaya uang iuran sekolah lainnya (R294),Total_ART_yang_Membayar_Iuran_Sekolah_lainnya,AMKP20,Keterangan
63,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50363,001800,3,...,503633,20000.0,0.0,0.0,0.0,0.0,0.0,20000.0,1,(VSEN25.KP R294) Pengeluaran iuran sekolah lai...

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 21
df_AMKP_21["AMKP21"]=np.where((df_AMKP_21["M1118I"]>0) & (df_AMKP_21["Pengeluaran Untuk Bimbel (R297)"]==0),"1","0")
df_AMKP_21["Keterangan"]=np.where(df_AMKP_21["AMKP21"]=="1","(VSEN25.KP R297) Pengeluaran uang kursus/bimbingan belajar di luar sekolah harus terisi karena (M1118I) terisi sebesar "+df_AMKP_21["M1118I"].astype(str),"")
df_anomali_AMKP_21=df_AMKP_21[df_AMKP_21["AMKP21"]=="1"]
df_anomali_AMKP_21.to_excel("df_anomali_Konsistensi_MdanKP_21.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_21.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/21 Konsistensi Pengeluaran Kursus untuk ART yg ikut Bimbel.xlsx', index=False)
df_anomali_AMKP_21

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M1118I, Pengeluaran Untuk Bimbel (R297), AMKP21, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 22
df_AMKP_22["Total_Art_yang_hiburan"]=df_AMKP_22["M_1208_1"]+df_AMKP_22["M_1208_3"]+df_AMKP_22["M_1209_1"]+df_AMKP_22["M_1209_3"]
df_AMKP_22["AMKP22"]=np.where((df_AMKP_22["Total_Art_yang_hiburan"]>0) & (df_AMKP_22["Pengeluaran Untuk Hiburan(R303)"]==0),"1","0")
df_AMKP_22["Keterangan"]=np.where(df_AMKP_22["AMKP22"]=="1","Pengeluaran untuk hiburan harus terisi","")
df_anomali_AMKP_22=df_AMKP_22[df_AMKP_22["AMKP22"]=="1"]
df_anomali_AMKP_22.to_excel("df_anomali_Konsistensi_MdanKP_22.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_22.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/22 Konsistensi Pengeluaran Hiburan untuk ART yg ikut mengikuti acara kebudayaan.xlsx', index=False)
df_anomali_AMKP_22

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,...,NAMAKRT,ID_ruta,M_1208_1,M_1208_3,M_1209_1,M_1209_3,Pengeluaran Untuk Hiburan(R303),Total_Art_yang_hiburan,AMKP22,Keterangan
10,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,1,...,PARNOTO,501501,0,0,2,0,0.0,2,1,Pengeluaran untuk hiburan harus terisi
11,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,2,...,SUTILAWATI,501502,0,0,4,0,0.0,4,1,Pengeluaran untuk hiburan harus terisi
12,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,3,...,SYAMSUL PALAMANI,501503,0,0,0,5,0.0,5,1,Pengeluaran untuk hiburan harus terisi
14,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,5,...,MISPAN,501505,0,0,0,4,0.0,4,1,Pengeluaran untuk hiburan harus terisi
15,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,6,...,AFRIZAL TANJUNG,501506,0,0,3,0,0.0,3,1,Pengeluaran untuk hiburan harus terisi
16,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,7,...,RIKI FEBRIANTO,501507,0,0,3,0,0.0,3,1,Pengeluaran untuk hiburan harus terisi
17,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,8,...,SARJONI,501508,0,0,3,0,0.0,3,1,Pengeluaran untuk hiburan harus terisi
18,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,10,...,MUSA LASTIAR HUTAGALUNG,5015010,0,0,0,4,0.0,4,1,Pengeluaran untuk hiburan harus terisi
19,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,12,...,M. AMIN,5015012,0,0,0,3,0.0,3,1,Pengeluaran untuk hiburan harus terisi
21,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00474,000300,1,...,SUPRIYATNA,004741,5,0,5,0,0.0,10,1,Pengeluaran untuk hiburan harus terisi
37,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00474,000300,10,...,MAHFUD RIDHO ANSHORI,0047410,0,0,4,0,0.0,4,1,Pengeluaran untuk hiburan harus terisi
61,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,1,...,JUMIATI,503681,0,0,0,1,0.0,1,1,Pengeluaran untuk hiburan harus terisi
66,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,5,...,AHMAD SAFARI,503685,0,0,3,0,0.0,3,1,Pengeluaran untuk hiburan harus terisi
67,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50363,001800,5,...,ALIS TAUFIQ,503635,0,0,0,4,0.0,4,1,Pengeluaran untuk hiburan harus terisi
69,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,6,...,MASITA,503686,0,0,1,0,0.0,1,1,Pengeluaran untuk hiburan harus terisi
70,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,7,...,RENDRA MONTI,503687,0,0,4,0,0.0,4,1,Pengeluaran untuk hiburan harus terisi
71,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50363,001800,7,...,KAMTANI,503637,0,0,1,0,0.0,1,1,Pengeluaran untuk hiburan harus terisi
73,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,8,...,ERNA WATI,503688,0,0,4,0,0.0,4,1,Pengeluaran untuk hiburan harus terisi
78,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,12,...,ACHMAD MARZUKI,5036812,0,0,1,3,0.0,4,1,Pengeluaran untuk hiburan harus terisi
82,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,14,TELUK SIALANG,2,00955,001200,3,...,YANTO,009553,0,0,1,0,0.0,1,1,Pengeluaran untuk hiburan harus terisi
84,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,14,TELUK SIALANG,2,00955,001200,5,...,MUHRI,009555,0,0,1,0,0.0,1,1,Pengeluaran untuk hiburan harus terisi
87,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,14,TELUK SIALANG,2,00955,001200,8,...,FADLI AZHARI,009558,0,0,3,0,0.0,3,1,Pengeluaran untuk hiburan harus terisi
103,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,4,...,MARGONO,009794,2,0,2,0,0.0,4,1,Pengeluaran untuk hiburan harus terisi
110,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,1,...,JANIMIN,011581,0,0,0,1,0.0,1,1,Pengeluaran untuk hiburan harus terisi
111,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,2,...,BAHERUDDIN,011582,0,0,0,2,0.0,2,1,Pengeluaran untuk hiburan harus terisi
112,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,3,...,SUDIONO,011583,0,0,0,3,0.0,3,1,Pengeluaran untuk hiburan harus terisi
113,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,4,...,JAMILAH,011584,0,0,0,1,0.0,1,1,Pengeluaran untuk hiburan harus terisi
114,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,6,...,M. KHAIRUDDIN,011586,0,0,0,1,0.0,1,1,Pengeluaran untuk hiburan harus terisi
115,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,7,...,AZRA' I,011587,0,0,0,1,0.0,1,1,Pengeluaran untuk hiburan harus terisi
116,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,8,...,HAMIM YUSUF,011588,0,0,0,3,0.0,3,1,Pengeluaran untuk hiburan harus terisi
119,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,13,...,A. HAIRI,0115813,0,0,0,4,0.0,4,1,Pengeluaran untuk hiburan harus terisi

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 23
df_AMKP_23["AMKP23"]=np.where((df_AMKP_23["M_1312_1"]>0) & (df_AMKP_23["Transfer untuk lembaga Nirlaba (Blok VE Rincian 4 Kolom 4) "]==0),"1","0")
df_AMKP_23["Keterangan"]=np.where(df_AMKP_23["AMKP23"]=="1","Pengeluaran untuk lembaga nirlaba harus terisi","")
df_anomali_AMKP_23=df_AMKP_23[df_AMKP_23["AMKP23"]=="1"]
df_anomali_AMKP_23.to_excel("df_anomali_Konsistensi_MdanKP_23.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_23.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/23 Konsistensi Transfer Ke Lembaga Nirlaba untuk ART yang menyumbang.xlsx', index=False)
df_anomali_AMKP_23

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M_1312_1, Transfer untuk lembaga Nirlaba (Blok VE Rincian 4 Kolom 4) , AMKP23, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 24
df_AMKP_24["AMKP24"]=np.where((df_AMKP_24["RumahMilikSendiri_1501"]>0) & (df_AMKP_24["Pengeluaran Untuk PBB (R335)"]==0),"1","0")
df_AMKP_24["Keterangan"]=np.where(df_AMKP_24["AMKP24"]=="1","Pengeluaran untuk Pajak Bumi dan Bangunan harus terisi","")
df_anomali_AMKP_24=df_AMKP_24[df_AMKP_24["AMKP24"]=="1"]
df_anomali_AMKP_24.to_excel("df_anomali_Konsistensi_MdanKP_24.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_24.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/24 Konsistensi Pengeluaran PBB untuk ART yang punya rumah sendiri.xlsx', index=False)
df_anomali_AMKP_24

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, RumahMilikSendiri_1501, Pengeluaran Untuk PBB (R335), AMKP24, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 25
df_AMKP_25["AMKP25"]=np.where((df_AMKP_25["ListrikPLN_1504"]>0) & (df_AMKP_25["Pengeluaran Untuk Listrik(R234)"]==0),"1","0")
df_AMKP_25["Keterangan"]=np.where(df_AMKP_25["AMKP25"]=="1","Pengeluaran untuk listrik harus terisi","")
df_anomali_AMKP_25=df_AMKP_25[df_AMKP_25["AMKP25"]=="1"]
df_anomali_AMKP_25.to_excel("df_anomali_Konsistensi_MdanKP_25.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_25.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/25 Konsistensi Pengeluaran Listri untuk Ruta yang menggunakan Listrik PLN.xlsx', index=False)
df_anomali_AMKP_25

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, ListrikPLN_1504, Pengeluaran Untuk Listrik(R234), AMKP25, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 26
df_AMKP_26["AMKP26"]=np.where((df_AMKP_26["M_1701_1"]>0) & (df_AMKP_26["Transfer bantuan dari pemerintah (Blok VE Rincian 1.b Kolom 2) "]==0),"1","0")
df_AMKP_26["Keterangan"]=np.where(df_AMKP_26["AMKP26"]=="1","Transfer berjalan dari pemerintah harus terisi untuk Ruta yang mendapatkan bantuan PKH","")
df_anomali_AMKP_26=df_AMKP_26[df_AMKP_26["AMKP26"]=="1"]
df_anomali_AMKP_26.to_excel("df_anomali_Konsistensi_MdanKP_26.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_26.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/26 Konsistensi Penerimaan Transfer untuk Ruta yang mendapatkan PKH.xlsx', index=False)
df_anomali_AMKP_26

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M_1701_1, Transfer bantuan dari pemerintah (Blok VE Rincian 1.b Kolom 2) , AMKP26, Keterangan]
Index: []

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 27
df_AMKP_27["AMKP27"]=np.where((df_AMKP_27["M_1703_1"]>0) & (df_AMKP_27["Transfer bantuan dari pemerintah dalam bentuk barang jasa (Blok VE Rincian 1.b Kolom 3) "]==0),"1","0")
df_AMKP_27["Keterangan"]=np.where(df_AMKP_27["AMKP27"]=="1","Transfer berjalan dari pemerintah harus terisi untuk Ruta yang mendapatkan BPNT/Program Sembako","")
df_anomali_AMKP_27=df_AMKP_27[df_AMKP_27["AMKP27"]=="1"]
df_anomali_AMKP_27.to_excel("df_anomali_Konsistensi_MdanKP_27.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_27.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/27 Konsistensi Penerimaan Transfer untuk Ruta yang mendapatkan BPNT.xlsx', index=False)
df_anomali_AMKP_27

,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,SEMESTER,NAMAKRTDSR,NAMAKRT,ID_ruta,M_1703_1,Transfer bantuan dari pemerintah dalam bentuk barang jasa (Blok VE Rincian 1.b Kolom 3),AMKP27,Keterangan
40,7,TANJUNG JABUNG BARAT,20,PENGABUAN,7,PARIT PUDIN,2,00661,001300,1,2,JAILANI,SIPLI,006611,3,0.0,1,Transfer berjalan dari pemerintah harus terisi...
43,7,TANJUNG JABUNG BARAT,20,PENGABUAN,7,PARIT PUDIN,2,00661,001300,4,2,DARMADI,DARMADI,006614,6,0.0,1,Transfer berjalan dari pemerintah harus terisi...
49,7,TANJUNG JABUNG BARAT,20,PENGABUAN,7,PARIT PUDIN,2,00661,001300,13,2,NUR ASIAH,SYAHRUNI,0066113,4,0.0,1,Transfer berjalan dari pemerintah harus terisi...
104,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,5,2,M. SAINI,M. SAINI,009795,3,0.0,1,Transfer berjalan dari pemerintah harus terisi...

In [ ]:
#KONSISTESI VSEN25.M dan VSEN25.KP NO 28
df_AMKP_28["Total_transfer_lainnya"]=df_AMKP_28["Transfer bantuan dari pemerintah dalam bentuk uang (Blok VE Rincian 1.b Kolom 2)"] + df_AMKP_28["Transfer bantuan dari pemerintah dalam bentuk barang jasa (Blok VE Rincian 1.b Kolom 3) "]
df_AMKP_28["AMKP28"]=np.where((df_AMKP_28["M_1704_1"]>0) & (df_AMKP_28["Total_transfer_lainnya"]==0),"1","0")
df_AMKP_28["Keterangan"]=np.where(df_AMKP_28["AMKP28"]=="1","Transfer berjalan dari pemerintah harus terisi untuk Ruta yang mendapatkan bantuan lainnya dari pemerintah","")
df_anomali_AMKP_28=df_AMKP_28[df_AMKP_28["AMKP28"]=="1"]
df_anomali_AMKP_28.to_excel("df_anomali_Konsistensi_MdanKP_28.xlsx", index=False)   # requires openpyxl or xlsxwriter installed
df_anomali_AMKP_28.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/28 Konsistensi Penerimaan Transfer untuk Ruta yang mendapatkan bantuan lainnya dari pemerintah.xlsx', index=False)
df_anomali_AMKP_28

Empty DataFrame
Columns: [KAB, NAMAKABUPA, KEC, NAMAKECAMA, DESA, NAMADESA, KLASIFIKAS, NKS, SLS, NURT, SEMESTER, NAMAKRTDSR, NAMAKRT, ID_ruta, M_1704_1, Transfer bantuan dari pemerintah dalam bentuk uang (Blok VE Rincian 1.b Kolom 2), Transfer bantuan dari pemerintah dalam bentuk barang jasa (Blok VE Rincian 1.b Kolom 3) , Total_transfer_lainnya, AMKP28, Keterangan]
Index: []

In [ ]:
### GABUNGKAN SELURUH ANOMALI KONSISTENSI M DAN KP DALAM 1 FILE
import pandas as pd
from functools import reduce

### 01 Gabungkan Seluruh Kode Anomali dan Status Anomali dalam 1 Dataframe
df_AMKP_01_sel=df_AMKP_01[["ID_ruta","AMKP01"]]
df_AMKP_02_1_sel=df_AMKP_02_1[["ID_ruta","AMKP02_1"]]
df_AMKP_02_2_sel=df_AMKP_02_2[["ID_ruta","AMKP02_2"]]
df_AMKP_02_3_sel=df_AMKP_02_3[["ID_ruta","AMKP02_3"]]
df_AMKP_02_4_sel=df_AMKP_02_4[["ID_ruta","AMKP02_4"]]
df_AMKP_03_sel=df_AMKP_03[["ID_ruta","AMKP03"]]
df_AMKP_04_sel=df_AMKP_04[["ID_ruta","AMKP04"]]
df_AMKP_05_sel=df_AMKP_05[["ID_ruta","AMKP05"]]
df_AMKP_06_sel=df_AMKP_06[["ID_ruta","AMKP06"]]
df_AMKP_08_sel=df_AMKP_08[["ID_ruta","AMKP08"]]
df_AMKP_09_sel=df_AMKP_09[["ID_ruta","AMKP09"]]
df_AMKP_10_sel=df_AMKP_10[["ID_ruta","AMKP10"]]
df_AMKP_11_sel=df_AMKP_11[["ID_ruta","AMKP11"]]
df_AMKP_12_sel=df_AMKP_12[["ID_ruta","AMKP12"]]
df_AMKP_13_sel=df_AMKP_13[["ID_ruta","AMKP13"]]
df_AMKP_14_sel=df_AMKP_14[["ID_ruta","AMKP14"]]
df_AMKP_15_sel=df_AMKP_15[["ID_ruta","AMKP15"]]
df_AMKP_16_sel=df_AMKP_16[["ID_ruta","AMKP16"]]
df_AMKP_17_sel=df_AMKP_17[["ID_ruta","AMKP17"]]
df_AMKP_18_sel=df_AMKP_18[["ID_ruta","AMKP18"]]
df_AMKP_19_sel=df_AMKP_19[["ID_ruta","AMKP19"]]
df_AMKP_20_sel=df_AMKP_20[["ID_ruta","AMKP20"]]
df_AMKP_21_sel=df_AMKP_21[["ID_ruta","AMKP21"]]
df_AMKP_22_sel=df_AMKP_22[["ID_ruta","AMKP22"]]
df_AMKP_23_sel=df_AMKP_23[["ID_ruta","AMKP23"]]
df_AMKP_24_sel=df_AMKP_24[["ID_ruta","AMKP24"]]
df_AMKP_25_sel=df_AMKP_25[["ID_ruta","AMKP25"]]
df_AMKP_26_sel=df_AMKP_26[["ID_ruta","AMKP26"]]
df_AMKP_27_sel=df_AMKP_27[["ID_ruta","AMKP27"]]
df_AMKP_28_sel=df_AMKP_28[["ID_ruta","AMKP28"]]
df_merged=[df_AMKP_01_sel,df_AMKP_02_1_sel,df_AMKP_02_2_sel,df_AMKP_02_3_sel,df_AMKP_02_4_sel,df_AMKP_03_sel,
           df_AMKP_04_sel,df_AMKP_05_sel,df_AMKP_06_sel,df_AMKP_08_sel,df_AMKP_09_sel,df_AMKP_10_sel,df_AMKP_11_sel,
           df_AMKP_12_sel,df_AMKP_13_sel,df_AMKP_14_sel,df_AMKP_15_sel,df_AMKP_16_sel,df_AMKP_17_sel,df_AMKP_18_sel,
           df_AMKP_19_sel,df_AMKP_20_sel,df_AMKP_21_sel,df_AMKP_22_sel,df_AMKP_23_sel,df_AMKP_24_sel,df_AMKP_25_sel,
           df_AMKP_26_sel,df_AMKP_27_sel,df_AMKP_28_sel]
df_AMKP_pivot = reduce(lambda left, right: pd.merge(left, right, on="ID_ruta", how="outer"), df_merged)
df_AMKP_pivot.head()

### 02 Unpivot Dataframe yanng berisikan ID_ruta dengan Kode Anomali dan Status Anomali
df_melted = pd.melt(
    df_AMKP_pivot,
    id_vars=["ID_ruta"],          # rows
    value_vars=[ 'AMKP01',
 'AMKP02_1',
 'AMKP02_2',
 'AMKP02_3',
 'AMKP02_4',
 'AMKP03',
 'AMKP04',
 'AMKP05',
 'AMKP06',
 'AMKP08',
 'AMKP09',
 'AMKP10',
 'AMKP11',
 'AMKP12',
 'AMKP13',
 'AMKP14',
 'AMKP15',
 'AMKP16',
 'AMKP17',
 'AMKP18',
 'AMKP19',
 'AMKP20',
 'AMKP21',
 'AMKP22',
 'AMKP23',
 'AMKP24',
 'AMKP25',
 'AMKP26',
 'AMKP27',
 'AMKP28'],
    var_name="Kode Anomali",
    value_name="Status Anomali"
    )


### 03 Siapkan Dataframe yang berisikan Identitas seluruh Ruta Sampel SSN
cols_to_keep_df_kor=['ID_ruta', 'KAB','NAMAKABUPA','KEC',
 'NAMAKECAMA','DESA', 'NAMADESA',
 'KLASIFIKAS', 'NKS', 'SLS', 'NURT',
 'NAMAKRTDSR', 'NAMAKRT']
df_AMKP_ID=df_kor_rt[cols_to_keep_df_kor]

### 04 Merge Dataframe yang berisikan Identitas seluruh Ruta Sampel SSN dengan Dataframe yang berisikan Status Anomali
df_AMKP_full=pd.merge(df_AMKP_ID,df_melted, on="ID_ruta", how="left")
df_AMKP_full_anomali=df_AMKP_full[df_AMKP_full["Status Anomali"]=="1"]
df_AMKP_full_anomali
df_AMKP_full_anomali=df_AMKP_full_anomali.drop(columns="Status Anomali")
df_AMKP_full_anomali

### 05 Import Dataframe yang berisikan keterangan Anomali
ket_anomali = pd.read_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Keterangan Anomali.xlsx', engine="openpyxl")

### 06 Merge Dataframe yang berisikan keterangan Anomali dengan Dataframe yang berisikan Ruta-Ruta berdasarkan Anomali
cols_to_keep2=['ID_ruta','CATATAN']
df_AMKP_Catatan=df_kp10[cols_to_keep2]

dfKonistensiMKP_ketanomali=pd.merge(df_AMKP_full_anomali,ket_anomali, on="Kode Anomali", how="left")
dfKonistensiMKP=pd.merge(dfKonistensiMKP_ketanomali,df_AMKP_Catatan, on="ID_ruta", how="left")

### 07 Export Dataframe yang berisikan Ruta dengan anomali beserta keterangannya
dfKonistensiMKP.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/Hasil Run Anomali M_KP/[Pengecekan Konsistensi VSEN25-M dan VSEN25-KP].xlsx', index=False)
dfKonistensiMKP

,ID_ruta,KAB,NAMAKABUPA,KEC,NAMAKECAMA,DESA,NAMADESA,KLASIFIKAS,NKS,SLS,NURT,NAMAKRTDSR,NAMAKRT,Kode Anomali,Keterangan,CATATAN
0,501501,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,1,PARNOTO,PARNOTO,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R303=0: MENONTON PAWAI BUDAYA GRATIS MENYAMBUT...
1,501502,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,2,SUTILAWATI,SUTILAWATI,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,ANOMALI : R 905TERISI TIDAK RELEVAN KARENA TID...
2,501503,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,3,SYAMSUL PALAMANI,SYAMSUL PALAMANI,AMKP16,16 Pengeluaran sumbangan pembangunan sekolah h...,JUALAN SAYUR 1.5JT/2 HARI KOTOR 350 BERSIH. TI...
3,501503,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,3,SYAMSUL PALAMANI,SYAMSUL PALAMANI,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,JUALAN SAYUR 1.5JT/2 HARI KOTOR 350 BERSIH. TI...
4,501505,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,5,MISPAN,MISPAN,AMKP16,16 Pengeluaran sumbangan pembangunan sekolah h...,M1118A TERISI KARENA ART 04 BARU MASUK SMP TAH...
5,501505,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,5,MISPAN,MISPAN,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,M1118A TERISI KARENA ART 04 BARU MASUK SMP TAH...
6,501506,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,6,AFRIZAL TANJUNG,AFRIZAL TANJUNG,AMKP16,16 Pengeluaran sumbangan pembangunan sekolah h...,M1108 TERISI KARENA PENDAFTARAN TK PADA TAHUN ...
7,501506,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,6,AFRIZAL TANJUNG,AFRIZAL TANJUNG,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,M1108 TERISI KARENA PENDAFTARAN TK PADA TAHUN ...
8,501507,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,7,RIKI FEBRIANTO,RIKI FEBRIANTO,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R303=0: MENONTON PAWAI BUDAYA GRATIS ACARA 17AN
9,501508,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,8,SARJONI,SARJONI,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R303=0: MELIHAT PAWAI BUDAYA ACARA HARI KEMERD...
10,5015010,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,10,MUSA LASTIAR HUTAGALUNG,MUSA LASTIAR HUTAGALUNG,AMKP16,16 Pengeluaran sumbangan pembangunan sekolah h...,R292 KOSONG KARENA UANG PENDAFTARAN ITU UNTUK ...
11,5015010,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,10,MUSA LASTIAR HUTAGALUNG,MUSA LASTIAR HUTAGALUNG,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R292 KOSONG KARENA UANG PENDAFTARAN ITU UNTUK ...
12,5015012,7,TANJUNG JABUNG BARAT,13,TEBING TINGGI,4,TEBING TINGGI,1,50150,002300,12,M. AMIN,M. AMIN,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R303=0: MENONTON HIBURAN PAWAI BUDAYA DALAM RA...
13,004741,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00474,000300,1,SUPRIYATNA,SUPRIYATNA,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R303 TIDAK TERISI KARNA SUPRYATNA HANYA MENONT...
14,0047410,7,TANJUNG JABUNG BARAT,14,RENAH MENDALUH,4,LAMPISI,1,00474,000300,10,MAHFUD RIDHO ANSHORI,MAHFUD RIDHO ANSHORI,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R=303 MENONTON PERTUJNJUKAN PAWAI TAK BAYAR
15,006611,7,TANJUNG JABUNG BARAT,20,PENGABUAN,7,PARIT PUDIN,2,00661,001300,1,JAILANI,SIPLI,AMKP27,27 Transfer berjalan dari pemerintah harus ter...,
16,006613,7,TANJUNG JABUNG BARAT,20,PENGABUAN,7,PARIT PUDIN,2,00661,001300,3,SYAFRIZAL,SYAFRIZAL,AMKP02_3,02_3 Pengeluaran untuk Susu Bubuk Bayi harus t...,ART KE 7 TIDAK MENGONSUMSI SUSU BUBUK BAYI KAR...
17,006614,7,TANJUNG JABUNG BARAT,20,PENGABUAN,7,PARIT PUDIN,2,00661,001300,4,DARMADI,DARMADI,AMKP27,27 Transfer berjalan dari pemerintah harus ter...,
18,0066113,7,TANJUNG JABUNG BARAT,20,PENGABUAN,7,PARIT PUDIN,2,00661,001300,13,NUR ASIAH,SYAHRUNI,AMKP27,27 Transfer berjalan dari pemerintah harus ter...,
19,503681,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,1,JUMIATI,JUMIATI,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R303 TIDAK TERISI MESKIPUN ADA ART YANG MENYAK...
20,503633,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50363,001800,3,ZUNAIDI,ZUNAIDI,AMKP20,20 Pengeluaran iuran sekolah lainnya harus ter...,B42K5.331 MEMBELI SEPEDA LISTRIK
21,503685,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,5,AMAT SAFARI,AHMAD SAFARI,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R303 TIDAK TERISI KARNA MENONTON KONSER ANDIKA...
22,503635,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50363,001800,5,ALIS TAUFIQ,ALIS TAUFIQ,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,RESPONDEN MENGIKUTI KONSER ANDIKA KANGEN BAND ...
23,503686,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,6,ABDUL HARIS,MASITA,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R303 TIDAK TERISI MESKIPUN KETERANGANNYA ADALA...
24,503687,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,7,RENDRA MONTI,RENDRA MONTI,AMKP16,16 Pengeluaran sumbangan pembangunan sekolah h...,R291-R297 MEMILIKI NILAI YANG LEBIH KECIL DARI...
25,503687,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,7,RENDRA MONTI,RENDRA MONTI,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R291-R297 MEMILIKI NILAI YANG LEBIH KECIL DARI...
26,503637,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50363,001800,7,KAMTANI,KAMTANI,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,RESPONDEN IKUT NONTON PESTA RAKYAT ULTAH TANJN...
27,503688,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,8,ERNA WATI,ERNA WATI,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R303 TIDAK TERISI KARENA RESPONDEN MENONTON PE...
28,5036812,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,12,ACHMAD MARZUKI,ACHMAD MARZUKI,AMKP16,16 Pengeluaran sumbangan pembangunan sekolah h...,R303 TIDAK TERISI KARENA ART INI HANYA MENONTO...
29,5036812,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,10,TUNGKAL II,1,50368,002300,12,ACHMAD MARZUKI,ACHMAD MARZUKI,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R303 TIDAK TERISI KARENA ART INI HANYA MENONTO...
30,009553,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,14,TELUK SIALANG,2,00955,001200,3,YANTO,YANTO,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,RUMAH TANGGA YANTO TIDAK MENGGUNAKAN ELPIGI- K...
31,009555,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,14,TELUK SIALANG,2,00955,001200,5,MUHRI,MUHRI,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,"R 303, ART 3 MENONTON HIBURAN RAKYAT GRATIS SE..."
32,009558,7,TANJUNG JABUNG BARAT,30,TUNGKAL ILIR,14,TELUK SIALANG,2,00955,001200,8,FADLI AZHARI,FADLI AZHARI,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R292-R297 TERISI LEBIH KECIL DARI VSEN25.M R11...
33,009793,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,3,KASPUL ANUAR,KASPUL ANUAR,AMKP15,15 Penerimaan Transfer dari badan usaha atau l...,MENDAPAT BEASISWA NON PEMERINTAH: DARI BOS AYA...
34,009794,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,4,MARGONO,MARGONO,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,R303=0 KARENA MELIHAT PAWAI ACARA 17 AN GRATIS...
35,009795,7,TANJUNG JABUNG BARAT,31,BRAM ITAM,2,BRAM ITAM KIRI,2,00979,000500,5,M. SAINI,M. SAINI,AMKP27,27 Transfer berjalan dari pemerintah harus ter...,DAPAT BANTUAN PENDIDIKAN DARI BOS AYAHNYA SEHI...
36,011581,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,1,JANIMIN,JANIMIN,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,ISIAN 303 KOSONG KARENA PERTUNJUKAN YANG DITON...
37,011582,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,2,BAHERUDDIN. S,BAHERUDDIN,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,RINCIAN 303 TIDAK TERISI KARENA PERTUNJUKAN YA...
38,011583,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,3,SUDIYONO,SUDIONO,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,RINCIAN 303 KOSONG KARENA PERTUNJUKAN YANG DIT...
39,011584,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,4,JAMILAH,JAMILAH,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,RINCIAN 303 TIDAK TERISI KARENA PERTUNJUKAN YA...
40,011586,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,6,M. KHAIRUDDIN,M. KHAIRUDDIN,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,RINCIAN 303 TIDAK TERISI KARENA PERTUNJUKAN YA...
41,011587,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,7,AZRA' I,AZRA' I,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,RINCIAN 303 KOSONG KARENA PERTUNJUKAN YANG DIT...
42,011588,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,8,HAMIM YUSUF,HAMIM YUSUF,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,RINCIAN 303 TIDAK TERISI KARENA PERTUNJUKAN YA...
43,011589,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,9,MULYADI,MULYADI,AMKP09,09 Konsumsi dan pengeluaran padi-padian dan um...,KONSUMSI PADI-PADIAN DAN UMBI-UMBIAN KARENA DA...
44,0115813,7,TANJUNG JABUNG BARAT,40,BETARA,7,SERDANG JAYA,2,01158,000500,13,A. HAIRI,A. HAIRI,AMKP22,22 Pengeluaran untuk hiburan harus terisi (VSE...,RINCIAN 303 TIDAK TERISI KARENA PERTUNJUKAN YA...
45,012621,7,TANJUNG JABUNG BARAT,40,BETARA,16,SUNGAI TERAP,2,01262,000500,1,RADIAH,RADIAH,AMKP06,06 Biaya pelayanan pengobatan/kuratif harus te...,RUMAH TANGGA INI MEMANG TIDAK BANYAK KONSUMSI ...
46,013778,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,8,BAHRAN,BAHRAN,AMKP16,16 Pengeluaran sumbangan pembangunan sekolah h...,
47,013779,7,TANJUNG JABUNG BARAT,41,KUALA BETARA,10,SUAK LABU,2,01377,000600,9,IRWAN NUDIN,IRWAN NUDIN,AMKP02_3,02_3 Pengeluaran untuk Susu Bubuk Bayi harus t...,BALITA SUDAH TIDAK MENGONSUMSI SUSU BAYI LAGI ...

# **04 PEMERIKSAAN OUTLIER BASKET KOMODITAS**

## 04.1.1 Pemeriksaan Outlier Konsumsi per Kapita Komoditas Makanan

In [ ]:
## 01 Komoditas Padi-Padian
import plotly.express as px
selected_cats=["01111001","01111003","01111005/2","01115005"]
df_filtered=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats)]
df_filtered["PerSatuan"]=(df_filtered["KOLOM6"]/df_filtered["R301"])
fig =px.box(df_filtered,x="KODECOICOP", y=df_filtered["PerSatuan"], hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig.update_layout(
    xaxis_title="Padi-padian",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "01 Cek Outlier Konsumsi Padi-Padian",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig.update_xaxes(
    ticktext=["2. Beras", "3. Beras Ketan","5. Jagung pipilan/beras jagung/jagung titi","6. Tepung Terigu"],  # new labels
    tickvals=["01111001","01111003","01111005/2","01115005"]                     # original values in the data
)

fig.show()

/tmp/ipython-input-1081789771.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered["PerSatuan"]=(df_filtered["KOLOM6"]/df_filtered["R301"])

In [ ]:
## 02 Komoditas Umbi-Umbian
import plotly.express as px
selected_cats2=["01178001","01178002","01178001"]
df_filtered2=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats2)]
df_filtered2["PerSatuan"]=(df_filtered2["KOLOM6"]/df_filtered2["R301"])
fig2 =px.box(df_filtered2,x="KODECOICOP", y="KOLOM6", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig2.update_layout(
    xaxis_title="Umbi-Umbian",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "02 Cek Outlier Konsumsi Umbi-Umbian",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig2.update_xaxes(
    ticktext=["9.Ketela pohon/singkong", "10.Ketela rambat/ubi jalar","14.Gaplek"],  # new labels
    tickvals=["01178001","01178002","01178001"]                     # original values in the data
)

fig2.show()

/tmp/ipython-input-3429723159.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 03 Komoditas IKAN/UDANG/CUMI
import plotly.express as px
selected_cats3=["01131069","01131072","01131013","01131028","01131067","01131003","01131045","01133032"]
df_filtered3=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats3)]
df_filtered3["PerSatuan"]=(df_filtered3["KOLOM6"]/df_filtered3["R301"])
fig3 =px.box(df_filtered3,x="KODECOICOP", y="KOLOM6", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig3.update_layout(
    xaxis_title="Umbi-Umbian",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "03 Cek Outlier Konsumsi IKAN/UDANG/CUMI",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig3.update_xaxes(
    ticktext=["18. Tongkol", "19.Tuna","20.Cakalang,dencis","23. Kembung","24.Teri Basah","25.Bandeng","27.Mujair","51.Teri Diawetkan"],  # new labels
    tickvals=["01131069","01131072","01131013","01131028","01131067","01131003","01131045","01133032"]                     # original values in the data
)

fig3.show()

/tmp/ipython-input-1379313124.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 04 Komoditas DAGING
import plotly.express as px
selected_cats4=["01121001","01122001","01124003","01124002","01121005"]
df_filtered4=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats4)]
df_filtered4["PerSatuan"]=(df_filtered4["KOLOM6"]/df_filtered4["R301"])
fig4 =px.box(df_filtered4,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig4.update_layout(
    xaxis_title="Daging",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "04 Cek Outlier Konsumsi DAGING",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig4.update_xaxes(
    ticktext=["62. Daging Sapi", "65. Daging Babi","66.Daging Ayam Ras","67. Daging Ayam Kampung","72.Tetelan"],  # new labels
    tickvals=["01121001","01122001","01124003","01124002","01121005"]                     # original values in the data
)

fig4.show()

/tmp/ipython-input-3575784267.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 05 Komoditas Telur dan Susu
import plotly.express as px
selected_cats5=["01147002","01147003","01143005","01143001/2"]
df_filtered5=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats5)]
df_filtered5["PerSatuan"]=(df_filtered5["KOLOM6"]/df_filtered5["R301"])
fig5 =px.box(df_filtered5,x="KODECOICOP", y="KOLOM6", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig5.update_layout(
    xaxis_title="Daging",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "05 Cek Outlier Konsumsi Telur dan SUsu",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig5.update_xaxes(
    ticktext=["75. Telur Ayam Ras", "77. Telur Itik/Telur Itik Manila","80. Kental Manis","81. Susu Bubuk"],  # new labels
    tickvals=["01147002","01147003","01143005","01143001/2"]                     # original values in the data
)

fig5.show()

/tmp/ipython-input-3222282631.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 06 Komoditas Sayur
import plotly.express as px
selected_cats6=["01171012","01173003","01173008","01173005","01171010","01173017","01174006","01173012","01173013"]
df_filtered6=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats6)]
df_filtered6["PerSatuan"]=(df_filtered6["KOLOM6"]/df_filtered6["R301"])
fig6 =px.box(df_filtered6,x="KODECOICOP", y="KOLOM6", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig6.update_layout(
    xaxis_title="Komoditas Sayur",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "06 Cek Outlier Konsumsi Sayur-Sayuran",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig6.update_xaxes(
    ticktext=["86.Bayam", "91.Buncis","92. Kacang Panjang","93.Tomat","96.Daun Ketela Pohon","102.Nangka Muda","105.Bawang Merah","108.Cabe Merah","110.Cabe Rawit"],  # new labels
    tickvals=["01171012","01173003","01173008","01173005","01171010","01173017","01174006","01173012","01173013"]                     # original values in the data
)

fig6.show()

/tmp/ipython-input-3983614107.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 07 Komoditas Kacang-Kacangan
import plotly.express as px
selected_cats7=["01168010","01194011","01194013"]
df_filtered7=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats7)]
df_filtered7["PerSatuan"]=(df_filtered7["KOLOM6"]/df_filtered7["R301"])
fig7 =px.box(df_filtered7,x="KODECOICOP", y="KOLOM6", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig7.update_layout(
    xaxis_title="Komoditas Kacang-Kacangan",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "07 Cek Outlier Nilai Konsumsi Kacang-Kacangan",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig7.update_xaxes(
    ticktext=["122.Kacang Tanah Tanpa Kulit", "125.Tahu","126.Tempe"],  # new labels
    tickvals=["01168010","01194011","01194013"]                     # original values in the data
)

fig7.show()

/tmp/ipython-input-3999393556.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 08 Komoditas Buah-Buahan
import plotly.express as px
selected_cats8=["01167002-14","01165008-11","01162001","01162002-14","01167022-27"]
df_filtered8=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats8)]
df_filtered8["PerSatuan"]=(df_filtered8["KOLOM6"]/df_filtered8["R301"])
fig8 =px.box(df_filtered8,x="KODECOICOP", y="KOLOM6", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig8.update_layout(
    xaxis_title="Komoditas Buah-buahan",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "08 Cek Outlier Nilai Konsumsi Buah-buahan",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig8.update_xaxes(
    ticktext=["131.Mangga", "136.Salak","137.Pisang","138.Pisang Lainnya","139.Pepaya"],  # new labels
    tickvals=["01167002-14","01165008-11","01162001","01162002-14","01167022-27"]                     # original values in the data
)

fig8.show()

/tmp/ipython-input-737962819.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 09 Komoditas Minyak dan Kelapaa
import plotly.express as px
selected_cats9=["01154003","01167033"]
df_filtered9=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats9)]
df_filtered9["PerSatuan"]=(df_filtered9["KOLOM6"]/df_filtered9["R301"])
fig9 =px.box(df_filtered9,x="KODECOICOP", y="KOLOM6", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig9.update_layout(
    xaxis_title="Komoditas Minyak dan Kelapa",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "09 Cek Outlier Nilai Konsumsi Minyak dan Kelapa",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig9.update_xaxes(
    ticktext=["155.Minyak Kelapa", "157.Kelapa"],  # new labels
    tickvals=["01154003","01167033"]                     # original values in the data
)

fig9.show()

/tmp/ipython-input-989459913.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 10 Komoditas Bahan Minuman
import plotly.express as px
selected_cats10=["01181001","01181002","01167033","01151/52/53/54","01211001","01211002"]
df_filtered10=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats10)]
df_filtered10["PerSatuan"]=(df_filtered10["KOLOM6"]/df_filtered10["R301"])
fig10 =px.box(df_filtered10,x="KODECOICOP", y="KOLOM6", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig10.update_layout(
    xaxis_title="Komoditas Bahan Minuman",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "10 Cek Outlier Nilai Konsumsi Bahan Minuman",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig10.update_xaxes(
    ticktext=["160.Gula Pasir","161.Gula Merah","162.Teh Bubuk","163.Teh Celup(sachet)","164.Kopi Bubuk","165.Kopi Instan (sachet)"],  # new labels
    tickvals=["01181001","01181002","01167033","01151/52/53/54","01211001","01211002"]                     # original values in the data
)

fig10.show()

/tmp/ipython-input-3587057695.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 11 Komoditas Bumbu-Bumbuan
import plotly.express as px
selected_cats11=["01192001","01192005","01194003/4"]
df_filtered11=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats11)]
df_filtered11["PerSatuan"]=(df_filtered11["KOLOM6"]/df_filtered11["R301"])
fig11 =px.box(df_filtered11,x="KODECOICOP", y="KOLOM6", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig11.update_layout(
    xaxis_title="Komoditas Bumbu-Bumbuan",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "11 Cek Outlier Nilai Konsumsi Bumbu-Bumbuan",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig11.update_xaxes(
    ticktext=["168.Garam","169.Kemiri","175.Terasi/Petis"],  # new labels
    tickvals=["01192001","01192005","01194003/4"]                     # original values in the data
)

fig11.show()

/tmp/ipython-input-2823087667.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 12 Komoditas Makanan Lainnya
import plotly.express as px
selected_cats12=["01115012","01115018/19"]
df_filtered12=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats12)]
df_filtered12["PerSatuan"]=(df_filtered12["KOLOM6"]/df_filtered12["R301"])
fig12 =px.box(df_filtered12,x="KODECOICOP", y="KOLOM6", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig12.update_layout(
    xaxis_title="Komoditas Makanan Lainnya",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "12 Cek Outlier Nilai Konsumsi Bahan Makanan Lainnya",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig12.update_xaxes(
    ticktext=["183.Mie Instan","184.Kerupuk Mentah"],  # new labels
    tickvals=["01115012","01115018/19"]                     # original values in the data
)

fig12.show()

/tmp/ipython-input-3377676215.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## Komoditas Makanan Jadi Lainnya
import plotly.express as px
selected_cats_mj=[188,189,190,191,221]
df_filtered_mj=df_kp2[df_kp2["NOURUTKOMO"].isin(selected_cats_mj)]
df_filtered_mj["NOURUTKOMO"]=df_filtered_mj["NOURUTKOMO"].astype(str)
df_filtered_mj["PerSatuan"]=(df_filtered_mj["KOLOM6"]/df_filtered_mj["R301"])


figmj =px.box(df_filtered_mj,x="NOURUTKOMO", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
figmj.update_layout(
    xaxis_title="Komoditas Makanan Jadi",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "13 Cek Outlier Makanan Jadi",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
figmj.update_xaxes(
    ticktext=["188.Roti Tawar","189.Roti Manis","190.Kue Kering","191.Kue Basah","221.Rokok"],  # new labels
    tickvals=[188,189,190,191,221]                     # original values in the data
)

figmj.show()

/tmp/ipython-input-2259575961.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-2259575961.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

## 04.1.2 Pemeriksaan Outlier Konsumsi per satuan Komoditas Makanan

In [ ]:
## 01 Komoditas Padi-Padian
import plotly.express as px
selected_cats=["01111001","01111003","01111005/2","01115005"]
df_filtered=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats)]
df_filtered["PerSatuan"]=(df_filtered["KOLOM6"]/df_filtered["KOLOM5"])
fig =px.box(df_filtered,x="KODECOICOP", y=df_filtered["PerSatuan"], hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig.update_layout(
    xaxis_title="Padi-padian",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "01 Cek Outlier Konsumsi Padi-Padian",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig.update_xaxes(
    ticktext=["2. Beras", "3. Beras Ketan","5. Jagung pipilan/beras jagung/jagung titi","6. Tepung Terigu"],  # new labels
    tickvals=["01111001","01111003","01111005/2","01115005"]                     # original values in the data
)

fig.show()

/tmp/ipython-input-1572273738.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 02 Komoditas Umbi-Umbian
import plotly.express as px
selected_cats2=["01178001","01178002","01178001"]
df_filtered2=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats2)]
df_filtered2["PerSatuan"]=(df_filtered2["KOLOM6"]/df_filtered2["KOLOM5"])
fig2 =px.box(df_filtered2,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig2.update_layout(
    xaxis_title="Umbi-Umbian",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "02 Cek Outlier Konsumsi Umbi-Umbian",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig2.update_xaxes(
    ticktext=["9.Ketela pohon/singkong", "10.Ketela rambat/ubi jalar","14.Gaplek"],  # new labels
    tickvals=["01178001","01178002","01178001"]                     # original values in the data
)

fig2.show()

/tmp/ipython-input-3947180925.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 03 Komoditas IKAN/UDANG/CUMI
import plotly.express as px
selected_cats3=["01131069","01131072","01131013","01131028","01131067","01131003","01131045","01133032"]
df_filtered3=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats3)]
df_filtered3["PerSatuan"]=(df_filtered3["KOLOM6"]/df_filtered3["KOLOM5"])
fig3 =px.box(df_filtered3,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig3.update_layout(
    xaxis_title="Umbi-Umbian",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "03 Cek Outlier Konsumsi IKAN/UDANG/CUMI",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig3.update_xaxes(
    ticktext=["18. Tongkol", "19.Tuna","20.Cakalang,dencis","23. Kembung","24.Teri Basah","25.Bandeng","27.Mujair","51.Teri Diawetkan"],  # new labels
    tickvals=["01131069","01131072","01131013","01131028","01131067","01131003","01131045","01133032"]                     # original values in the data
)

fig3.show()

/tmp/ipython-input-1022573506.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 04 Komoditas DAGING
import plotly.express as px
selected_cats4=["01121001","01122001","01124003","01124002","01121005"]
df_filtered4=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats4)]
df_filtered4["PerSatuan"]=(df_filtered4["KOLOM6"]/df_filtered4["KOLOM5"])
fig4 =px.box(df_filtered4,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig4.update_layout(
    xaxis_title="Daging",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "04 Cek Outlier Konsumsi DAGING",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig4.update_xaxes(
    ticktext=["62. Daging Sapi", "65. Daging Babi","66.Daging Ayam Ras","67. Daging Ayam Kampung","72.Tetelan"],  # new labels
    tickvals=["01121001","01122001","01124003","01124002","01121005"]                     # original values in the data
)

fig4.show()

/tmp/ipython-input-2353338229.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 05 Komoditas Telur dan Susu
import plotly.express as px
selected_cats5=["01147002","01147003","01143005","01143001/2"]
df_filtered5=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats5)]
df_filtered5["PerSatuan"]=(df_filtered5["KOLOM6"]/df_filtered5["KOLOM5"])
fig5 =px.box(df_filtered5,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig5.update_layout(
    xaxis_title="Daging",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "05 Cek Outlier Konsumsi Telur dan SUsu",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig5.update_xaxes(
    ticktext=["75. Telur Ayam Ras", "77. Telur Itik/Telur Itik Manila","80. Kental Manis","81. Susu Bubuk"],  # new labels
    tickvals=["01147002","01147003","01143005","01143001/2"]                     # original values in the data
)

fig5.show()

/tmp/ipython-input-2839104349.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 06 Komoditas Sayur
import plotly.express as px
selected_cats6=["01171012","01173003","01173008","01173005","01171010","01173017","01174006","01173012","01173013"]
df_filtered6=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats6)]
df_filtered6["PerSatuan"]=(df_filtered6["KOLOM6"]/df_filtered6["KOLOM5"])
fig6 =px.box(df_filtered6,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig6.update_layout(
    xaxis_title="Komoditas Sayur",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "06 Cek Outlier Konsumsi Sayur-Sayuran",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig6.update_xaxes(
    ticktext=["86.Bayam", "91.Buncis","92. Kacang Panjang","93.Tomat","96.Daun Ketela Pohon","102.Nangka Muda","105.Bawang Merah","108.Cabe Merah","110.Cabe Rawit"],  # new labels
    tickvals=["01171012","01173003","01173008","01173005","01171010","01173017","01174006","01173012","01173013"]                     # original values in the data
)

fig6.show()

/tmp/ipython-input-964847706.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 07 Komoditas Kacang-Kacangan
import plotly.express as px
selected_cats7=["01168010","01194011","01194013"]
df_filtered7=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats7)]
df_filtered7["PerSatuan"]=(df_filtered7["KOLOM6"]/df_filtered7["KOLOM5"])
fig7 =px.box(df_filtered7,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig7.update_layout(
    xaxis_title="Komoditas Kacang-Kacangan",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "07 Cek Outlier Nilai Konsumsi Kacang-Kacangan",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig7.update_xaxes(
    ticktext=["122.Kacang Tanah Tanpa Kulit", "125.Tahu","126.Tempe"],  # new labels
    tickvals=["01168010","01194011","01194013"]                     # original values in the data
)

fig7.show()

/tmp/ipython-input-3489148286.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 08 Komoditas Buah-Buahan
import plotly.express as px
selected_cats8=["01167002-14","01165008-11","01162001","01162002-14","01167022-27"]
df_filtered8=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats8)]
df_filtered8["PerSatuan"]=(df_filtered8["KOLOM6"]/df_filtered8["KOLOM5"])
fig8 =px.box(df_filtered8,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig8.update_layout(
    xaxis_title="Komoditas Buah-buahan",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "08 Cek Outlier Nilai Konsumsi Buah-buahan",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig8.update_xaxes(
    ticktext=["131.Mangga", "136.Salak","137.Pisang","138.Pisang Lainnya","139.Pepaya"],  # new labels
    tickvals=["01167002-14","01165008-11","01162001","01162002-14","01167022-27"]                     # original values in the data
)

fig8.show()

/tmp/ipython-input-2846860918.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 09 Komoditas Minyak dan Kelapaa
import plotly.express as px
selected_cats9=["01154003","01167033"]
df_filtered9=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats9)]
df_filtered9["PerSatuan"]=(df_filtered9["KOLOM6"]/df_filtered9["KOLOM5"])
fig9 =px.box(df_filtered9,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig9.update_layout(
    xaxis_title="Komoditas Minyak dan Kelapa",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "09 Cek Outlier Nilai Konsumsi Minyak dan Kelapa",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig9.update_xaxes(
    ticktext=["155.Minyak Kelapa", "157.Kelapa"],  # new labels
    tickvals=["01154003","01167033"]                     # original values in the data
)

fig9.show()

/tmp/ipython-input-58342561.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 10 Komoditas Bahan Minuman
import plotly.express as px
selected_cats10=[160,161,162,163,164,165]
df_filtered10=df_kp1[df_kp1["NOURUTKOMO"].isin(selected_cats10)]
df_filtered10["PerSatuan"]=(df_filtered10["KOLOM6"]/df_filtered10["KOLOM5"])
fig10 =px.box(df_filtered10,x="NOURUTKOMO", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig10.update_layout(
    xaxis_title="Komoditas Bahan Minuman",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "10 Cek Outlier Nilai Konsumsi Bahan Minuman",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig10.update_xaxes(
    ticktext=["160.Gula Pasir","161.Gula Merah","162.Teh Bubuk","163.Teh Celup(sachet)","164.Kopi Bubuk","165.Kopi Instan (sachet)"],  # new labels
    tickvals=[160,161,162,163,164,165]                     # original values in the data
)

fig10.show()

/tmp/ipython-input-1195632254.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 11 Komoditas Bumbu-Bumbuan
import plotly.express as px
selected_cats11=["01192001","01192005","01194003/4"]
df_filtered11=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats11)]
df_filtered11["PerSatuan"]=(df_filtered11["KOLOM6"]/df_filtered11["KOLOM5"])
fig11 =px.box(df_filtered11,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig11.update_layout(
    xaxis_title="Komoditas Bumbu-Bumbuan",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "11 Cek Outlier Nilai Konsumsi Bumbu-Bumbuan",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig11.update_xaxes(
    ticktext=["168.Garam","169.Kemiri","175.Terasi/Petis"],  # new labels
    tickvals=["01192001","01192005","01194003/4"]                     # original values in the data
)

fig11.show()

/tmp/ipython-input-1267856501.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 12 Komoditas Makanan Lainnya
import plotly.express as px
selected_cats12=["01115012","01115018/19"]
df_filtered12=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats12)]
df_filtered12["PerSatuan"]=(df_filtered12["KOLOM6"]/df_filtered12["KOLOM5"])
fig12 =px.box(df_filtered12,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5"])
fig12.update_layout(
    xaxis_title="Komoditas Makanan Lainnya",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "12 Cek Outlier Nilai Konsumsi Bahan Makanan Lainnya",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig12.update_xaxes(
    ticktext=["183.Mie Instan","184.Kerupuk Mentah"],  # new labels
    tickvals=["01115012","01115018/19"]                     # original values in the data
)

fig12.show()

/tmp/ipython-input-736008867.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## Komoditas Makanan Jadi Lainnya
import plotly.express as px
selected_cats_mj=[188,189,190,191,221]
df_filtered_mj=df_kp2[df_kp2["NOURUTKOMO"].isin(selected_cats_mj)]
df_filtered_mj["NOURUTKOMO"]=df_filtered_mj["NOURUTKOMO"].astype(str)
df_filtered_mj["PerSatuan"]=(df_filtered_mj["KOLOM6"]/df_filtered_mj["KOLOM5"])


figmj =px.box(df_filtered_mj,x="NOURUTKOMO", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
figmj.update_layout(
    xaxis_title="Komoditas Makanan Jadi",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "13 Cek Outlier Makanan Jadi",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
figmj.update_xaxes(
    ticktext=["188.Roti Tawar","189.Roti Manis","190.Kue Kering","191.Kue Basah","221.Rokok"],  # new labels
    tickvals=[188,189,190,191,221]                     # original values in the data
)

figmj.show()

/tmp/ipython-input-3874145258.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-3874145258.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

## 04.2 Pemeriksaan Outlier Konsumsi Per **Kapita** Komoditas NonMakanan

In [ ]:
## A. PERUMAHAN DAN FASILITAS RUMAH TANGGA

import plotly.express as px
selected_cats13=[228,229,230,231,233,235]
df_filtered13=df_kp3[df_kp3["NOURUTKOMO"].isin(selected_cats13)]
df_filtered13["PerKapita"]=(df_filtered13["KOLOM5"]/df_filtered13["R301"])

fig13 =px.box(df_filtered13,x="NOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig13.update_layout(
    xaxis_title="Komoditas Perumahan dan Fasilitas Rumah Tangga (1)",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "13 Cek Outlier Nilai Konsumsi Perumahan DAN Fasilitas Rumah Tangga Sebulan terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig13.update_xaxes(
    ticktext=["228.Milik Sendiri","229.Kontrak Rumah","230.Sewa","231.Dinas/Lainnya"],  # new labels
    tickvals=[228,229,230,231,233,235]                     # original values in the data
)

fig13.show()

/tmp/ipython-input-921442838.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
import plotly.express as px
selected_cats13_2=[256,261]
df_filtered13_2=df_kp3[df_kp3["NOURUTKOMO"].isin(selected_cats13_2)]
df_filtered13_2["PerKapita"]=(df_filtered13_2["KOLOM5"]/df_filtered13_2["R301"])


fig13_2 =px.box(df_filtered13_2,x="NOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig13_2.update_layout(
    xaxis_title="Komoditas Perumahan dan Fasilitas Rumah Tangga (2)",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "13 Cek Outlier Nilai Konsumsi Perumahan dan Fasilitas Rumah Tangga Sebulan terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig13_2.update_xaxes(
    ticktext=["256.Minyak Tanah","261.Kayu Bakar"],  # new labels
    tickvals=[256,261]                     # original values in the data
)

fig13_2.show()

/tmp/ipython-input-2560613189.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
import plotly.express as px
selected_cats_bensin=[243]
df_filtered13_bensin=df_kp3[df_kp3["NOURUTKOMO"].isin(selected_cats_bensin)]
df_filtered13_bensin["PerKapita"]=(df_filtered13_bensin["KOLOM7"]/df_filtered13_bensin["R301"])


fig_bensin =px.box(df_filtered13_bensin,x="NOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig_bensin.update_layout(
    xaxis_title="Komoditas Perumahan dan Fasilitas Rumah Tangga (2.1)",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "13 Cek Outlier Nilai Konsumsi Bensin Rumah Tangga Sebulan terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig_bensin.update_xaxes(
    ticktext=["243.Bensin"],  # new labels
    tickvals=[243]                     # original values in the data
)

fig_bensin.show()

/tmp/ipython-input-2636284194.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
import plotly.express as px
selected_cats13_3=[262,265]
df_filtered13_3=df_kp3[df_kp3["NOURUTKOMO"].isin(selected_cats13_3)]
df_filtered13_3["PerKapita"]=(df_filtered13_3["KOLOM5"]/df_filtered13_3["R301"])


fig13_3 =px.box(df_filtered13_3,x="NOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig13_3.update_layout(
    xaxis_title="Komoditas Perumahan dan Fasilitas Rumah Tangga (3)",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "13 Cek Outlier Nilai Konsumsi Perumahan dan Fasilitas Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig13_3.update_xaxes(
    ticktext=["262.Obat Nyamuk, Korek Api, Baterai, Aki","265.Pos dan benda pos"],  # new labels
    tickvals=[262,265]                     # original values in the data
)

fig13_3.show()

/tmp/ipython-input-3455907328.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## B.1 ANEKA BARANG DAN JASA (SEBULAN TERAKHIR)

import plotly.express as px
selected_cats14=[269,270,271,272]
df_filtered14=df_kp3[df_kp3["NOURUTKOMO"].isin(selected_cats14)]
df_filtered14["PerKapita"]=(df_filtered14["KOLOM5"]/df_filtered14["R301"])


fig14 =px.box(df_filtered14,x="NOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig14.update_layout(
    xaxis_title="Aneka Barang dan Jasa",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "14 Cek Outlier Nilai Konsumsi Aneka Barang dan Jasa Rumah Tangga Sebulan terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig14.update_xaxes(
    ticktext=["269.Perlengkapan mandi","270.Barang Kecantikan","271.Perawatan kulit, muka, kuku, tambut","272.Sabun Cuci"],  # new labels
    tickvals=[269,270,271,272]                     # original values in the data
)

fig14.show()

/tmp/ipython-input-1880276902.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## B.2 ANEKA BARANG DAN JASA (Kesehatan)

import plotly.express as px
selected_cats15=[276,277,278,279,280,281,282,283,284,285,291]
df_filtered15=df_kp3[df_kp3["NOURUTKOMO"].isin(selected_cats15)]
df_filtered15["NOURUTKOMO"]=df_filtered15["NOURUTKOMO"].astype(str)
df_filtered15["PerKapita"]=(df_filtered15["KOLOM6"]/df_filtered15["R301"])


fig15 =px.box(df_filtered15,x="NOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig15.update_layout(
    xaxis_title="Aneka Barang dan Jasa",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "15 Cek Outlier Nilai Konsumsi Aneka Barang dan Jasa (Kesehatan) Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig15.update_xaxes(
    ticktext=["276","277","278","279","280","281","282","283","284","285","291"],  # new labels
    tickvals=[276,277,278,279,280,281,282,283,284,285,291]                     # original values in the data
)

fig15.show()

/tmp/ipython-input-3314295349.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-3314295349.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## B.3 ANEKA BARANG DAN JASA (Pendidikan)

import plotly.express as px
selected_cats16=[292,293,294,295,296]
df_filtered16=df_kp3[df_kp3["NOURUTKOMO"].isin(selected_cats16)]
df_filtered16["PerKapita"]=(df_filtered16["KOLOM6"]/df_filtered16["R301"])


fig16 =px.box(df_filtered16,x="NOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig16.update_layout(
    xaxis_title="Aneka Barang dan Jasa (Pendidikan)",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "16 Cek Outlier Nilai Konsumsi Aneka Barang dan Jasa (Pendidikan) Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig16.update_xaxes(
    ticktext=["292","293","294","295","296"],  # new labels
    tickvals=[292,293,294,295,296]                     # original values in the data
)

fig16.show()

/tmp/ipython-input-1869318374.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## B.4 ANEKA BARANG DAN JASA (Transportasi dan Jasa lainnya)

import plotly.express as px
selected_cats17=[298,299,300,301,306]
df_filtered17=df_kp3[df_kp3["NOURUTKOMO"].isin(selected_cats17)]
df_filtered17["NOURUTKOMO"]=df_filtered17["NOURUTKOMO"].astype(str)
df_filtered17["PerKapita"]=(df_filtered17["KOLOM6"]/df_filtered17["R301"])


fig17 =px.box(df_filtered17,x="NOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig17.update_layout(
    xaxis_title="Aneka Barang dan Jasa (Transportasi)",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "17 Cek Outlier Nilai Konsumsi Aneka Barang dan Jasa (Transportasi dan Jasa Lain) Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig17.update_xaxes(
    ticktext=["298","299","300","301","306"],  # new labels
    tickvals=[298,299,300,301,306]                     # original values in the data
)

fig17.show()

/tmp/ipython-input-4200197275.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-4200197275.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## C. PAKAIAN DAN ALAS KAKI

import plotly.express as px
selected_cats18=[308,309,310,312,313,314,315]
df_filtered18=df_kp3[df_kp3["NOURUTKOMO"].isin(selected_cats18)]
df_filtered18["NOURUTKOMO"]=df_filtered18["NOURUTKOMO"].astype(str)
df_filtered18["PerKapita"]=(df_filtered18["KOLOM6"]/df_filtered18["R301"])


fig18 =px.box(df_filtered18,x="NOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig18.update_layout(
    xaxis_title="PAKAIAN, ALAS KAKI, DAN TUTUP KEPALA",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "18 Cek Outlier Nilai Konsumsi PAKAIAN Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig18.update_xaxes(
    ticktext=["308","309","310","312","313","314","315"],  # new labels
    tickvals=[308,309,310,312,313,314,315]                     # original values in the data
)

fig18.show()

/tmp/ipython-input-1224532717.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-1224532717.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## D. BARANG TAHAN LAMA

import plotly.express as px
selected_cats19=[319,320,321,325,326,328]
df_filtered19=df_kp3[df_kp3["NOURUTKOMO"].isin(selected_cats19)]
df_filtered19["NOURUTKOMO"]=df_filtered19["NOURUTKOMO"].astype(str)
df_filtered19["PerKapita"]=(df_filtered19["KOLOM6"]/df_filtered19["R301"])


fig19 =px.box(df_filtered19,x="NOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig19.update_layout(
    xaxis_title="No Urut Komoditas Barang Tahan Lama",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "19 Cek Outlier Nilai Konsumsi BARANG TAHAN LAMA Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig19.update_xaxes(
    ticktext=["319","320","321","325","326","328"],  # new labels
    tickvals=[319,320,321,325,326,328]                     # original values in the data
)

fig19.show()

/tmp/ipython-input-813795842.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-813795842.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## E.PAJAK, PUNGUTAN, DAN ASURANSI dan KEPERLUAN PESTA DAN UPACARA/KENDURI

import plotly.express as px
selected_cats20=[335,336,337]
df_filtered20=df_kp3[df_kp3["NOURUTKOMO"].isin(selected_cats20)]
df_filtered20["PerKapita"]=(df_filtered20["KOLOM6"]/df_filtered20["R301"])


fig20 =px.box(df_filtered20,x="NOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig20.update_layout(
    xaxis_title="No Urut Komoditas PAJAK, PUNGUTAN, DAN ASURANSI ",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "20 Cek Outlier Nilai Konsumsi PAJAK, PUNGUTAN, DAN ASURANSI dan KEPERLUAN PESTA DAN UPACARA/KENDURI Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig20.update_xaxes(
    ticktext=["335","336","337","344","346"],  # new labels
    tickvals=[335,336,337,344,346]                     # original values in the data
)

fig20.show()

/tmp/ipython-input-1359843536.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## F. KEPERLUAN PESTA DAN UPACARA/KENDURI

import plotly.express as px
selected_cats21=[344,346]
df_filtered21=df_kp3[df_kp3["NOURUTKOMO"].isin(selected_cats21)]
df_filtered21["PerKapita"]=(df_filtered21["KOLOM6"]/df_filtered21["R301"])


fig21 =px.box(df_filtered21,x="NOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig21.update_layout(
    xaxis_title="No Urut Komoditas KEPERLUAN PESTA DAN UPACARA/KENDURI",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "21 Cek Outlier Nilai Konsumsi KEPERLUAN PESTA DAN UPACARA/KENDURI Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig21.update_xaxes(
    ticktext=["335","336","337","344","346"],  # new labels
    tickvals=[335,336,337,344,346]                     # original values in the data
)

fig21.show()

/tmp/ipython-input-1008935073.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

# **05 PEMERIKSAAN POPULASI REFERENSI HASIL PENDATAAN**

## 05.1 Menentukan Populasi Referensi

In [ ]:
# 1. Bagi ke dalam 100 persentil
df_kp9['perkapita']=df_kp9['B433R9K3']/df_kp9['R301']
df_kp9['persentil'] = pd.qcut(df_kp9['perkapita'], q=100, labels=False) + 1
df_kp9.sort_values(by="persentil", ascending=True, inplace=True)
df_kp9

# 2. Tentukan garis kemiskinan (664.127 per kapita/bulan)
garis_kemiskinan = 664127

# 3. Cari persentil di mana garis kemiskinan berada
all_quantiles = np.percentile(df_kp9['perkapita'], np.arange(1,101))
persentil_gk_alt = np.searchsorted(all_quantiles, garis_kemiskinan) + 1
print(f"Garis kemiskinan jatuh pada persentil ke: {persentil_gk_alt}")

# 4. Cari rumah tangga yang berada 20 persentil di atas garis kemiskinan
# Filter data yang persentilnya di atas 7
filtered = df_kp9[df_kp9["persentil"] > persentil_gk_alt]

#  Hitung 20% dari jumlah baris hasil
n_rows = int(len(df_kp9) * 0.2)

# buat dataframe Populasi Referensi
populasi_referensi = filtered.head(n_rows)
populasi_referensi["ID_ruta"]=populasi_referensi["NKS"].astype(str) +populasi_referensi["NURT"].astype(str)
populasi_referensi["PopRef"]="1"
populasi_referensi
populasi_referensi.to_excel('/content/drive/My Drive/Folder Mantan SOSIAL1507/07. Kegiatan Teknis 2025/12 SUSENAS September/03 Pasca Lapangan/01 Evaluasi Kabupaten Tanjung Jabung Barat/[Populasi Referensi].xlsx', index=False)

/tmp/ipython-input-3129624615.py:24: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-3129624615.py:25: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Garis kemiskinan jatuh pada persentil ke: 5

## 05.2 Pengecekan Konsumsi perkapita perminggu Basket Commodity Populasi Referensi

In [ ]:
## 01 Komoditas Padi-Padian
import plotly.express as px
selected_cats=["01111001","01111003","01111005/2","01115005"]
df_filtered=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats)]
df_poprefmerge=pd.merge(df_filtered,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_padi=df_poprefmerge[df_poprefmerge["PopRef"]=="1"]
popref_padi["PerSatuan"]=(popref_padi["KOLOM6"]/popref_padi["R301"])
fig =px.box(popref_padi,x="KODECOICOP", y=popref_padi["PerSatuan"], hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig.update_layout(
    xaxis_title="Padi-padian",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "01 Cek Outlier Konsumsi Padi-Padian",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig.update_xaxes(
    ticktext=["2. Beras", "3. Beras Ketan","5. Jagung pipilan/beras jagung/jagung titi","6. Tepung Terigu"],  # new labels
    tickvals=["01111001","01111003","01111005/2","01115005"]                     # original values in the data
)

fig.show()

/tmp/ipython-input-2960122095.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 02 Komoditas Umbi-Umbian
import plotly.express as px
selected_cats2=["01178001","01178002","01178001"]
df_filtered2=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats2)]
df_poprefmerge2=pd.merge(df_filtered2,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')

popref_umbi=df_poprefmerge2[df_poprefmerge2["PopRef"]=="1"]
popref_umbi["PerSatuan"]=(popref_umbi["KOLOM6"]/popref_umbi["R301"])
fig2 =px.box(popref_umbi,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig2.update_layout(
    xaxis_title="Umbi-Umbian",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "02 Cek Outlier Konsumsi Umbi-Umbian",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig2.update_xaxes(
    ticktext=["9.Ketela pohon/singkong", "10.Ketela rambat/ubi jalar","14.Gaplek"],  # new labels
    tickvals=["01178001","01178002","01178001"]                     # original values in the data
)

fig2.show()

/tmp/ipython-input-3311337746.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 03 Komoditas IKAN/UDANG/CUMI
import plotly.express as px
selected_cats3=["01131069","01131072","01131013","01131028","01131067","01131003","01131045","01133032"]
df_filtered3=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats3)]
df_poprefmerge3=pd.merge(df_filtered3,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')

popref_ikan=df_poprefmerge3[df_poprefmerge3["PopRef"]=="1"]
popref_ikan["PerSatuan"]=(popref_ikan["KOLOM6"]/popref_ikan["R301"])


fig3 =px.box(popref_ikan,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig3.update_layout(
    xaxis_title="Umbi-Umbian",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "03 Cek Outlier Konsumsi IKAN/UDANG/CUMI",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig3.update_xaxes(
    ticktext=["18. Tongkol", "19.Tuna","20.Cakalang,dencis","23. Kembung","24.Teri Basah","25.Bandeng","27.Mujair","51.Teri Diawetkan"],  # new labels
    tickvals=["01131069","01131072","01131013","01131028","01131067","01131003","01131045","01133032"]                     # original values in the data
)

fig3.show()

/tmp/ipython-input-3494772932.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 04 Komoditas DAGING
import plotly.express as px
selected_cats4=["01121001","01122001","01124003","01124002","01121005"]
df_filtered4=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats4)]
df_poprefmerge4=pd.merge(df_filtered4,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')

popref_daging=df_poprefmerge4[df_poprefmerge4["PopRef"]=="1"]
popref_daging["PerSatuan"]=(popref_daging["KOLOM6"]/popref_daging["R301"])


fig4 =px.box(popref_daging,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig4.update_layout(
    xaxis_title="Daging",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "04 Cek Outlier Konsumsi DAGING",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig4.update_xaxes(
    ticktext=["62. Daging Sapi", "65. Daging Babi","66.Daging Ayam Ras","67. Daging Ayam Kampung","72.Tetelan"],  # new labels
    tickvals=["01121001","01122001","01124003","01124002","01121005"]                     # original values in the data
)

fig4.show()

/tmp/ipython-input-2251882949.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 05 Komoditas Telur dan Susu
import plotly.express as px
selected_cats5=["01147002","01147003","01143005","01143001/2"]
df_filtered5=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats5)]
df_poprefmerge5=pd.merge(df_filtered5,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_telur_susu=df_poprefmerge5[df_poprefmerge5["PopRef"]=="1"]
popref_telur_susu["PerSatuan"]=(popref_telur_susu["KOLOM6"]/popref_telur_susu["R301"])

fig5 =px.box(popref_telur_susu,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig5.update_layout(
    xaxis_title="Daging",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "05 Cek Outlier Konsumsi Telur dan SUsu",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig5.update_xaxes(
    ticktext=["75. Telur Ayam Ras", "77. Telur Itik/Telur Itik Manila","80. Kental Manis","81. Susu Bubuk"],  # new labels
    tickvals=["01147002","01147003","01143005","01143001/2"]                     # original values in the data
)

fig5.show()

/tmp/ipython-input-3198019023.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 06 Komoditas Sayur
import plotly.express as px
selected_cats6=["01171012","01173003","01173008","01173005","01171010","01173017","01174006","01173012","01173013"]
df_filtered6=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats6)]
df_poprefmerge6=pd.merge(df_filtered6,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_sayur=df_poprefmerge6[df_poprefmerge6["PopRef"]=="1"]
popref_sayur["PerSatuan"]=(popref_sayur["KOLOM6"]/popref_sayur["R301"])

fig6 =px.box(popref_sayur,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig6.update_layout(
    xaxis_title="Komoditas Sayur",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "06 Cek Outlier Konsumsi Sayur-Sayuran",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig6.update_xaxes(
    ticktext=["86.Bayam", "91.Buncis","92. Kacang Panjang","93.Tomat","96.Daun Ketela Pohon","102.Nangka Muda","105.Bawang Merah","108.Cabe Merah","110.Cabe Rawit"],  # new labels
    tickvals=["01171012","01173003","01173008","01173005","01171010","01173017","01174006","01173012","01173013"]                     # original values in the data
)

fig6.show()

/tmp/ipython-input-1589102191.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 07 Komoditas Kacang-Kacangan
import plotly.express as px
selected_cats7=["01168010","01194011","01194013"]
df_filtered7=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats7)]
df_poprefmerge7=pd.merge(df_filtered7,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_kacangkacangan=df_poprefmerge7[df_poprefmerge7["PopRef"]=="1"]
popref_kacangkacangan["PerSatuan"]=(popref_kacangkacangan["KOLOM6"]/popref_kacangkacangan["R301"])

fig7 =px.box(popref_kacangkacangan,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig7.update_layout(
    xaxis_title="Komoditas Kacang-Kacangan",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "07 Cek Outlier Nilai Konsumsi Kacang-Kacangan",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig7.update_xaxes(
    ticktext=["122.Kacang Tanah Tanpa Kulit", "125.Tahu","126.Tempe"],  # new labels
    tickvals=["01168010","01194011","01194013"]                     # original values in the data
)

fig7.show()

/tmp/ipython-input-570471556.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 08 Komoditas Buah-Buahan
import plotly.express as px
selected_cats8=["01167002-14","01165008-11","01162001","01162002-14","01167022-27"]
df_filtered8=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats8)]
df_poprefmerge8=pd.merge(df_filtered8,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_buah=df_poprefmerge8[df_poprefmerge8["PopRef"]=="1"]
popref_buah["PerSatuan"]=(popref_buah["KOLOM6"]/popref_buah["R301"])


fig8 =px.box(popref_buah,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig8.update_layout(
    xaxis_title="Komoditas Buah-buahan",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "08 Cek Outlier Nilai Konsumsi Buah-buahan",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig8.update_xaxes(
    ticktext=["131.Mangga", "136.Salak","137.Pisang","138.Pisang Lainnya","139.Pepaya"],  # new labels
    tickvals=["01167002-14","01165008-11","01162001","01162002-14","01167022-27"]                     # original values in the data
)

fig8.show()

/tmp/ipython-input-1144459188.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 09 Komoditas Minyak dan Kelapaa
import plotly.express as px
selected_cats9=["01154003","01167033"]
df_filtered9=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats9)]
df_poprefmerge9=pd.merge(df_filtered9,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_minyak_kelapa=df_poprefmerge9[df_poprefmerge9["PopRef"]=="1"]
popref_minyak_kelapa["PerSatuan"]=(popref_minyak_kelapa["KOLOM6"]/popref_minyak_kelapa["R301"])


fig9 =px.box(popref_minyak_kelapa,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig9.update_layout(
    xaxis_title="Komoditas Minyak dan Kelapa",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "09 Cek Outlier Nilai Konsumsi Minyak dan Kelapa",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig9.update_xaxes(
    ticktext=["155.Minyak Kelapa", "157.Kelapa"],  # new labels
    tickvals=["01154003","01167033"]                     # original values in the data
)

fig9.show()

/tmp/ipython-input-614639311.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 10 Komoditas Bahan Minuman
import plotly.express as px
selected_cats10=[160,161,162,163,164,165]
df_filtered10=df_kp1[df_kp1["NOURUTKOMO"].isin(selected_cats10)]
df_poprefmerge10=pd.merge(df_filtered10,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_bahanminum=df_poprefmerge10[df_poprefmerge10["PopRef"]=="1"]
popref_bahanminum["PerSatuan"]=(popref_bahanminum["KOLOM6"]/popref_bahanminum["R301"])


fig10 =px.box(popref_bahanminum,x="NOURUTKOMO", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig10.update_layout(
    xaxis_title="Komoditas Bahan Minuman",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "10 Cek Outlier Nilai Konsumsi Bahan Minuman",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig10.update_xaxes(
    ticktext=["160.Gula Pasir","161.Gula Merah","162.Teh Bubuk","163.Teh Celup(sachet)","164.Kopi Bubuk","165.Kopi Instan (sachet)"],  # new labels
    tickvals=[160,161,162,163,164,165]                     # original values in the data
)

fig10.show()

/tmp/ipython-input-710097308.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 11 Komoditas Bumbu-Bumbuan
import plotly.express as px
selected_cats11=["01192001","01192005","01194003/4"]
df_filtered11=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats11)]
df_poprefmerge11=pd.merge(df_filtered11,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_bumbu=df_poprefmerge11[df_poprefmerge11["PopRef"]=="1"]
popref_bumbu["PerSatuan"]=(popref_bumbu["KOLOM6"]/popref_bumbu["R301"])


fig11 =px.box(popref_bumbu,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig11.update_layout(
    xaxis_title="Komoditas Bumbu-Bumbuan",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "11 Cek Outlier Nilai Konsumsi Bumbu-Bumbuan",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig11.update_xaxes(
    ticktext=["168.Garam","169.Kemiri","175.Terasi/Petis"],  # new labels
    tickvals=["01192001","01192005","01194003/4"]                     # original values in the data
)

fig11.show()

/tmp/ipython-input-3710322005.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 12 Komoditas Makanan Lainnya
import plotly.express as px
selected_cats12=["01115012","01115018/19"]
df_filtered12=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats12)]
df_poprefmerge12=pd.merge(df_filtered12,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_bahanmakanan=df_poprefmerge12[df_poprefmerge12["PopRef"]=="1"]
popref_bahanmakanan["PerSatuan"]=(popref_bahanmakanan["KOLOM6"]/popref_bahanmakanan["R301"])


fig12 =px.box(popref_bahanmakanan,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig12.update_layout(
    xaxis_title="Komoditas Makanan Lainnya",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "12 Cek Outlier Nilai Konsumsi Bahan Makanan Lainnya",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig12.update_xaxes(
    ticktext=["183.Mie Instan","184.Kerupuk Mentah"],  # new labels
    tickvals=["01115012","01115018/19"]                     # original values in the data
)

fig12.show()

/tmp/ipython-input-2627922130.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## Komoditas Makanan Jadi Lainnya
import plotly.express as px
selected_cats_mj=[188,189,190,191,221]
df_filtered_mj=df_kp2[df_kp2["NOURUTKOMO"].isin(selected_cats_mj)]
df_filtered_mj["NOURUTKOMO"]=df_filtered_mj["NOURUTKOMO"].astype(str)
df_poprefmerge_mj=pd.merge(df_filtered_mj,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_mj=df_poprefmerge_mj[df_poprefmerge_mj["PopRef"]=="1"]
popref_mj["PerSatuan"]=(popref_mj["KOLOM6"]/popref_mj["R301"])


figmj =px.box(popref_mj,x="NOURUTKOMO", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
figmj.update_layout(
    xaxis_title="Komoditas Makanan Jadi",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "Cek Outlier Makanan Jadi",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
figmj.update_xaxes(
    ticktext=["188.Roti Tawar","189.Roti Manis","190.Kue Kering","191.Kue Basah","221.Rokok"],  # new labels
    tickvals=[188,189,190,191,221]                     # original values in the data
)

figmj.show()

/tmp/ipython-input-3950033940.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-3950033940.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## A. PERUMAHAN DAN FASILITAS RUMAH TANGGA

import plotly.express as px
selected_cats13=[228,229,230,231,233,235]
df_filtered13=kp3_full[kp3_full["NOMOURUTKOMO"].isin(selected_cats13)]
df_poprefmerge13=pd.merge(df_filtered13,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
df_poprefmerge13_2=pd.merge(df_poprefmerge13,df_kor_rt[["M301","NAMAKECAMA","NAMAKRT","ID_ruta"]],on="ID_ruta",how='left')
popref_rumah_fasilitas=df_poprefmerge13_2[df_poprefmerge13_2["PopRef"]=="1"]
popref_rumah_fasilitas["PerKapita"]=(popref_rumah_fasilitas["KOLOM5"]/popref_rumah_fasilitas["M301"])


fig13 =px.box(popref_rumah_fasilitas,x="NOMOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","M301","KOLOM5","KOLOM6"])
fig13.update_layout(
    xaxis_title="Komoditas Perumahan dan Fasilitas Rumah Tangga (1)",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "13 Cek Outlier Nilai Konsumsi Perumahan dadn Fasilitas Rumah Tangga Sebulan terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig13.update_xaxes(
    ticktext=["228.Milik Sendiri","229.Kontrak Rumah","230.Sewa","231.Dinas/Lainnya"],  # new labels
    tickvals=[228,229,230,231,233,235]                     # original values in the data
)

fig13.show()

/tmp/ipython-input-1598810697.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
import plotly.express as px
selected_cats13_2=[256,261]
df_filtered13_2=kp3_full[kp3_full["NOMOURUTKOMO"].isin(selected_cats13_2)]
df_poprefmerge13_2_1=pd.merge(df_filtered13_2,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
df_poprefmerge13_2_2=pd.merge(df_poprefmerge13_2_1,df_kor_rt[["M301","NAMAKECAMA","NAMAKRT","ID_ruta"]],on="ID_ruta",how='left')
popref_rumah_fasilitas_2=df_poprefmerge13_2_2[df_poprefmerge13_2_2["PopRef"]=="1"]
popref_rumah_fasilitas_2["PerKapita"]=(popref_rumah_fasilitas_2["KOLOM5"]/popref_rumah_fasilitas_2["M301"])


fig13_2 =px.box(popref_rumah_fasilitas_2,x="NOMOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","M301","KOLOM5","KOLOM6"])
fig13_2.update_layout(
    xaxis_title="Komoditas Perumahan dan Fasilitas Rumah Tangga (2)",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "13 Cek Outlier Nilai Konsumsi Perumahan dan Fasilitas Rumah Tangga Sebulan terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig13_2.update_xaxes(
    ticktext=["256.Minyak Tanah","261.Kayu Bakar"],  # new labels
    tickvals=[256,261]                     # original values in the data
)

fig13_2.show()

/tmp/ipython-input-1296008163.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
import plotly.express as px
selected_cats_bensin=[243]
df_filtered13_bensin=kp3_full[kp3_full["NOMOURUTKOMO"].isin(selected_cats_bensin)]
df_poprefmerge_bensin=pd.merge(df_filtered13_bensin,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
df_filtered13_bensin_2=pd.merge(df_poprefmerge_bensin,df_kor_rt[["M301","NAMAKECAMA","NAMAKRT","ID_ruta"]],on="ID_ruta",how='left')
popref_bensin=df_filtered13_bensin_2[df_filtered13_bensin_2["PopRef"]=="1"]
popref_bensin["PerKapita"]=(popref_bensin["KOLOM7"]/popref_bensin["M301"])


fig_bensin =px.box(popref_bensin,x="NOMOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","M301","KOLOM5","KOLOM6"])
fig_bensin.update_layout(
    xaxis_title="Komoditas Perumahan dan Fasilitas Rumah Tangga (2.1)",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "13 Cek Outlier Nilai Konsumsi Bensin Rumah Tangga Sebulan terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig_bensin.update_xaxes(
    ticktext=["243.Bensin"],  # new labels
    tickvals=[243]                     # original values in the data
)

fig_bensin.show()

/tmp/ipython-input-3479576175.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
import plotly.express as px
selected_cats13_3=[262,265]
df_filtered13_3=kp3_full[kp3_full["NOMOURUTKOMO"].isin(selected_cats13_3)]
df_poprefmerge13_2_3=pd.merge(df_filtered13_3,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
df_poprefmerge13_2_4=pd.merge(df_poprefmerge13_2_3,df_kor_rt[["M301","NAMAKECAMA","NAMAKRT","ID_ruta"]],on="ID_ruta",how='left')
popref_rumah_fasilitas_3=df_poprefmerge13_2_4[df_poprefmerge13_2_4["PopRef"]=="1"]
popref_rumah_fasilitas_3["PerKapita"]=(popref_rumah_fasilitas_3["KOLOM5"]/popref_rumah_fasilitas_3["M301"])


fig13_3 =px.box(popref_rumah_fasilitas_3,x="NOMOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","M301","KOLOM5","KOLOM6"])
fig13_3.update_layout(
    xaxis_title="Komoditas Perumahan dan Fasilitas Rumah Tangga (3)",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "13 Cek Outlier Nilai Konsumsi Perumahan dan Fasilitas Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig13_3.update_xaxes(
    ticktext=["262.Obat Nyamuk, Korek Api, Baterai, Aki","265.Pos dan benda pos"],  # new labels
    tickvals=[262,265]                     # original values in the data
)

fig13_3.show()

/tmp/ipython-input-1221653198.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## B.1 ANEKA BARANG DAN JASA (SEBULAN TERAKHIR)

import plotly.express as px
selected_cats14=[269,270,271,272]
df_filtered14=kp3_full[kp3_full["NOMOURUTKOMO"].isin(selected_cats14)]
df_poprefmerge14=pd.merge(df_filtered14,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
df_poprefmerge14_2=pd.merge(df_poprefmerge14,df_kor_rt[["M301","NAMAKECAMA","NAMAKRT","ID_ruta"]],on="ID_ruta",how='left')
popref_ABJ_sebulan=df_poprefmerge14_2[df_poprefmerge14_2["PopRef"]=="1"]
popref_ABJ_sebulan["PerKapita"]=(popref_ABJ_sebulan["KOLOM5"]/popref_ABJ_sebulan["M301"])


fig14 =px.box(popref_ABJ_sebulan,x="NOMOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","M301","KOLOM5","KOLOM6"])
fig14.update_layout(
    xaxis_title="Aneka Barang dan Jasa",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "14 Cek Outlier Nilai Konsumsi Aneka Barang dan Jasa Rumah Tangga Sebulan terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig14.update_xaxes(
    ticktext=["269.Perlengkapan mandi","270.Barang Kecantikan","271.Perawatan kulit, muka, kuku, tambut","272.Sabun Cuci"],  # new labels
    tickvals=[269,270,271,272]                     # original values in the data
)

fig14.show()

/tmp/ipython-input-1598922165.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## B.2 ANEKA BARANG DAN JASA (Kesehatan)

import plotly.express as px
selected_cats15=[276,277,278,279,280,281,282,283,284,285,291]
df_filtered15=kp3_full[kp3_full["NOMOURUTKOMO"].isin(selected_cats15)]
df_filtered15["NOMOURUTKOMO"]=df_filtered15["NOMOURUTKOMO"].astype(str)
df_poprefmerge15=pd.merge(df_filtered15,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
df_poprefmerge15_2=pd.merge(df_poprefmerge15,df_kor_rt[["M301","NAMAKECAMA","NAMAKRT","ID_ruta"]],on="ID_ruta",how='left')
popref_ABJ_kesehatan=df_poprefmerge15_2[df_poprefmerge15_2["PopRef"]=="1"]
popref_ABJ_kesehatan["PerKapita"]=(popref_ABJ_kesehatan["KOLOM6"]/popref_ABJ_kesehatan["M301"])


fig15 =px.box(popref_ABJ_kesehatan,x="NOMOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","M301","KOLOM5","KOLOM6"])
fig15.update_layout(
    xaxis_title="Aneka Barang dan Jasa",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "15 Cek Outlier Nilai Konsumsi Aneka Barang dan Jasa (Kesehatan) Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig15.update_xaxes(
    ticktext=["276","277","278","279","280","281","282","283","284","285","291"],  # new labels
    tickvals=[276,277,278,279,280,281,282,283,284,285,291]                     # original values in the data
)

fig15.show()

/tmp/ipython-input-219811929.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-219811929.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## B.3 ANEKA BARANG DAN JASA (Pendidikan)

import plotly.express as px
selected_cats16=[292,293,294,295,296]
df_filtered16=kp3_full[kp3_full["NOMOURUTKOMO"].isin(selected_cats16)]
df_poprefmerge16=pd.merge(df_filtered16,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
df_poprefmerge16_2=pd.merge(df_poprefmerge16,df_kor_rt[["M301","NAMAKECAMA","NAMAKRT","ID_ruta"]],on="ID_ruta",how='left')
popref_ABJ_pendidikan=df_poprefmerge16_2[df_poprefmerge16_2["PopRef"]=="1"]
popref_ABJ_pendidikan["PerKapita"]=(popref_ABJ_pendidikan["KOLOM6"]/popref_ABJ_pendidikan["M301"])


fig16 =px.box(popref_ABJ_pendidikan,x="NOMOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","M301","KOLOM5","KOLOM6"])
fig16.update_layout(
    xaxis_title="Aneka Barang dan Jasa (Pendidikan)",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "16 Cek Outlier Nilai Konsumsi Aneka Barang dan Jasa (Pendidikan) Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig16.update_xaxes(
    ticktext=["292","293","294","295","296"],  # new labels
    tickvals=[292,293,294,295,296]                     # original values in the data
)

fig16.show()

/tmp/ipython-input-2082528192.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## B.4 ANEKA BARANG DAN JASA (Transportasi dan Jasa lainnya)

import plotly.express as px
selected_cats17=[298,299,300,301,306]
df_filtered17=kp3_full[kp3_full["NOMOURUTKOMO"].isin(selected_cats17)]
df_filtered17["NOMOURUTKOMO"]=df_filtered17["NOMOURUTKOMO"].astype(str)
df_poprefmerge17=pd.merge(df_filtered17,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
df_poprefmerge17_2=pd.merge(df_poprefmerge17,df_kor_rt[["M301","NAMAKECAMA","NAMAKRT","ID_ruta"]],on="ID_ruta",how='left')
popref_ABJ_transportasi=df_poprefmerge17_2[df_poprefmerge17_2["PopRef"]=="1"]
popref_ABJ_transportasi["PerKapita"]=(popref_ABJ_transportasi["KOLOM6"]/popref_ABJ_transportasi["M301"])


fig17 =px.box(popref_ABJ_transportasi,x="NOMOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","M301","KOLOM5","KOLOM6"])
fig17.update_layout(
    xaxis_title="Aneka Barang dan Jasa (Transportasi)",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "17 Cek Outlier Nilai Konsumsi Aneka Barang dan Jasa (Transportasi dan Jasa Lain) Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig17.update_xaxes(
    ticktext=["298","299","300","301","306"],  # new labels
    tickvals=[298,299,300,301,306]                     # original values in the data
)

fig17.show()

/tmp/ipython-input-2495661986.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-2495661986.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## C. PAKAIAN DAN ALAS KAKI

import plotly.express as px
selected_cats18=[308,309,310,312,313,314,315]
df_filtered18=kp3_full[kp3_full["NOMOURUTKOMO"].isin(selected_cats18)]
df_filtered18["NOMOURUTKOMO"]=df_filtered18["NOMOURUTKOMO"].astype(str)
df_poprefmerge18=pd.merge(df_filtered18,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
df_poprefmerge18_2=pd.merge(df_poprefmerge18,df_kor_rt[["M301","NAMAKECAMA","NAMAKRT","ID_ruta"]],on="ID_ruta",how='left')
popref_PAKAIAN=df_poprefmerge18_2[df_poprefmerge18_2["PopRef"]=="1"]
popref_PAKAIAN["PerKapita"]=(popref_PAKAIAN["KOLOM6"]/popref_PAKAIAN["M301"])


fig18 =px.box(popref_PAKAIAN,x="NOMOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","M301","KOLOM5","KOLOM6"])
fig18.update_layout(
    xaxis_title="PAKAIAN, ALAS KAKI, DAN TUTUP KEPALA",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "18 Cek Outlier Nilai Konsumsi PAKAIAN Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig18.update_xaxes(
    ticktext=["308","309","310","312","313","314","315"],  # new labels
    tickvals=[308,309,310,312,313,314,315]                     # original values in the data
)

fig18.show()

/tmp/ipython-input-1300940503.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-1300940503.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## D. BARANG TAHAN LAMA

import plotly.express as px
selected_cats19=[319,320,321,325,326,328]
df_filtered19=kp3_full[kp3_full["NOMOURUTKOMO"].isin(selected_cats19)]
df_filtered19["NOMOURUTKOMO"]=df_filtered19["NOMOURUTKOMO"].astype(str)
df_poprefmerge19=pd.merge(df_filtered19,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
df_poprefmerge19_2=pd.merge(df_poprefmerge19,df_kor_rt[["M301","NAMAKECAMA","NAMAKRT","ID_ruta"]],on="ID_ruta",how='left')
popref_BARANGTAHANLAMA=df_poprefmerge19_2[df_poprefmerge19_2["PopRef"]=="1"]
popref_BARANGTAHANLAMA["PerKapita"]=(popref_BARANGTAHANLAMA["KOLOM6"]/popref_BARANGTAHANLAMA["M301"])


fig19 =px.box(popref_BARANGTAHANLAMA,x="NOMOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","M301","KOLOM5","KOLOM6"])
fig19.update_layout(
    xaxis_title="No Urut Komoditas Barang Tahan Lama",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "19 Cek Outlier Nilai Konsumsi BARANG TAHAN LAMA Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig19.update_xaxes(
    ticktext=["319","320","321","325","326","328"],  # new labels
    tickvals=[319,320,321,325,326,328]                     # original values in the data
)

fig19.show()

/tmp/ipython-input-773101986.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-773101986.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## E.PAJAK, PUNGUTAN, DAN ASURANSI dan KEPERLUAN PESTA DAN UPACARA/KENDURI

import plotly.express as px
selected_cats20=[335,336,337]
df_filtered20=kp3_full[kp3_full["NOMOURUTKOMO"].isin(selected_cats20)]
df_poprefmerge20=pd.merge(df_filtered20,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
df_poprefmerge20_2=pd.merge(df_poprefmerge20,df_kor_rt[["M301","NAMAKECAMA","NAMAKRT","ID_ruta"]],on="ID_ruta",how='left')
popref_E=df_poprefmerge20_2[df_poprefmerge20_2["PopRef"]=="1"]
popref_E["PerKapita"]=(popref_E["KOLOM6"]/popref_E["M301"])


fig20 =px.box(popref_E,x="NOMOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","M301","KOLOM5","KOLOM6"])
fig20.update_layout(
    xaxis_title="No Urut Komoditas PAJAK, PUNGUTAN, DAN ASURANSI ",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "20 Cek Outlier Nilai Konsumsi PAJAK, PUNGUTAN, DAN ASURANSI dan KEPERLUAN PESTA DAN UPACARA/KENDURI Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig20.update_xaxes(
    ticktext=["335","336","337","344","346"],  # new labels
    tickvals=[335,336,337,344,346]                     # original values in the data
)

fig20.show()

/tmp/ipython-input-121158650.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## F. KEPERLUAN PESTA DAN UPACARA/KENDURI

import plotly.express as px
selected_cats21=[344,346]
df_filtered21=kp3_full[kp3_full["NOMOURUTKOMO"].isin(selected_cats21)]
df_poprefmerge21=pd.merge(df_filtered21,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
df_poprefmerge21_2=pd.merge(df_poprefmerge21,df_kor_rt[["M301","NAMAKECAMA","NAMAKRT","ID_ruta"]],on="ID_ruta",how='left')
popref_F=df_poprefmerge21_2[df_poprefmerge21_2["PopRef"]=="1"]
popref_F["PerKapita"]=(popref_F["KOLOM6"]/popref_F["M301"])


fig21 =px.box(popref_F,x="NOMOURUTKOMO", y="PerKapita", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","M301","KOLOM5","KOLOM6"])
fig21.update_layout(
    xaxis_title="No Urut KomoditasKEPERLUAN PESTA DAN UPACARA/KENDURI",
    yaxis_title="Nilai konsumsi per kapita(dalam Rupiah)",
    title={
        "text": "21 Cek Outlier Nilai Konsumsi KEPERLUAN PESTA DAN UPACARA/KENDURI Rumah Tangga Setahun terakhir",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig21.update_xaxes(
    ticktext=["335","336","337","344","346"],  # new labels
    tickvals=[335,336,337,344,346]                     # original values in the data
)

fig21.show()

/tmp/ipython-input-3259352717.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

## 05.3 Pengecekan Harga Persatuan Basket Commodity Populasi Referensi

In [ ]:
## 01 Komoditas Padi-Padian
import plotly.express as px
selected_cats=["01111001","01111003","01111005/2","01115005"]
df_filtered=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats)]
df_poprefmerge=pd.merge(df_filtered,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_padi=df_poprefmerge[df_poprefmerge["PopRef"]=="1"]
popref_padi["PerSatuan"]=(popref_padi["KOLOM6"]/popref_padi["KOLOM5"])
fig =px.box(popref_padi,x="KODECOICOP", y=popref_padi["PerSatuan"], hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig.update_layout(
    xaxis_title="Padi-padian",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "01 Cek Outlier Konsumsi Padi-Padian",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig.update_xaxes(
    ticktext=["2. Beras", "3. Beras Ketan","5. Jagung pipilan/beras jagung/jagung titi","6. Tepung Terigu"],  # new labels
    tickvals=["01111001","01111003","01111005/2","01115005"]                     # original values in the data
)

fig.show()

/tmp/ipython-input-533089829.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 02 Komoditas Umbi-Umbian
import plotly.express as px
selected_cats2=["01178001","01178002","01178001"]
df_filtered2=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats2)]
df_poprefmerge2=pd.merge(df_filtered2,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')

popref_umbi=df_poprefmerge2[df_poprefmerge2["PopRef"]=="1"]
popref_umbi["PerSatuan"]=(popref_umbi["KOLOM6"]/popref_umbi["KOLOM5"])
fig2 =px.box(popref_umbi,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig2.update_layout(
    xaxis_title="Umbi-Umbian",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "02 Cek Outlier Konsumsi Umbi-Umbian",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig2.update_xaxes(
    ticktext=["9.Ketela pohon/singkong", "10.Ketela rambat/ubi jalar","14.Gaplek"],  # new labels
    tickvals=["01178001","01178002","01178001"]                     # original values in the data
)

fig2.show()

/tmp/ipython-input-599510522.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 03 Komoditas IKAN/UDANG/CUMI
import plotly.express as px
selected_cats3=["01131069","01131072","01131013","01131028","01131067","01131003","01131045","01133032"]
df_filtered3=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats3)]
df_poprefmerge3=pd.merge(df_filtered3,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')

popref_ikan=df_poprefmerge3[df_poprefmerge3["PopRef"]=="1"]
popref_ikan["PerSatuan"]=(popref_ikan["KOLOM6"]/popref_ikan["KOLOM5"])


fig3 =px.box(popref_ikan,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig3.update_layout(
    xaxis_title="Umbi-Umbian",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "03 Cek Outlier Konsumsi IKAN/UDANG/CUMI",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig3.update_xaxes(
    ticktext=["18. Tongkol", "19.Tuna","20.Cakalang,dencis","23. Kembung","24.Teri Basah","25.Bandeng","27.Mujair","51.Teri Diawetkan"],  # new labels
    tickvals=["01131069","01131072","01131013","01131028","01131067","01131003","01131045","01133032"]                     # original values in the data
)

fig3.show()

/tmp/ipython-input-2826946006.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 04 Komoditas DAGING
import plotly.express as px
selected_cats4=["01121001","01122001","01124003","01124002","01121005"]
df_filtered4=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats4)]
df_poprefmerge4=pd.merge(df_filtered4,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')

popref_daging=df_poprefmerge4[df_poprefmerge4["PopRef"]=="1"]
popref_daging["PerSatuan"]=(popref_daging["KOLOM6"]/popref_daging["KOLOM5"])


fig4 =px.box(popref_daging,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig4.update_layout(
    xaxis_title="Daging",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "04 Cek Outlier Konsumsi DAGING",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig4.update_xaxes(
    ticktext=["62. Daging Sapi", "65. Daging Babi","66.Daging Ayam Ras","67. Daging Ayam Kampung","72.Tetelan"],  # new labels
    tickvals=["01121001","01122001","01124003","01124002","01121005"]                     # original values in the data
)

fig4.show()

/tmp/ipython-input-4203664711.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 05 Komoditas Telur dan Susu
import plotly.express as px
selected_cats5=["01147002","01147003","01143005","01143001/2"]
df_filtered5=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats5)]
df_poprefmerge5=pd.merge(df_filtered5,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_telur_susu=df_poprefmerge5[df_poprefmerge5["PopRef"]=="1"]
popref_telur_susu["PerSatuan"]=(popref_telur_susu["KOLOM6"]/popref_telur_susu["KOLOM5"])

fig5 =px.box(popref_telur_susu,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig5.update_layout(
    xaxis_title="Daging",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "05 Cek Outlier Konsumsi Telur dan SUsu",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig5.update_xaxes(
    ticktext=["75. Telur Ayam Ras", "77. Telur Itik/Telur Itik Manila","80. Kental Manis","81. Susu Bubuk"],  # new labels
    tickvals=["01147002","01147003","01143005","01143001/2"]                     # original values in the data
)

fig5.show()

/tmp/ipython-input-98939047.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 06 Komoditas Sayur
import plotly.express as px
selected_cats6=["01171012","01173003","01173008","01173005","01171010","01173017","01174006","01173012","01173013"]
df_filtered6=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats6)]
df_poprefmerge6=pd.merge(df_filtered6,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_sayur=df_poprefmerge6[df_poprefmerge6["PopRef"]=="1"]
popref_sayur["PerSatuan"]=(popref_sayur["KOLOM6"]/popref_sayur["KOLOM5"])

fig6 =px.box(popref_sayur,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig6.update_layout(
    xaxis_title="Komoditas Sayur",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "06 Cek Outlier Konsumsi Sayur-Sayuran",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig6.update_xaxes(
    ticktext=["86.Bayam", "91.Buncis","92. Kacang Panjang","93.Tomat","96.Daun Ketela Pohon","102.Nangka Muda","105.Bawang Merah","108.Cabe Merah","110.Cabe Rawit"],  # new labels
    tickvals=["01171012","01173003","01173008","01173005","01171010","01173017","01174006","01173012","01173013"]                     # original values in the data
)

fig6.show()

/tmp/ipython-input-3548895086.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 07 Komoditas Kacang-Kacangan
import plotly.express as px
selected_cats7=["01168010","01194011","01194013"]
df_filtered7=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats7)]
df_poprefmerge7=pd.merge(df_filtered7,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_kacangkacangan=df_poprefmerge7[df_poprefmerge7["PopRef"]=="1"]
popref_kacangkacangan["PerSatuan"]=(popref_kacangkacangan["KOLOM6"]/popref_kacangkacangan["KOLOM5"])

fig7 =px.box(popref_kacangkacangan,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig7.update_layout(
    xaxis_title="Komoditas Kacang-Kacangan",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "07 Cek Outlier Nilai Konsumsi Kacang-Kacangan",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig7.update_xaxes(
    ticktext=["122.Kacang Tanah Tanpa Kulit", "125.Tahu","126.Tempe"],  # new labels
    tickvals=["01168010","01194011","01194013"]                     # original values in the data
)

fig7.show()

/tmp/ipython-input-959706496.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 08 Komoditas Buah-Buahan
import plotly.express as px
selected_cats8=["01167002-14","01165008-11","01162001","01162002-14","01167022-27"]
df_filtered8=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats8)]
df_poprefmerge8=pd.merge(df_filtered8,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_buah=df_poprefmerge8[df_poprefmerge8["PopRef"]=="1"]
popref_buah["PerSatuan"]=(popref_buah["KOLOM6"]/popref_buah["KOLOM5"])


fig8 =px.box(popref_buah,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig8.update_layout(
    xaxis_title="Komoditas Buah-buahan",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "08 Cek Outlier Nilai Konsumsi Buah-buahan",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig8.update_xaxes(
    ticktext=["131.Mangga", "136.Salak","137.Pisang","138.Pisang Lainnya","139.Pepaya"],  # new labels
    tickvals=["01167002-14","01165008-11","01162001","01162002-14","01167022-27"]                     # original values in the data
)

fig8.show()

/tmp/ipython-input-1322319723.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 09 Komoditas Minyak dan Kelapaa
import plotly.express as px
selected_cats9=["01154003","01167033"]
df_filtered9=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats9)]
df_poprefmerge9=pd.merge(df_filtered9,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_minyak_kelapa=df_poprefmerge9[df_poprefmerge9["PopRef"]=="1"]
popref_minyak_kelapa["PerSatuan"]=(popref_minyak_kelapa["KOLOM6"]/popref_minyak_kelapa["KOLOM5"])


fig9 =px.box(popref_minyak_kelapa,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig9.update_layout(
    xaxis_title="Komoditas Minyak dan Kelapa",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "09 Cek Outlier Nilai Konsumsi Minyak dan Kelapa",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig9.update_xaxes(
    ticktext=["155.Minyak Kelapa", "157.Kelapa"],  # new labels
    tickvals=["01154003","01167033"]                     # original values in the data
)

fig9.show()

/tmp/ipython-input-2726476630.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 10 Komoditas Bahan Minuman
import plotly.express as px
selected_cats10=[160,161,162,163,164,165]
df_filtered10=df_kp1[df_kp1["NOURUTKOMO"].isin(selected_cats10)]
df_poprefmerge10=pd.merge(df_filtered10,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_bahanminum=df_poprefmerge10[df_poprefmerge10["PopRef"]=="1"]
popref_bahanminum["PerSatuan"]=(popref_bahanminum["KOLOM6"]/popref_bahanminum["KOLOM5"])


fig10 =px.box(popref_bahanminum,x="NOURUTKOMO", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig10.update_layout(
    xaxis_title="Komoditas Bahan Minuman",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "10 Cek Outlier Nilai Konsumsi Bahan Minuman",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig10.update_xaxes(
    ticktext=["160.Gula Pasir","161.Gula Merah","162.Teh Bubuk","163.Teh Celup(sachet)","164.Kopi Bubuk","165.Kopi Instan (sachet)"],  # new labels
    tickvals=[160,161,162,163,164,165]                     # original values in the data
)

fig10.show()

/tmp/ipython-input-473316132.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 11 Komoditas Bumbu-Bumbuan
import plotly.express as px
selected_cats11=["01192001","01192005","01194003/4"]
df_filtered11=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats11)]
df_poprefmerge11=pd.merge(df_filtered11,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_bumbu=df_poprefmerge11[df_poprefmerge11["PopRef"]=="1"]
popref_bumbu["PerSatuan"]=(popref_bumbu["KOLOM6"]/popref_bumbu["KOLOM5"])


fig11 =px.box(popref_bumbu,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig11.update_layout(
    xaxis_title="Komoditas Bumbu-Bumbuan",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "11 Cek Outlier Nilai Konsumsi Bumbu-Bumbuan",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig11.update_xaxes(
    ticktext=["168.Garam","169.Kemiri","175.Terasi/Petis"],  # new labels
    tickvals=["01192001","01192005","01194003/4"]                     # original values in the data
)

fig11.show()

/tmp/ipython-input-1903884098.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 12 Komoditas Makanan Lainnya
import plotly.express as px
selected_cats12=["01115012","01115018/19"]
df_filtered12=df_kp1[df_kp1["KODECOICOP"].isin(selected_cats12)]
df_poprefmerge12=pd.merge(df_filtered12,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_bahanmakanan=df_poprefmerge12[df_poprefmerge12["PopRef"]=="1"]
popref_bahanmakanan["PerSatuan"]=(popref_bahanmakanan["KOLOM6"]/popref_bahanmakanan["KOLOM5"])


fig12 =px.box(popref_bahanmakanan,x="KODECOICOP", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
fig12.update_layout(
    xaxis_title="Komoditas Makanan Lainnya",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "12 Cek Outlier Nilai Konsumsi Bahan Makanan Lainnya",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
fig12.update_xaxes(
    ticktext=["183.Mie Instan","184.Kerupuk Mentah"],  # new labels
    tickvals=["01115012","01115018/19"]                     # original values in the data
)

fig12.show()

/tmp/ipython-input-4125396964.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## Komoditas Makanan Jadi Lainnya
import plotly.express as px
selected_cats_mj=[188,189,190,191,221]
df_filtered_mj=df_kp2[df_kp2["NOURUTKOMO"].isin(selected_cats_mj)]
df_filtered_mj["NOURUTKOMO"]=df_filtered_mj["NOURUTKOMO"].astype(str)
df_poprefmerge_mj=pd.merge(df_filtered_mj,populasi_referensi[["PopRef","ID_ruta"]],on="ID_ruta",how='left')
popref_mj=df_poprefmerge_mj[df_poprefmerge_mj["PopRef"]=="1"]
popref_mj["PerSatuan"]=(popref_mj["KOLOM6"]/popref_mj["KOLOM5"])


figmj =px.box(popref_mj,x="NOURUTKOMO", y="PerSatuan", hover_data=["NAMAKECAMA","NKS","NURT","NAMAKRT","R301","KOLOM5","KOLOM6"])
figmj.update_layout(
    xaxis_title="Komoditas Makanan Jadi",
    yaxis_title="Nilai konsumsi (dalam Rupiah)",
    title={
        "text": "Cek Outlier Makanan Jadi",
        "y":0.9,                # vertical position (0=bottom, 1=top)
        "x":0.5,                # horizontal position (0=left, 1=right)
        "xanchor": "center",    # anchor for x ("left","center","right")
        "yanchor": "top"        # anchor for y
    }
    )
# Rename tick labels
figmj.update_xaxes(
    ticktext=["188.Roti Tawar","189.Roti Manis","190.Kue Kering","191.Kue Basah","221.Rokok"],  # new labels
    tickvals=[188,189,190,191,221]                     # original values in the data
)

figmj.show()

/tmp/ipython-input-227595249.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-227595249.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

## 05.4 Pengecekan Kelengkapan Basket Comodity pada Populasi Referensi

In [ ]:
import plotly.graph_objects as go
import pandas as pd
df_poprefmergekp1=pd.merge(populasi_referensi,kp1_pivot,on="ID_ruta",how='left')
popref_kp1=df_poprefmergekp1[df_poprefmergekp1["PopRef"]=="1"]

kol_basket_com=[ 'NAMAKABUPA',
 'NAMAKECAMA', 'NAMADESA',
 'NAMAKRTDSR', 'NAMAKRT','ID_ruta',2,3,5,6,9,10,14,18,19,20,23,24,25,26,51,62,65,66,67,72,75,77,80,81,86,91,92,93,96,102,105,108,110,122,125,126,131,136,137,138,139,155,157,160,161,162,163,164,165,168,169,175,183,184]
popref01=popref_kp1[kol_basket_com]
numeric_cols = popref01.select_dtypes(include='number').columns

popref01['count_basket'] = (popref01[numeric_cols] > 0).sum(axis=1)
fig=px.bar(popref01,x="ID_ruta",y=popref01['count_basket'])


# Sample data

# Calculate the average of the 'Value' column
average_value = popref01['count_basket'].mean()

# Create the bar chart trace
bar_trace = go.Bar(x=popref01['ID_ruta'], y=popref01['count_basket'],
                   customdata=popref01[["NAMAKECAMA", "NAMADESA", "NAMAKRT"]],
                   hovertemplate=(
                       "<b>ID_ruta:</b> %{x}<br>"
                       "<b>Jumlah:</b> %{y}<br>"
                       "<b>Kecamatan:</b> %{customdata[0]}<br>"
                       "<b>Desa/Kel:</b> %{customdata[1]}<br>"
                       "<b>NamaKRT:</b> %{customdata[2]}<extra></extra>"
            ),

)

# Create the figure
fig = go.Figure(data=[bar_trace])

# Add the average line
fig.add_hline(y=average_value, line_dash="dot", line_color="red",
              annotation_text=f"Average: {average_value:.2f}",
              annotation_position="top left")


# Update layout for better presentation
fig.update_layout(
    title='Jumlah Komoditas Bahan Makanan yang dikonsumsi',
    xaxis_title='Category',
    yaxis_title='Jumlah Komoditas'
)

fig.show()

/tmp/ipython-input-363404429.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

## 05.5 Konsistensi Pendapatan dan Pengeluaran